### ISSUE TITLE
[BUG] hmip Adapter failing to start after upgrade of jscontroller to 3.0.14 => "error starting homematic: Error: undefined is not a valid state value"

### ISSUE THREAD

**Issue by mueckeflo** [iobroker-community-adapters/ioBroker.hmip#104]
After updating iobroker to 3.0.14, the hmip adapter status never turns to green.
Error logged is "error starting homematic: Error: undefined is not a valid state value"

**Comment by mdn-united** [comment]
Same problem here. I also find this in my log file:
(6621) starting. Version 0.0.11 in /opt/iobroker/node_modules/iobroker.hmip, node: v10.20.1, js-controller: 3.0.14
....
error | (31981) TypeError: Cannot read property 'id' of undefined     at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:193:50)     at WebSocket._ws.on (/opt/iobroker
error | (31981) uncaught exception: Cannot read property 'id' of undefined

**Comment by neorulez** [comment]
Same problem here as @mueckeflo after updating js-controller:


`hmip.0 | 2020-04-23 22:38:29.785 | error | (20849) Error: undefined is not a valid state value at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39 at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_module
-- | -- | -- | --
hmip.0 | 2020-04-23 22:38:29.781 | error | (20849) uncaught exception: undefined is not a valid state value

`

**Comment by RP70DP** [comment]
Auch hier gleiches Problem:
error starting homematic: Error: undefined is not a valid state value

**Comment by 1974Sascha** [comment]
Auch hier gleiches Problem nach Upgrade auf JS-Controller 3.0.x:
error starting homematic: Error: undefined is not a valid state value

**Comment by mueckeflo** [comment]
Bin mir nicht sicher ob sich das Problem mit js-controller 3.0.20 erledigt hat, oder weil ich die Token-Informationen gelöscht und den Adapter neu verbunden habe. Wie auch immer, mein Adapter ist jetzt wieder dauerhaft grün und verbunden. Somit hat sich (zumindest für mich) das Problem erledigt. (Ich habe meinen iobroker komplett neu aufgesetzt und alles auf den aktuellsten Stand gebracht)
Wenn noch mehr das Verhalten bestätigen könnten, dann könnten wir dieses Issue schließen...

**Comment by mdn-united** [comment]
Bei mir hat es sich mit dem Update auf 3.0.20 erledigt! Adapter wieder grün!

**Comment by mueckeflo** [comment]
Gelöst durch update des js-controllers auf 3.0.20 - Resolved by updating js-controller to 3.0.20
