### ISSUE TITLE
State value to be set is invalid...

### ISSUE THREAD

**Issue by kkickingereder** [iobroker-community-adapters/ioBroker.hmip#105]
Node.js 10.20.1
iobroker.admin 4.0.9

Also after complete deinstall and new install same error.

<img width="1232" alt="Bildschirmfoto 2020-04-22 um 20 16 15" src="https://user-images.githubusercontent.com/61472717/80018658-a091d100-84d6-11ea-84ea-32faa050c1dd.png">

**Comment by QoSi** [comment]
Hello, the same error...hope on new update coming soon

**Comment by RP70DP** [comment]
Selber Fehler hier:

hmip.0 | 2020-05-01 10:41:27.557 | warn | (4332) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
hmip.0 | 2020-05-01 10:41:27.556 | warn | (4332)  State value to set is invalid for  hmip.0.homes.1eb9ee9e-13f5-4e98-a4d2-e44d8dbee5ab.functionalHomes.securityAndAlarm.alarmEventDeviceChannel:  The state contains the forbidden properties deviceI
hmip.0 | 2020-05-01 10:41:27.161 | warn | (4332) This value will not be set in future versions. Please report this to the developer.
hmip.0 | 2020-05-01 10:41:27.160 | warn | (4332)  State value to set is invalid for  hmip.0.homes.1eb9ee9e-13f5-4e98-a4d2-e44d8dbee5ab.functionalHomes.securityAndAlarm.alarmEventDeviceChannel:  The state contains the forbidden properties deviceI

**Comment by Apollon77** [comment]
fixed in 1.0.x
