### ISSUE TITLE
hmip.0 HomeMatic IP Cloud-Zugriffspunkt not green

### ISSUE THREAD

**Issue by JogiBarbarski** [iobroker-community-adapters/ioBroker.hmip#106]
Hello, first of all many thanks for the great job you did there. I can't get the HMIP adapter to work. It is not possible to save the settings after entering the adapter data. And the errors from the log of the Raspberry Pi 4 look like this. Software and Raspberry Pi 4 are up to date. Best regards and thanks for everything.
hmip.0 2020-04-24 11:06:11.067 error (8452) error starting homematic: Error: undefined is not a valid state value
hmip.0 2020-04-24 11:05:31.450 error at WebSocket.emit (events.js:198:13)
hmip.0 2020-04-24 11:05:31.450 error at WebSocket._ws.on (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
hmip.0 2020-04-24 11:05:31.450 error at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0 2020-04-24 11:05:31.450 error at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:285:28)
hmip.0 2020-04-24 11:05:31.450 error at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:738:28)
hmip.0 2020-04-24 11:05:31.450 error at HmIpCloudAccesspointAdapter.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
hmip.0 2020-04-24 11:05:31.450 error at new Promise ()
hmip.0 2020-04-24 11:05:31.450 error at Promise (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16)
hmip.0 2020-04-24 11:05:31.450 error at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5744:21)
hmip.0 2020-04-24 11:05:31.450 error at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39
hmip.0 2020-04-24 11:05:31.450 error (7357) Error: undefined is not a valid state value
hmip.0 2020-04-24 11:05:31.449 error (7357) uncaught exception: undefined is not a valid state value
hmip.0 2020-04-24 11:05:31.105 error at WebSocket.emit (events.js:198:13)
hmip.0 2020-04-24 11:05:31.105 error at WebSocket._ws.on (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
hmip.0 2020-04-24 11:05:31.105 error at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0 2020-04-24 11:05:31.105 error at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:285:28)
hmip.0 2020-04-24 11:05:31.105 error at HmIpCloudAccesspointAdapter._updateHomeStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:738:28)
hmip.0 2020-04-24 11:05:31.105 error at HmIpCloudAccesspointAdapter.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
hmip.0 2020-04-24 11:05:31.105 error at new Promise ()
hmip.0 2020-04-24 11:05:31.105 error at Promise (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16)
hmip.0 2020-04-24 11:05:31.105 error at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5744:21)
hmip.0 2020-04-24 11:05:31.105 error at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39
hmip.0 2020-04-24 11:05:31.105 error (7357) Error: undefined is not a valid state value
hmip.0 2020-04-24 11:05:31.076 error (7357) uncaught exception: undefined is not a valid state value
hmip.0 2020-04-24 11:04:29.185 error (7357) error starting homematic: Error: undefined is not a valid state value

**Comment by vorlautb0y** [comment]
Same here... after updating js-controller today

**Comment by JogiBarbarski** [comment]
these are a few more bugs that pop up. Maybe it helps them. Thanks for your great job. Glad if I can use Siri again soon. Thank you very much.

hmip.0 | 2020-04-26 18:56:19.430 | error | at WebSocket.<anonymous> (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:152:18)
-- | -- | -- | --
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmCloudAPI._parseEventdata (/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:200:22)
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmIpCloudAccesspointAdapter._eventRaised (/opt/iobroker/node_modules/iobroker.hmip/main.js:262:28)
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmIpCloudAccesspointAdapter._updateDeviceStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:359:43)
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmIpCloudAccesspointAdapter._updateSingleKeyChannelStates (/opt/iobroker/node_modules/iobroker.hmip/main.js:596:28)
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmIpCloudAccesspointAdapter.setStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1577:16)
hmip.0 | 2020-04-26 18:56:19.430 | error | at new Promise (<anonymous>)
hmip.0 | 2020-04-26 18:56:19.430 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1578:16
hmip.0 | 2020-04-26 18:56:19.430 | error | at HmIpCloudAccesspointAdapter.setState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5744:21)
hmip.0 | 2020-04-26 18:56:19.430 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1581:39
hmip.0 | 2020-04-26 18:56:19.430 | error | (3648) Error: undefined is not a valid state value
hmip.0 | 2020-04-26 18:56:19.423 | error | (3648) uncaught exception: undefined is not a valid state value

**Comment by JogiBarbarski** [comment]
Läuft jetzt wieder. Danke

**Comment by JogiBarbarski** [comment]
Hallo, ich bekomme den tr-064.0 nicht zum Laufen. Habe die Fritz Box 7590 und die habe ich bereits neu gestartet. Aber es war ohne Erfolg. Der Adapter ist in den Instanzen grün. Es lassen sich aber keine Geräte suchen. In den Objekten taucht er auch nicht auf.
Mein System, auf dem der Iobroker läuft:Raspberry Pi 4, 8GB
ioBroker.admin 4.2.1
Node.js: v12.20.2
NPM: 6.14.6
js-controller
JS controller Installiert: 3.2.16
OS: linux
Stable (default)
Das ist der Fehler aus dem Log.

host.raspberrypi | 2021-02-16 16:12:40.666 | Fehler | Instanz system.adapter.tr-064.0 beendet mit Code 1 (JS_CONTROLLER_STOPPED) -- | -- | -- | -- tr-064.0 | 2021-02-16 16:12:39.989 | warnen | (19035) Beendet (JS_CONTROLLER_STOPPED): Schwerwiegender Fehler. Es kann keine Verbindung zu Ihrer FritzBox hergestellt werden. tr-064.0 | 2021-02-16 16:12:39.986 | Fehler | (19035) ~ tr-064.0 | 2021-02-16 16:12:39.985 | Fehler | (19035) ~~ Wenn Konfiguration, Netzwerk, IP-Adresse usw. in Ordnung sind, versuchen Sie, Ihre FritzBox neu zu starten tr-064.0 | 2021-02-16 16:12:39.984 | Fehler | (19035) ~~ Schwerwiegender Fehler. Es kann keine Verbindung zu Ihrer FritzBox hergestellt werden. tr-064.0 | 2021-02-16 16:12:39.983 | Fehler | (19035) ~ tr-064.0 | 2021-02-16 16:12:39.981 | Fehler | (19035) Fehler: connect ETIMEDOUT 192.168.188.1:49000 - {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"192.168.188.1","port":49000}

**Comment by Apollon77** [comment]
reopen?? Closed since april last year ....
