### ISSUE TITLE
Please add missing value for WeatherSensorPro (HmIP-SWO-PR)

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hmip#114]
Please add vaporAmount for WeatherSensorPro:
```
promises.push(this.setObjectNotExistsAsync('devices.' + device.id + '.channels.' + channel + '.vaporAmount', { type: 'state', common: { name: vaporAmount', type: 'number', role: 'info', read: true, write: true }, native: {} }));
```

**Comment by steckenpferd** [comment]
What is vaporAmount?

**Comment by RP70DP** [comment]
Dunst, der eine Trübung der Luft durch Wassertröpfchen oder Aerosole verursacht. Wird vom Pro-Sensor geliefert:
https://homematicip-rest-api.readthedocs.io/en/latest/_modules/homematicip/device.html

**Comment by redPanther** [comment]
> What is vaporAmount?

it is the absolute humidity. The sensor measures the absolute humidity in g/m3 and take the temperature and calculates the relative humidity.
example:
currently I have 11.2°C and 72% relH. if you calculate backwards e.g. with this tool https://www.calctool.org/atmospheric-thermodynamics/absolute-humidity you get 7.3 g/m3 absolue humidity.
and thats (rounded) the value of vaporAmount shown in iobroker (7.28600079)


BTW I get vaporAmount from my HmIP-STHO sensor.
