### ISSUE TITLE
hmip - unkown channel type  - PRESENCE_DETECTION_CHANNEL 

### ISSUE THREAD

**Issue by SWU-DEV** [iobroker-community-adapters/ioBroker.hmip#117]
undefined2020-05-12 17:56:31.350 - info: hmip.0 (863) unkown channel type - PRESENCE_DETECTION_CHANNEL - {"id":"3014F711A0000C1A4998B608","homeId":"f0961760-4ced-4555-9a69-933652970db4","label":"Präsenzmelder – Wohnzimmer","lastStatusUpdate":1589298991333,"type":"PRESENCE_DETECTOR_INDOOR","functionalChannels":{"0":{"label":"","deviceId":"3014F711A0000C1A4998B608","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_SABOTAGE","groups":["bdc9c8c8-180a-4fd1-a6b5-0d3b844e7572","fe1112e5-9e69-4f08-877a-e0899ceae098"],"unreach":false,"lowBat":false,"routerModuleEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-51,"rssiPeerValue":null,"configPending":false,"dutyCycle":false,"deviceOverloaded":false,"coProUpdateFailure":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceUndervoltage":false,"deviceOverheated":false,"temperatureOutOfRange":false,"devicePowerFailureDetected":false,"supportedOptionalFeatures":{"IFeatureDeviceCoProRestart":false,"IFeatureDeviceOverheated":false,"IFeatureDeviceUndervoltage":false,"IFeatureDeviceCoProUpdate":false,"IFeatureDeviceCoProError":false,"IFeatureDeviceOverloaded":false,"IFeatureDevicePowerFailure":false,"IFeatureDeviceIdentify":false,"IFeatureDeviceTemperatureOutOfRange":false},"sabotage":false},"1":{"label":"","deviceId":"3014F711A0000C1A4998B608","index":1,"groupIndex":1,"functionalChannelType":"PRESENCE_DETECTION_CHANNEL","groups":["bdc9c8c8-180a-4fd1-a6b5-0d3b844e7572","2c0206b1-ef27-4076-98f2-08ecae0830a2","5c6c6c60-a5da-4bb6-aa91-7a5bdd6af35b"],"presenceDetected":true,"illumination":22.7,"currentIllumination":null,"numberOfBrightnessMeasurements":1,"motionDetectionSendInterval":"SECONDS_240","motionBufferActive":true}},"oem":"eQ-3","manufacturerCode":1,"firmwareVersion":"1.4.0","firmwareVersionInteger":66560,"updateState":"UP_TO_DATE","liveUpdateState":"LIVE_UPDATE_NOT_SUPPORTED","availableFirmwareVersion":"1.4.0","modelType":"HmIP-SPI","serializedGlobalTradeItemNumber":"3014F711A0000C1A4998B608","modelId":303,"permanentlyReachable":true,"connectionType":"HMIP_RF"}

**Comment by SWU-DEV** [comment]
I fixed it on my own, here is the main.js as textfile
[main.txt](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/4617341/main.txt)

**Comment by jogibear9988** [comment]
@SWU-DEV as I said, I've no time to work on this.
could you create a pull req?

**Comment by Apollon77** [comment]
@SWU-DEV comparing the textfile itself is very hard to find your changes ... a PR on Github is not that difficult. just go to the file list and open the relevant file here in weg and klick on the pencil top right, then change the code and then sscroll down to tell that you want to propse that change

**Comment by Apollon77** [comment]
I tried to take over the changes on the two plaes ... it will be in 1.0.1 .. but next time a PR would be awesome

**Comment by Apollon77** [comment]
And even different here ... was in an other PR sand so already in 1.0.0 included
