### ISSUE TITLE
Homematic IP Lichtschalter HmIP-BSM

### ISSUE THREAD

**Issue by bekiss** [iobroker-community-adapters/ioBroker.hmip#13]
Ich habe einen Homematic IP Lichtschalter vom Typ "BRAND_SWITCH_MEASURING", den ich in der Version 0.0.2 nicht schalten und messen konnte.

Durch Hinzufügen von
	    case 'BRAND_SWITCH_MEASURING':

in der "Dateil main.js" 
bei den Funktionen "_updateDeviceStates(device)" und "_createObjectsForDevice(device)"
funktionieren nun die Lichtschalter.

Hier mein Änderungsvorschlag:
...
       switch (device.type) {
            case 'FULL_FLUSH_SWITCH_MEASURING':
	    case 'BRAND_SWITCH_MEASURING':
            case 'PLUGABLE_SWITCH_MEASURING': {
...

**Comment by steckenpferd** [comment]
Im Log zu sehen es geht um den HmIP-BSM
