### ISSUE TITLE
Homematic IP Wetterstation pro / weather station pro

### ISSUE THREAD

**Issue by mitsol** [iobroker-community-adapters/ioBroker.hmip#133]
I tried to integrate the weather station pro in iobroker. unfortunately i only get this data in channel 1:

acousticAlarmSignal | acousticAlarmSignal | state | info |   |   |   | editdeletebuild
-- | -- | -- | -- | -- | -- | -- | --
acousticAlarmTiming | acousticAlarmTiming | state | info |   |   |   | editdeletebuild
acousticWaterAlarmTrigger | acousticWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
functionalChannelType | functionalChannelType | state | info |   |   | WEATHER_SENSOR_PRO_CHANNEL | editdeletebuild
inAppWaterAlarmTrigger | inAppWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
moistureDetected | moistureDetected | state | level |   |   |   | editdeletebuild
raining | raining | state | info |   |   | false | editdeletebuild
sirenWaterAlarmTrigger | sirenWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
todayRainCounter | todayRainCounter | state | level |   |   | 0 | editdeletebuild
totalRainCounter | totalRainCounter | state | level |   |   | 0 | editdeletebuild
waterlevelDetected | waterlevelDetected | state | info |   |   |   | editdeletebuild
weathervaneAlignmentNeeded | weathervaneAlignmentNeeded | state | info |   |   | false | editdeletebuild
windDirection | windDirection | state | info |   |   | 92.5 | editdeletebuild
windDirectionVariation | windDirectionVariation | state | info |   |   | 22.5 | editdeletebuild
yesterdayRainCounter | yesterdayRainCounter | state | level |   |   | 0

there is no wind speed, temperature, humidity and brightness. Any suggestions how to fix this? Thank you

**Comment by mitsol** [comment]
All right, i found it myself! I just used the adapter version of this Github repo and not the official one of iobroker! Now all remaining data is available! Thanks for your work! I really appreciate it!

**Comment by Apollon77** [comment]
WHich version you nowuse?

**Comment by mitsol** [comment]
i just installed the version here from this git repo. This added some more resources:

acousticAlarmSignal | acousticAlarmSignal | state | info |   |   |   | editdeletebuild
-- | -- | -- | -- | -- | -- | -- | --
acousticAlarmTiming | acousticAlarmTiming | state | info |   |   |   | editdeletebuild
acousticWaterAlarmTrigger | acousticWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
actualTemperature | actualTemperature | state | info |   |   | 10.8 | editdeletebuild
functionalChannelType | functionalChannelType | state | info |   |   | WEATHER_SENSOR_PRO_CHANNEL | editdeletebuild
humidity | humidity | state | info |   |   | 72 | editdeletebuild
illumination | illumination | state | info |   |   | 4350 | editdeletebuild
illuminationThresholdSunshine | illuminationThresholdSunshine | state | level |   |   | 3500 | editdeletebuild
inAppWaterAlarmTrigger | inAppWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
moistureDetected | moistureDetected | state | level |   |   |   | editdeletebuild
raining | raining | state | info |   |   | false | editdeletebuild
sirenWaterAlarmTrigger | sirenWaterAlarmTrigger | state | info |   |   |   | editdeletebuild
storm | storm | state | info |   |   | false | editdeletebuild
sunshine | sunshine | state | info |   |   | true | editdeletebuild
todayRainCounter | todayRainCounter | state | level |   |   | 0 | editdeletebuild
todaySunshineDuration | todaySunshineDuration | state | info |   |   | 131 | editdeletebuild
totalRainCounter | totalRainCounter | state | level |   |   | 7.699999999999999 | editdeletebuild
totalSunshineDuration | totalSunshineDuration | state | info |   |   | 4476 | editdeletebuild
vaporAmount | vaporAmount | state | info |   |   | 7.105208607969205 | editdeletebuild
waterlevelDetected | waterlevelDetected | state | info |   |   |   | editdeletebuild
weathervaneAlignmentNeeded | weathervaneAlignmentNeeded | state | info |   |   | false | editdeletebuild
windDirection | windDirection | state | info |   |   | 10 | editdeletebuild
windDirectionVariation | windDirectionVariation | state | info |   |   | 22.5 | editdeletebuild
windSpeed | windSpeed | state | info |   |   | 9 | editdeletebuild
windValueType | windValueType | state | info |   |   | MAX_VALUE | editdeletebuild
yesterdayRainCounter | yesterdayRainCounter | state | level |   |   | 7.699999999999999 | editdeletebuild
yesterdaySunshineDuration | yesterdaySunshineDuration | state | info |   |   | 804

**Comment by Apollon77** [comment]
Yes the 1.0.0 is not yet released ... so issue solved with this version ?

**Comment by giant2000s** [comment]
Hallo. 

Bin Neu hier. Wo bekomme ich die Datei her? Wo und wie muss ich es einfügen.
Habe auch das Problem. möchte gerne die wetterdaten auf mein Magic Mirror anzeigen lassen.
IoBrocker habe ich auf meinem Synology server zum laufen bekommen. 

Danke für eure Hilfe.

**Comment by Apollon77** [comment]
Admin . Experten modus - Custom Install Button oben dann dort den adapter wählen und du bekommst diese experimentelle Version vom GitHub
