### ISSUE TITLE
Homematic IP Funk Taster mit iobroker Problem mit eindeutiger Tasten ID

### ISSUE THREAD

**Issue by MrSonei6** [iobroker-community-adapters/ioBroker.hmip#134]
Das Problem scheint mit allen Funktastern von HMIP mit Accespoint Anbindung zu bestehen.

Ich habe das Problem mit den
-HmIP-BRC2 Homematic IP Funk-Wandtaster und
-HmIP-WRC6 Homematic IP Funk-Wandtaster
andere haben das selbe Problem mit dem 8 Tasten Funkfernbedinung.
aber es scheint mit allen Funktastern und Funkfernbedinungen zu bestehen

Man sieht im ioBroker darin die Channels zum beispiel von  0 bis 6 bei dem 6 fach funk schalter, wobei 0 vermutlich nur für die Geräteconfig benötigt wird und 1-6 die einzelnen Kanäle sind. Problem: Ein Tastendruck auf irgended eine taste aktualisiert zwar den functionalChannelType, setzt ihn aber (bzw. haltet ihn) immer auf den Wert "SINGLE_KEY_CHANNEL" und das macht er für alle 6 Kanäle, ganz egal welche Taste ich drücke. Kurz gesagt: Ich kann zwar den Tastendruck erkennen, aber nicht welche Taste gedrückt wird.

Was mir auch zusätzlich aufgefallen ist
Wenn ich mein Script auf "Play" setze im ioBroker,  dann schaltet das script plötzlich von ganz alleine nach einer gewissen zeit. Ich denke das alle Funkschalter ein "Ich bin am leben signal" alle heiligen zeiten sendet. Sprich bei mir schaltet sich dann das Licht von alleine ein ;( so nach ca 20 min.
Und natürlich schaltet es auch ein wenn ich auf eine der anderen Tasten (2-6) drücke obwohl ich das Script auf Taste 1 gelegt habe.

Ich hoffe sehr, dass uns jemand hilft.
Bei Connrad Connect lief es ohne Problme mit den Funktstern.

``
on({id: 'hmip.0.devices.3014F711A00019DA499460B0.channels.1.on', change: "any"}, function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  setState("hmip.0.devices.3014F711A00008D8A9AC16D9.channels.1.on"/*on*/, true);
``

**Comment by jogibear9988** [comment]
das problem ist, die taster kann man nur erkennen wenn man sie mit was verknüpft. das ist auch an der homematic zentrale so, aber da gibts ja virtuelle kanäle (zumindest in der vccu)
daher nutze ich selbst auch hmip nicht mehr (und ich wollte auch nicht das ich das internet brauche damit mein licht angeht)

**Comment by Apollon77** [comment]
Um hier mehr zu sehen wäre ein debug log sehr gut. am besten debug log aktivieren, mal so eine schaltaktion machen und log zeigen. Bitte von der Platte und nicht aus dem Admin kopieren

**Comment by jogibear9988** [comment]
win nicht verknüpfter taster sendet nix...

**Comment by MrSonei6** [comment]
Ja dann müsste man doch irgendwie so ein dummy verknüpfung virtuell bauen können oder?
Ich hab mir aktuell so beholfen das ich bei meinem 6 Fach funk taster den ich für meine Logitech Harmony aktionen verwende einfach jeweils in der app eine verknüpfung für jede einzelen Taste gebaut habe. 
-Taste 1 schaltet einen Heizkörper Termostat aug 8 Grad 
-Taste 2 schaltet einen Heizkörper Termostat aug 9 Grad 
-Taste 3 schaltet einen Heizkörper Termostat aug 10 Grad 
-Taste 4 schaltet einen Heizkörper Termostat aug 11Grad 
-Taste 5 schaltet einen Heizkörper Termostat aug 12 Grad 
-Taste 6 schaltet einen Heizkörper Termostat aug 13 Grad 

und so kann ich in ioBroker abfragen wenn dieses Termonstat auf 8 Grad steht bitte führe Aktion X aus. 

Aber das ist natürlich totaler schmarng. Aber ein Workaround zur zeit ist e. aber das beste wäre es wenn man hier eie virtuelle verknüpfung anlegen könnte, und die dann abfragen lässt.  
Wie geht das?

**Comment by Apollon77** [comment]
nothing where adapter can do anything
