### ISSUE TITLE
Heizkörperthermostate: Boost Funktion

### ISSUE THREAD

**Issue by Totto973** [iobroker-community-adapters/ioBroker.hmip#146]
Leider kann man mit einer Homematic IP Bridge (mit einer CCU soll es angeblich funktionieren) keinen Boost bei den Heizkörperthermostaten auslösen.

Wäre wirklich super, wenn sich jemand erbarmen würde, und dies vielleicht bis zum Beginn der kommenden Heizperiode implementieren könnte.

Vielen Dank dafür im Voraus! :)

**Comment by SliX185** [comment]
Die Boostfuntion ist schon seit geraumer Zeit implementiert und unter der jeweiligen Gruppe zu finden.
groups -> "Dein Raum" -> boostMode = true/false


Close?

**Comment by Totto973** [comment]
Ja, vielen Dank. Da hab' ich leider nicht geschaut...

Vielen Dank für die Info! Kann natürlich geschlossen werden!

Gruß
Totto

Am Mo., 22. Juni 2020 um 20:24 Uhr schrieb Sigi Liegl <
notifications@github.com>:
