### ISSUE TITLE
Durchgangssensor HmIP-SPDR Werte auslesen (Channels 2-4 fehlen)

### ISSUE THREAD

**Issue by SmartHomeNeuling** [iobroker-community-adapters/ioBroker.hmip#147]
Hallo,

ich bin nicht sicher ob das hier die richtige Stelle für meine Nachfrage ist, aber ich habe heute angefangen mich mit dem ioBroker auseinanderzusetzen und konnte mithilfe dieses Adapters meine Geräte vom HmIP-AP integrieren. Ich würde nun gerne ein Skript schreiben, dass mit den Daten des Durchgangssensors feststellt ob in einem Raum mindestens eine Person ist oder nicht. Ich finde nun leider keine Option um die nötigen Daten auszulesen. Laut der Device Documentation sollte diese Information in Channel 2 bzw. 3 liegen (je nach Durchgangsrichtung), allerdings tauchen im ioBroker nur die Channels 0 und 1 auf.

Ist das ein Problem des Adapters oder habe ich etwas falsch gemacht? Kann mir jemand weiterhelfen?

**Comment by SliX185** [comment]
Hallo,

Der HMIP-SPDR (PASSAGE_DETECTOR_CHANNEL) ist noch garnicht im Adapter implementiert... 

Ein debug log vom Sensor wäre hilfreich und dann noch Geduld, bis wer Zeit hat ihn zu integrieren.

**Comment by SmartHomeNeuling** [comment]
Oh, ok. Das wusste ich nicht, ich habe nur gesehen, dass der Sensor in der Geräteliste auftaucht.

Wie bekomme ich denn so ein debug log? (Bitte entschuldige die evtl. blöde Frage, bin noch nicht richtig in der Materie drin)

**Comment by SliX185** [comment]
Du kannst, wenn du im Iobroker auf Instanzen gehst, bei dem Adapater die Logstufe einstellen. Standardmäßig steht diese auf "Info"
Wenn du "Debug" auswählst, kommen alle Informationen von deinen angelernten Module ins Log und somit auch der noch nicht integrierte.

Was aber eigentlich schon hinfällig ist, da ich schon von der coreGreenberet API alle Informationen haben sollte.

Oben siehste Du auch schon ein Pull Request, was Dein Problem lösen sollte, sofern ich alles richtig gemacht habe.
Also nur noch bisschen gedulden, und es sollte mit ins Repo kommen.

**Comment by SmartHomeNeuling** [comment]
ach cool, vielen dank :) ich sehe schon, da gibt es noch sehr viel zu lernen. Gibt es eigentlich irgendwo ein Tutorial (oder mehrere) mit dem man sich gut in die skript-erstellung im iobroker einarbeiten kann? Ich finde nur sachen auf sehr niedrigem Niveau (ich weiß z.b. schon was Variablen und Funktionen sind) oder auf sehr hohem Niveau, wo schon sehr viel vorausgesetzt wird. Ich würde mich gerne da noch weiter einarbeiten, aber finde noch keinen richtigen zugang

**Comment by SliX185** [comment]
Grundsätzlich sind Javascript Kenntnisse vom Vorteil, ich hab z.b mit Webseiten meine ersten Javascript Erfahrungen gemacht.
Sonst kann dir auch das https://www.iobroker.net/docu/index-43.htm?page_id=5385&lang=de
sehr hilfreich sein.
Gibt viele Kanäle wo du was findest um dich weiter zu bilden, aber jetzt genau der eine für iobroker Scripts speziell... Kenn ich leider keinen.

**Comment by Apollon77** [comment]
@SliX185 a PR for your change would be awesome

**Comment by SliX185** [comment]
@Apollon77 
PR https://github.com/iobroker-community-adapters/ioBroker.hmip/pull/148 ?

**Comment by Apollon77** [comment]
hehe ... hatte in meinem fork gesucht :-)) Checke

**Comment by Apollon77** [comment]
check 1.1.0
