### ISSUE TITLE
Homematic IP Alarm-Sirene innen

### ISSUE THREAD

**Issue by Ma-ster77** [iobroker-community-adapters/ioBroker.hmip#16]
2019-01-19 13:04:50.225 - silly: hmip.0 updateDeviceStates - ALARM_SIREN_INDOOR - {"id":"3014F711A0000AD5699C69CE","homeId":"8c0eeaeb-1f7b-4415-b84d-42edc64eb7f5","label":"Alarmsirene","lastStatusUpdate":1547899375716,"type":"ALARM_SIREN_INDOOR","functionalChannels":{"0":{"label":"","deviceId":"3014F711A0000AD5699C69CE","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_SABOTAGE","groups":["baf3564c-aab7-4be6-8c90-766cec1a0201","52af37c4-5bfb-46ab-a1ce-f54c4042aeb3"],"unreach":false,"lowBat":false,"routerModuleEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-56,"rssiPeerValue":null,"configPending":false,"dutyCycle":false,"sabotage":false},"1":{"label":"","deviceId":"3014F711A0000AD5699C69CE","index":1,"groupIndex":1,"functionalChannelType":"ALARM_SIREN_CHANNEL","groups":["cfc67c21-1c72-48de-8016-ff61931a7c7e","52af37c4-5bfb-46ab-a1ce-f54c4042aeb3","fd00c14b-234a-4da6-9c23-4aec1e4de9d0"]}},"firmwareVersionInteger":66064,"updateState":"UP_TO_DATE","liveUpdateState":"LIVE_UPDATE_NOT_SUPPORTED","oem":"eQ-3","manufacturerCode":1,"firmwareVersion":"1.2.16","availableFirmwareVersion":"1.2.16","serializedGlobalTradeItemNumber":"3014F711A0000AD5699C69CE","modelType":"HmIP-ASIR","permanentlyReachable":true,"modelId":298}

**Comment by jogibear9988** [comment]
gibt die denn auch infos zurück?
was soll man damit machen können? nur einschalten?
ich könnte mal probieren ob das normal 'on' geht, sonst weiß ich im moment auch nicht.

**Comment by jogibear9988** [comment]
hab mal on eingebaut, bitte test ob man sie damit einschalten kann

**Comment by Ma-ster77** [comment]
Ja, man kann die nur ein und ausschalten. Man kann die in Kombination mit einem Tür und Fensterkontakt als Alarmanlage nutzen.

**Comment by jogibear9988** [comment]
geht das mit dem on?

**Comment by Ma-ster77** [comment]
Kann das nicht testen weil in den Objekten kein Schalter ist den ich ansteuern kann. Ich bin auf der Version 0.0.2 und bekomme das Update auf 0.0.3 nicht hin. Mit der Katze über die URL macht er das Update nicht.

**Comment by jogibear9988** [comment]
> Kann das nicht testen weil in den Objekten kein Schalter ist den ich ansteuern kann. Ich bin auf der Version 0.0.2 und bekomme das Update auf 0.0.3 nicht hin. Mit der Katze über die URL geht das Update nicht.

frag mal im forum, sollte nichts spezielles mit dem adapter sein, bzw. weiß ich dazu nichts

**Comment by jogibear9988** [comment]
> Im Log zu sehen es geht um die HmIP-ASIR

könntest du einen pull req für die readme.md erstellen?

**Comment by Ma-ster77** [comment]
Habe schon im Forum nachgefragt. Vielleicht kann mir da einer helfen. Sobald ich das Problem gelöst habe schaue ich nach ob ich sie schalten kann.

**Comment by Ma-ster77** [comment]
@jogibear9988
So, nach langen hin und her habe ich das Update hin bekommen aber unter Objekte / Devices gibt es bei der alatmsir3ne kein Switch oder State den man schalten kann. Es gibt nur  Label, model Type und Type Mehr nicht.

**Comment by jogibear9988** [comment]
kann man denn über die app die sirene direkt ansteuern oder geht das nur wenn das haus ein alarm auslöst?

**Comment by Ma-ster77** [comment]
Habe eben mal eben in der Homematic IP App nachgesehen. Da kann man leider nicht direkt die Alarmsirene ansteuern. Lediglich die Zuordnung kann man auswählen. Aber es muss doch sicher irgendwie möglich sein die anzusteuern. Weil die App bzw der Access Point schaltet sie ja auch irgendwie ein. Würde dir da gern weiter helfen jedoch kenne ich mich mit der Adapterentwicklung garnicht aus.

**Comment by jogibear9988** [comment]
ich kann nur das steuern was auch die app kann, da wir die cloud api verwenden und nicht den ap steuern.

**Comment by steckenpferd** [comment]
Falls es helfen würde kann ich das Gerät auch zur Verfügung stellen

**Comment by Ma-ster77** [comment]
Man kann ja den Hüllschutz bzw den Vollschutz in der App schalten. Kann man darüber nicht eventuell die Sirene ansteuern? Quasi auf einem Umweg.

**Comment by jogibear9988** [comment]
> Falls es helfen würde kann ich das Gerät auch zur Verfügung stellen

nicht wirklich. wenn es die api nicht her gibt, wüsste ich auch nicht wie es geht. 

und die api ist aus der app

**Comment by jogibear9988** [comment]
denke mit einer richtigen homematic zentrale oä. geht es. aber über den cloud adapter halt nicht

**Comment by Ma-ster77** [comment]
Vielleicht geht ja der Umweg über die Alarm Fernbedienung. Vielleicht kann man über den Umweg die Sirene schalten.

**Comment by jogibear9988** [comment]
keine ahnung, geht das in der app?

**Comment by Ma-ster77** [comment]
In der App kann man zumindest den Vollschutz und den Hüllschutz schalten. Die Sirene kann man in der App nirgendwo direkt schalten.

**Comment by jogibear9988** [comment]
hab ich ja auch eingebaut hmip.0.homes.25b9a600-e6e5-443f-a8f6-556e856da5d0.functionalHomes.securityAndAlarm.setSecurityZonesActivationExternal

**Comment by Ma-ster77** [comment]
Naja, vielleicht hat ja noch einer ne Idee wie man die Sirene schalten kann.

**Comment by coreGreenberet** [comment]
Mir wäre hier leider auch nichts bekannt =(
man könnte höchstens einen "testton" abspielen lassen, aber das geht dann vermutlich über alle sirenen und nicht nur über eine bestimmte

**Comment by Ma-ster77** [comment]
Naja, ich habe nur eine Sirene und ich denke bei den meisten wird dies genau so sein. Von daher wäre ein "Testton" besser wie nichts.

**Comment by coreGreenberet** [comment]
ich habe leider keiner Alarmsirene, darum kann ich es selbst nicht testen...
Vom konzept her wäre es wie der Testton den du über die App ansteuern kannst. Würde dieser ausreichen? bzw. ist dieser überhaupt laut genug?

**Comment by Ma-ster77** [comment]
So, ich habe mich eben mal ran gesetzt. Leider tut sich nichts wenn ich Alarm Active auf true setze. Habe alle Möglichkeiten die es dort geben könnte versucht. Alles ohne Erfolg. Aber auch die App gibt dann keine Info das sich irgendwas geändert hat. Das hat mich ein wenig gewundert. Normalerweise würde sich ja irgendwas in der App tun.

**Comment by Ma-ster77** [comment]
Habe dir alles was in Objekte/Homes/Security and Alarm drin ist per Telegram geschickt. Vielleicht hilft das ja ein wenig.

**Comment by jogibear9988** [comment]
ich habe jetzt gerade nochmal 3 signale eingebaut, musst mal prüfen

SetOnTime
TestSignalOptical
SetSignalOptical

**Comment by steckenpferd** [comment]
Kurze Frage zu den Updates - nochmal neu die 0.0.5 installieren oder schnürrst du eine 0.0.6 ?

**Comment by Ma-ster77** [comment]
Wo sollen denn die States auftauchen? Habe nochmals ein Update über die katze per URL gemacht aber die States werden in Homes/Funktional Homes Security and Homes nicht angezeigt.

Habe eben auch nochmal alles durchforstet und dabei unter Devices bei der Alarm Sirene unter Channel 1 einen Switch gefunden der On heißt. Aber auch bei dem tut sich nichts wenn ich per Switch im Vis auf on/Off bzw true/false schalte.

**Comment by Ma-ster77** [comment]
Alles versucht, jedoch ohne Erfolg. Im Dropdown sind Werte um "Alarmlichter" zu steuern. Aber da tut sich nichts. Wo kann man denn den Testalarm bzw Testton den Greenberet erwähnt hatte aktivieren?

**Comment by jogibear9988** [comment]
denke mit diesen api befehlen sollte das eigentlich gehen

**Comment by Ma-ster77** [comment]
Kann natürlich sein das da ein Bedienfehler  meinerseits besteht. Wüsste aber auch nicht was ich da falsch gemacht habe. Vielleicht findet sich noch einer mit der Sirene der das Testen kann.

**Comment by steckenpferd** [comment]
Schreib mal ins Forum oder Facebook.

**Comment by jogibear9988** [comment]
das problem ist 

SetOnTime
TestSignalOptical
SetSignalOptical

muss man eine gruppen id übergeben, ich weiß nicht für welche gruppen das gilt etc.

ich habe keine, kann da also nix testen

hab die befehle im git repo mal für alle gruppen hinzugefügt, teste mal bitte mit welcher/ob etwas passiert

**Comment by coreGreenberet** [comment]
das geht nur bei ALARM_SWITCHING Gruppen und für einen Ton müssen wir einen Testton abspielen

```
    def test_signal_acoustic(self,
                            signalAcoustic=AcousticAlarmSignal.FREQUENCY_FALLING):
        data = {"groupId": self.id, "signalAcoustic": signalAcoustic}
        return self._restCall("group/switching/alarm/testSignalAcoustic", body=json.dumps(data))
```

```python
class AcousticAlarmSignal(AutoNameEnum):
    DISABLE_ACOUSTIC_SIGNAL = auto()
    FREQUENCY_RISING = auto()
    FREQUENCY_FALLING = auto()
    FREQUENCY_RISING_AND_FALLING = auto()
    FREQUENCY_ALTERNATING_LOW_HIGH = auto()
    FREQUENCY_ALTERNATING_LOW_MID_HIGH = auto()
    FREQUENCY_HIGHON_OFF = auto()
    FREQUENCY_HIGHON_LONGOFF = auto()
    FREQUENCY_LOWON_OFF_HIGHON_OFF = auto()
    FREQUENCY_LOWON_LONGOFF_HIGHON_LONGOFF = auto()
    LOW_BATTERY = auto()
    DISARMED = auto()
    INTERNALLY_ARMED = auto()
    EXTERNALLY_ARMED = auto()
    DELAYED_INTERNALLY_ARMED = auto()
    DELAYED_EXTERNALLY_ARMED = auto()
    EVENT = auto()
    ERROR = auto()
```

**Comment by Ma-ster77** [comment]
So, heute bin ich zum testen gekommen. Es funktioniert. Man bekommt einen Testton nach Wahl ausgegeben. Und das auch bei voller Lautstärke. Leider wird der Tom nur ein paar Sekunden abgespielt und endet automatisch. Und Objekte / Groups / testSignalAcoustic kann man den Ton auswählen welcher wiedergegeben werden soll. Sobald man die Auswahl bestätigt, geht  die Sirene ein paar Sekunden los. Schöne Ware es wenn man mit einem Switch State die Sirene ein und ausschalten kann. Wäre dies möglich?

**Comment by jogibear9988** [comment]
nein, wir können nur nutzen was die api hergibt

**Comment by jogibear9988** [comment]
das kannst du dir ja über den javascript adapter bauen, das er das signal immer wieder triggert

**Comment by Ma-ster77** [comment]
Hast gerade ein Blockly dafür parat? Ich bin nämlich auch ein "nicht Programmierer".

**Comment by steckenpferd** [comment]
Zu empfehlen:
https://youtu.be/G_gFCqzebN8
https://youtu.be/nkocCDUUlbk

**Comment by jogibear9988** [comment]
ich schick einen, baue gerade noch einen zusätzlichen befehl in blockly ein, das es einfacher wird

**Comment by Ma-ster77** [comment]
@Steckenpferd schaue ich mir an.

@jogibaer9988 Super, vielen Dank.

**Comment by jogibear9988** [comment]
Habs gebaut, aber dazu wird ein neuer Befehl im Javascript adapter benötigt:

Erstelle morgen dafür ein Pull Req...

<img width="604" alt="bildschirmfoto 2019-01-24 um 23 32 01" src="https://user-images.githubusercontent.com/364896/51712938-b349fb80-2030-11e9-8afd-98309bf4c2f5.png">

**Comment by jogibear9988** [comment]
Wenn man nun das Objekt "Test" setzen würde würde alle 1s wieder angetriggert.

Aber der Befehl "Warten" fehlt noch im Javascrip Adapter

**Comment by steckenpferd** [comment]
https://forum.iobroker.net/viewtopic.php?t=5505#p56007
