### ISSUE TITLE
Logo auf Startseite tauschen

### ISSUE THREAD

**Issue by steckenpferd** [iobroker-community-adapters/ioBroker.hmip#17]
Kosmetischer Issue: Bitte das Logo der “klassischen” Homematic gegen das neue Logo von Homematic IP tauschen. Könnte sonst zu Verwirrung führen.

**Comment by jogibear9988** [comment]
kannst mir das logo als png zur verfügung stellen?

**Comment by steckenpferd** [comment]
So aber jetzt muss es geklappt haben
