### ISSUE TITLE
Cant create Token, Stuck by "Press Blue Button"

### ISSUE THREAD

**Issue by tehmilcho** [iobroker-community-adapters/ioBroker.hmip#175]
**Describe the bug**  
Hello, i got today my Access point but i cant create the Token for Ioborker, im stuck by "Press blue Button", i pressed the button multiple times but nothing happens.

**To Reproduce**  
Follow the Token creation like here https://www.youtube.com/watch?v=kXWfJRUYJIA&lc=Ugzpd0FfyymG_508yhB4AaABAg.9CcyH8NjLuv9Clvigfn5bz discribed

**Expected behavior**  
Create the Token to use the Adapter  :)

**Screenshots & Logfiles**  
hmip.0 | 2020-08-29 11:50:26.173 | info | (11873) auth step 2
-- | -- | -- | --
hmip.0 | 2020-08-29 11:50:26.005 | info | (11873) auth step 1
hmip.0 | 2020-08-29 11:50:25.808 | info | (11873) started token request
hmip.0 | 2020-08-29 11:50:20.960 | info | (11873) token not yet created
hmip.0 | 2020-08-29 11:50:20.935 | info | (11873) starting. Version 1.2.0 in /opt/iobroker/node_modules/iobroker.hmip, node: v10.22.0, js-controller: 3.1.4
host.leetwerkiobroker | 2020-08-29 11:50:19.951 | info | instance system.adapter.hmip.0 started with pid 11873

**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: 3.1.4 
 - Node version: v10.22. 
 - Operating system: LInux-Ubuntu 

Also got a "KEY" and a "PW" on the Backside of my Accesspoint additional to the SGTIN and the QR.. until now i cant find any info about the "KEY" and "PW".

**Comment by Apollon77** [comment]
Already fixed in 1.2.1+

**Comment by tehmilcho** [comment]
Here i get a newer Version? Via Repo Default "1.2.0" is the latest and with Repo "lastest" i only the "0.0.11"
