### ISSUE TITLE
Batterie Values for the Devices

### ISSUE THREAD

**Issue by tehmilcho** [iobroker-community-adapters/ioBroker.hmip#176]
**Is your feature request related to a problem? Please describe.**
Hello, i know the Homematic App can send you Pushes etc when a devices has a low batterie value,  but IObroker dont have this values for the batterie-state right now. And this everytime a pain in the A** when work with Accu / batterie devices.

I think because the App know this Value there must be the information anywhere for the batterie.  

**Describe the solution you'd like**
Add Batterie State to "info" from the Device, so that you can process this information with other adapters/scripts (send telegram or do something else)

**Comment by Apollon77** [comment]
Please set adapter to debug log and try to find out the json from a device that has a battery info and post here please.

**Comment by Apollon77** [comment]
Ps:why closed?

**Comment by tehmilcho** [comment]
It's already in it...with lowbat true or false.. That's enough. But after I get the adapter working the fristtime there wars only on channel bytheway devices without this info. Then I added some more devices to hmip and reboot the adapter and then I get a 2nd channel by the devices with this info. So I closed the issue :-)

**Comment by Apollon77** [comment]
Ahh ok. ... cool
