### ISSUE TITLE
Eingefügte HmIP Devices auf Startseite

### ISSUE THREAD

**Issue by steckenpferd** [iobroker-community-adapters/ioBroker.hmip#18]
Bitte auf die Start/Readme Seite die bisher zugefügten Device (min. technischen Namen z.B. HmIP-ASIR) posten. Danke

**Comment by steckenpferd** [comment]
Pull-Req für README.md erstellt

**Comment by jogibear9988** [comment]
wo???

**Comment by steckenpferd** [comment]
So aber jetzt muss es (hoffentlich) geklappt haben
