### ISSUE TITLE
Remains stuck at (3258) auth step 2

### ISSUE THREAD

**Issue by Hansderlump** [iobroker-community-adapters/ioBroker.hmip#180]
Hello,

by pressing on "Start creating Token", it stucks at step 2:

hmip.0 | 2020-09-11 19:03:01.165 | info | (3258) auth step 2
hmip.0 | 2020-09-11 19:03:01.093 | info | (3258) auth step 1
hmip.0 | 2020-09-11 19:03:00.999 | info | (3258) started token request

I tried it a few times but it doesn't work. The button "press blue button on accespoint" doesnt dissapear after pressing the button on my homematic ip. 

![image](https://user-images.githubusercontent.com/7850371/92953991-f73a8000-f462-11ea-883b-237d1629c220.png)

Homeatic ip is up to date
NodeJS version is v.12.18.3
HomeMaticIP Cloud AccessPoint Adater is version 1.2.0

Could you please check?

Regards,
Hansderlump

**Comment by Apollon77** [comment]
use 1.2.2 please

**Comment by karsten089** [comment]
I have the same issue. Where do I find 1.2.2? It only shows 1.2.0.

**Comment by Apollon77** [comment]
1.2.2 should be in Latest Repository. I will update stable soon

**Comment by Apollon77** [comment]
PS: Hm .. 1.2.0 is laterst repo too ... so how you installed it?

**Comment by Apollon77** [comment]
stable will be updated this afternoon

**Comment by karsten089** [comment]
Awesome :-)

**Comment by Hansderlump** [comment]
Really nice! Now it works. Thanks a lot :)
