### ISSUE TITLE
unknown channel type - MULTI_MODE_INPUT_SWITCH_CHANNEL - Schaltaktor für Hutschienenmontage – 4-fach

### ISSUE THREAD

**Issue by backons** [iobroker-community-adapters/ioBroker.hmip#181]
unknown channel type - MULTI_MODE_INPUT_SWITCH_CHANNEL - {"id":"1234","homeId":"1234","label":"Schaltaktor für Hutschienenmontage – 4-fach","

Gerät: HmIP-K-DRSI4

**Comment by Apollon77** [comment]
Thank you!, Duplicate #143
