### ISSUE TITLE
add write access to temperatureOffset and operationLockActive

### ISSUE THREAD

**Issue by Tomba1889** [iobroker-community-adapters/ioBroker.hmip#185]
It may be possible to add a write access to the objects temperatureOffset and operationLockActive. So i can simulate my wall thermostat to the valve temperature.

**Comment by Apollon77** [comment]
What exactly you mean? It is not known how to send updated data to hmip server

**Comment by Tomba1889** [comment]
yes it works perfect for hmip.0.devices.<ID>.channels.1.setPointTemperature but there are some objects that are only readable:
hmip.0.devices.<ID>.channels.1.temperatureOffset
hmip.0.devices.<ID>.channels.0.operationLockActive

**Comment by Apollon77** [comment]
Yes they are only readable becuse writing would not make any sense because then values gets messed up and a change will never be send to HMIP ... so why it should be writable then?

**Comment by Tomba1889** [comment]
I want to control the operationLock via Homekit, so i can easy turn it on or off.
Secandly, i have ich third-party Temperaturesensor, so i want to use the Offsetvalue to simulate the temperature to the valve.

**Comment by SliX185** [comment]
OperationLock is already implemented and works in version 1.3.0 (thanks to @Apollon77) 
Maybe you need to delete or recreate the states if it's not working.

Unfortunally you wont't be able to control the temperatureOffset...  The API just cannot handle it.

**Comment by Apollon77** [comment]
@Tomba1889 dfid you tried what @SliX185 said?

**Comment by Tomba1889** [comment]
@SliX185 thx the OperationLock works. A working TemperatureOffset would be very nice :)

**Comment by Apollon77** [comment]
Sorry, but it is currently not known on how to set the offset ... noone has "sniffed" that from the API so far
