### ISSUE TITLE
functionalHomes.securityAndAlarm.active is always true

### ISSUE THREAD

**Issue by aehs** [iobroker-community-adapters/ioBroker.hmip#189]
The Property functionalHomes.securityAndAlarm.active is always true, even when the 
alarm system disarmed.

**To Reproduce**  
1. Go to hmip.0.homes.XXX-XXXX-XXXX.functionalHomes.securityAndAlarm
2. Click on  securityAndAlarm.setSecurityZonesActivationInternalAndExternal
3. Scroll up to securityAndAlarm.active and convince yourself that the value is true
4. Click on securityAndAlarm.setSecurityZonesActivationNone
5. Scroll up to securityAndAlarm.active and convince  yourself that the value is still true

**Expected behavior**  

1. after clicking on securityAndAlarm.setSecurityZonesActivationInternalAndExternal the value of securityAndAlarm.active  should be chaged to **true**

2. after clicking on securityAndAlarm.setSecurityZonesActivationNone the value of securityAndAlarm.active  should be chaged to **false**

3. after clicking on securityAndAlarm.setSecurityZonesActivationInternalAndExternal the value of securityAndAlarm.active  should be chaged to **true**

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 3.1.6
 - Node version: 10.22.0
 - Operating system: linux

**Comment by Apollon77** [comment]
Please enable debug log and do exactly these steps and attach the debug log please

**Comment by aehs** [comment]
Hello Apollon77, 
here are the logs.


![image](https://user-images.githubusercontent.com/19493653/96587367-8b112e80-12e2-11eb-8b38-694d5f90f8a9.png)


hmip.0 | 20.10.2020   14:41 | debug | (14897)   No home in SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
-- | -- | -- | --
hmip.0 | 20.10.2020   14:41 | info | (14897)   state change - setSecurityZonesActivationInternalAndExternal - id - value   true
hmip.0 | 2020-10-20   14:41:00.021 | debug | (14897)   No home in SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
hmip.0 | 20.10.2020   14:40 | info | (14897)   state change - setSecurityZonesActivationNone - id - value true
hmip.0 | 20.10.2020   14:40 | debug | (14897)   No home in SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
hmip.0 | 20.10.2020   14:40 | info | (14897)   state change - setSecurityZonesActivationInternalAndExternal - id - value   true
  |   |   |

**Comment by Apollon77** [comment]
Hm ... it seems that in the event no content is in ... please try GitHub version (will be same version). Restart adapter after install and stay with Debug log. I now implemented that the hole is re-read if the data are missing for SECURITY_JOURNAL_CHANGED event

**Comment by aehs** [comment]
Hi, the GitHub version is installed. Here is the log:

hmip.0 | 23.10.2020   19:30 | debug | (31432)   system.adapter.admin.0: logging true
-- | -- | -- | --
hmip.0 | 23.10.2020   19:30 | debug | (31432)   Read Home for SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
hmip.0 | 23.10.2020   19:30 | info | (31432)   state change - setSecurityZonesActivationNone - id - value true
hmip.0 | 23.10.2020   19:30 | debug | (31432)   Read Home for SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
hmip.0 | 23.10.2020   19:30 | info | (31432)   state change - setSecurityZonesActivationExternal - id - value true
hmip.0 | 23.10.2020   19:30 | debug | (31432)   Read Home for SECURITY_JOURNAL_CHANGED:   {"pushEventType":"SECURITY_JOURNAL_CHANGED"}
hmip.0 | 23.10.2020   19:30 | info | (31432)   state change - setSecurityZonesActivationNone - id - value true

**Comment by aehs** [comment]
but securityAndAlarm.active is true as before

**Comment by Apollon77** [comment]
Please set loglevel to "silly" and provide same log :-) thank you

**Comment by aehs** [comment]
Hey Ingo,
loglevel is set to silly. Logfile attached.

KR
André

[HMIPsilly.txt](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/5433547/HMIPsilly.txt)

**Comment by Apollon77** [comment]
When you check the logs then exactly these data are shown as reported by HMIP ... they always are true.

So first of all: when you schange status via app ... is this displayed correctly in adapter? If yes maybe it is because of the "set" function do not work ... or is the app showing status correctly after changing by adapter?

**Comment by aehs** [comment]
When I change the status via app, it is not correctly displaying in adapter. It is always true.
On the other hand does the app sowing status correctly after changing it in adapter.

**Comment by saschaabraham** [comment]
If you are looking for the information, if the alarm settings are active you have to check the active status of the group INTERNAL and EXTERNAL, they represent in combination the three alarm states. INTERNAL and EXTERNAL actives means Away, only EXTERNAL active means only Perimeter active.

Falls es um die Information geht, welcher Alarmmodus aktiv ist, dann muss man den Status der Gruppen INTERNAL und EXTERNAL prüfen. Diese bilden Hüllschutz und Vollschutz ab.

**Comment by Apollon77** [comment]
Ok, then please do loglevel "silly" and then change in app and then show leg ... there should be a json triggered and then we see whats in there. And then please turn off again ad also show log ...maybe we just use the wrong file?

**Comment by saschaabraham** [comment]
By the way, the state "functionalHomes.securityAndAlarm.active" indicates only, that this part of the system is available.
For example, i have no devices regarding weather and climate, so the state ".functionalHomes.weatherAndEnvironment.active" is set to false. 

Maybe only a missunderstandig of the meaning of these states and this issue is solved...

Nebenbei, der State "functionalHomes.securityAndAlarm.active" zeigt nur, dass es diesen Teil im System gibt. Ich habe bei mir keine Geräte, die mit Wetter oder Klima zu tun haben, daher ist ".functionalHomes.weatherAndEnvironment.active" bei mir auf false. Heute habe ich mir eine Schaltmesssteckdose zugelegt, seit dem ist "functionalHomes.lightAndShadow.active" auf true.

Vermutlich liegt hier nur ein Missverständiss vor.

**Comment by aehs** [comment]
> By the way, the state "functionalHomes.securityAndAlarm.active" indicates only, that this part of the system is available.
> For example, i have no devices regarding weather and climate, so the state ".functionalHomes.weatherAndEnvironment.active" is set to false.
> 
> Maybe only a missunderstandig of the meaning of these states and this issue is solved...
> 
> Nebenbei, der State "functionalHomes.securityAndAlarm.active" zeigt nur, dass es diesen Teil im System gibt. Ich habe bei mir keine Geräte, die mit Wetter oder Klima zu tun haben, daher ist ".functionalHomes.weatherAndEnvironment.active" bei mir auf false. Heute habe ich mir eine Schaltmesssteckdose zugelegt, seit dem ist "functionalHomes.lightAndShadow.active" auf true.
> 
> Vermutlich liegt hier nur ein Missverständiss vor.

Hey, that sounds logical to me. All I wanted is to just get the state of the alarm system. Is it active or not. I assumed that it is set in the property "functionalHomes.securityAndAlarm.active". I absolutely agree with you about the misunderstanding. Thank you for the information.

**Comment by aehs** [comment]
**### If you are looking for the information, if the alarm settings are active you have to check the active status of the group INTERNAL and EXTERNAL, they represent in combination the three alarm states. INTERNAL and EXTERNAL actives means Away, only EXTERNAL active means only Perimeter active.**

**Comment by Apollon77** [comment]
thank you! I added it to the readme!
