### ISSUE TITLE
Security alarm state does not change to false

### ISSUE THREAD

**Issue by Hesse-Bub** [iobroker-community-adapters/ioBroker.hmip#191]
By turning off the alarm, which is working great, the alarm status (hmip.0.homes.xxxxxx.functionalHomes.securityAndAlarm.active) should switch to false, but it stays always true.

Or am I wrong and there is another datapoint for the status, which i did not find yet?

Thanky for the support and the great adapter :)

**Comment by Hesse-Bub** [comment]
was my fault , i found the info ...

**Comment by redPanther** [comment]
@Hesse-Bub I also search for that data point, which info you found?
