### ISSUE TITLE
Temperatur wird manchmal nicht gesetzt

### ISSUE THREAD

**Issue by RK62** [iobroker-community-adapters/ioBroker.hmip#194]
Manchmal blieb morgens die Heizung kalt. Ich habe dann Schedules in javascript aufgesetzt, die jeweils alle 15 Minuten die Temperatur von 2 Ventilen über den State .setPointTemperature ändern. 
Über den ganzen Tag läuft das dann auch einwandfrei und jede Veränderung wird im Log bestätigt:
```
hmip.0	2020-11-20 16:31:10.068	info	(4856) state change - setPointTemperature - id 8e77cc2e-896a-40a8-a84a-b0daca357210 - value 11
hmip.0	2020-11-20 16:31:05.100	info	(4856) state change - setPointTemperature - id dd93601b-134b-4836-8010-e23d525de3e1 - value 11
```
Irgendwann wird dann aber auch mal eine Einstellung "übersehen", es erfolgt keine Bestätigung es wird nichts von hmip.0 geloggt. Der State hat den gesetzten Wert bekommen, in der HMIP-App stehen aber noch die alten Werte. Die Ventile stehen immer alle im MANUELL-Modus weil ich die Heizung exklusiv über ioBroker via javascript steuere. Ich kann die Aussetzer bisher an nichts fest machen, bei anderen Adaptern tritt das Verhalten auch nicht auf.

Gerne melden wenn weitere Informationen benötigt werden.

- Adapterversion hmip V1.3.1
- Adapterversion javascript V4.8.4
- Node.js v12.19.0 
- NPM 6.14.8
- redis 6.0.6

Danke, Ralf

**Comment by Apollon77** [comment]
Du meinst also das da obige "state changed" Logging fehlt? Das wird gemacht wenn ein neuer Wert reinkommt im hmip Adapter! Wenn das also nicht kommt dann kam kein Wert rein. Sicher das das Skript den Wert setzt mit ack=false?

**Comment by RK62** [comment]
Genau, das Logging fehlt obwohl der State verändert wurde.
Ich setzte alle 15 Minuten mit diesem Befehl die Temperatur:
`setState(vRegler +'.setPointTemperature', Number(vTemp));`
Funktioniert dann auch stundenlang einwandfrei und dann einmal zwischendurch nicht.
Habe den Adapter schon auf 'debug' stehen, da erfolgt aber kein Log-Eintrag.
Komisch dass es dann auch gleich bei 2 Ventilen nicht funktioniert.

Macht es Sinn, dass ich mal einen eigenen Trigger auf den .setpoint State setze?
Dann könnte man zumindest ausschließen, dass der Änderung nicht an den Adapter weitergereicht wird.

**Comment by Apollon77** [comment]
Also ja, am besten mach mal ein kleines JS mit nem subscribe auf den State. Weil an dem Punkt im code passiert nicht viel bevor es geloggt wird.

Zweite Frage: Ehrlich keine Ahnung, da ich selbst hmip nicht habe, da es aber ja tut bei dir und auch loggt sollte es ja sein.

**Comment by RK62** [comment]
So, ich habe es ausprobiert: 
Eigener Trigger auf den State wirft die Meldung im Log zuverlässig aus.
hmip.0 reagiert aber nicht immer:

```
2020-11-22 06:01:00.026  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterHeizung: SETPOINT3: GZ|10|09|35000
2020-11-22 06:01:35.033  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterEventList: [Eventlist debug] hmip.0.groups.2 = 9
<<< Keine Reaktion hmip.0 >>>
...
2020-11-22 08:21:54.327  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterHeizung: SETPOINT3: GZ|11|09|20000
2020-11-22 08:22:14.332  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterEventList: [Eventlist debug] hmip.0.groups.2 = 9
2020-11-22 08:22:14.362  - info: hmip.0 (5635) state change - setPointTemperature - id 8e77cc2e-896a-40a8-a84a-b0daca357210 - value 9
...
2020-11-22 16:35:08.032  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterHeizung: SETPOINT3: GZ|11|09|25000
2020-11-22 16:35:33.037  - info: javascript.0 (1379) script.js.prod_Adapter.AdapterEventList: [Eventlist debug] hmip.0.groups.2 = 9
2020-11-22 16:35:33.053  - info: hmip.0 (5635) state change - setPointTemperature - id 8e77cc2e-896a-40a8-a84a-b0daca357210 - value 9
```

Mit Log-Stufe DEBUG wurde keine Meldung ausgegeben. 
Macht es ggf. Sinn dass ich mit SILLY logge?
Oder gibt es da gar keine Meldungen vor der Verarbeitung des States?

**Comment by Apollon77** [comment]
Das ist sehr komisch. Aber ja ein Silly Log wäre gut weil man dann auch mehr sieht was im Adapter direkt passiert. Log wird aber um einiges länger :-) Und bitte dann sehr großzügig posten wenn es um den Fehlerfall geht

**Comment by RK62** [comment]
Hat sich erledigt, der Adapter funktioniert einwandfrei. 
Ich habe die Thermostate alle 30 Minuten angesteuert und einen Wert von 1800 in der history bei "trotzdem gleiche Werte aufzeichnen" gesetzt. Dadurch haben beide zum gleichen Zeitpunkt reagiert. Die History "trotzdem gleiche Werte aufzeichnen" (sql.0) ist aber etwas langsamer als das Loggen der Wertänderung(javascript.0), dadurch stand in der DB der alte Wert als letzter Eintrag.

![photo_2020-11-27_12-54-20](https://user-images.githubusercontent.com/39200469/101247714-5a167d00-371b-11eb-8454-7c9ee22df081.jpg)

Mit einem Wert von 1860 bei bei "trotzdem gleiche Werte aufzeichnen" funktioniert es, jetzt schreibt History nur Einträge wenn sich wirklich nichts ändert.

Gruß, Ralf

**Comment by Patt2k** [comment]
Auch wenn das jetzt einwenig älter ist, aber ich habe genau das selbe Problem seit längerer Zeit. 
Wie RK62 steht bei mir auf Manuel und die kommplette Steuerung kommt aus Javascript.
 
Gibt es da schon eine lösung ?

MfG

**Comment by Apollon77** [comment]
Ist die Frage in einem seit 5.12.2020 geschlossenen Issue wirklich ernst gemeint?

Bitte Logfile prüfen. Falls da nichts drin ist was hilft (zb meldung das Wert zu oft geändert wurde oder sowas) dann bitte neues Issue mit Debug Log öffnen
