### ISSUE TITLE
Boost-Funktion nicht möglich

### ISSUE THREAD

**Issue by Kusi-Schweiz** [iobroker-community-adapters/ioBroker.hmip#196]
Gerne würde ich die Boost-Funktion per ioBroker starten. Leider finden sich dafür keine Objekte in den Heizkörperthermostaten. Lässt sich dies ändern? Vielen Dank im Voraus für die tolle Arbeit.

**Comment by Kusi-Schweiz** [comment]
Edit: Das Objekt für sie Boost-Funktion befindet sich nicht beim Heizthermostat unter "Devices", sondern unter "Groups". Damit funktioniert es einwandfrei.

**Comment by Apollon77** [comment]
also kann ich schliessen? ;-)
