### ISSUE TITLE
HMIP-BROLL missing channels

### ISSUE THREAD

**Issue by ReneSchlagehan** [iobroker-community-adapters/ioBroker.hmip#197]
Vielleicht kann jemand helfen. Ich versuche die Rolläden mit Yahka zu steuern. Target position und current position kann ich aus "shutterLevel" berechnen. Was mit fehlt ist etwas um den current state abzubilden. Ich sehe auch nur 2 channel. Ich glaube aber hier gibt es noch mehrere virtuelle channels die nicht sichtbar sind. Kommt man an die ran? Jemand eine Idee?

<img width="1568" alt="Bildschirmfoto 2020-12-05 um 14 17 39" src="https://user-images.githubusercontent.com/6965456/101244169-1b75c800-3705-11eb-9423-cd7c6f12a177.png">

edit: Wahrscheinlich gibt das die API tatsächlich nicht her und es ist nicht möglich "Wird geöffnet" oder "Wird geschlossen" abzubilden.

Gruß
René

**Comment by Apollon77** [comment]
Bitte Adapter auf Debug stellen, dann am besten einmal was tun das neue Werte reinkommen und davon das Log (nicht aus Admin, Logfile auf der Platte) hier posten, dann schauen wir mal was ggf noch an Daten da ist

**Comment by Apollon77** [comment]
Unter https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/device.py#L1195-L1215 kann man bissl sehen was die Python Dev bei deren Lb so an States haben... irgendwas hilfreich?

**Comment by ReneSchlagehan** [comment]
Ich muss denke ich eher bei SHUTTER_CHANNEL schauen und da gibt es leider nur "processing". In der Homematic IP App wird der current state wenn sich der Rolladen bewegt auch nicht angezeigt, von daher denke ich, das gibts einfach nicht...

**Comment by Apollon77** [comment]
mach doch mal Debug log ... dann sehen wir es

**Comment by Apollon77** [comment]
python hat https://github.com/coreGreenberet/homematicip-rest-api/blob/master/homematicip/device.py#L1153-L1170
Und unser Adapter hat https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/4b12a0e64b2ed3d326b9d7a5710caadde89efd1d/main.js#L1811-L1823

Falls dir also hier objekte Fehlern bitte mal bei den Objekten das "Gerät" löschen und Adapterneu starten, dann sollte es ggf neu angelegt werden

**Comment by nicojako** [comment]
Hallo habe das selbe Problem im neuen VIS Jarvis wird der punkt 3.level angesprochen und dieser existiert leider nicht.

Wenn ich irgendetwas falsch geschrieben habe oder unverständlich bitte melden bin neu in dem Thema :D

**Comment by Apollon77** [comment]
Habt Ihr mal das device mit den objekten gelöscht und dann neu gestartet? Dann sollte neu angelegt werden
. bzw ... ".level"?? gibts nicht ... dann ist das ein Bug in der vis das es das schreiben will?

**Comment by ReneSchlagehan** [comment]
Neu anlegen bringt nichts, da kommt nichts neues. "shutterLevel" gibts und der verändert sich entsprechend und daraus kann man letztlich auch mit scripten rausfinden ob sich der Rolladen hoch oder runter bewegt um in HomeKit "wird geöffnet" oder "schließen" status anzeigen zu lassen.

**Comment by nicojako** [comment]
habe es auch neu geladen und komplett neu gepaired leider kein erfolg

**Comment by Apollon77** [comment]
Ja ok, aber was ist jetzt die Anfrage? Sollen neue States hinzugefügt werden die magisch aus werten gebildet/errechnet werden? Das wäre an sich etwas für den Javascript adapter und eigene States dazu ...
