### ISSUE TITLE
By creating the Token i get the following error: RequestError: Error: connect ECONNREFUSED 81.14.202.219:6969

### ISSUE THREAD

**Issue by ErwinEberl** [iobroker-community-adapters/ioBroker.hmip#199]
**Describe the bug**  

I installed iobroker and  the hmip.0 with the Version 1.5. I changed the PW on my Homematic IP Accesspoint and tried to connect it. I get always the same error. (see in the headline).

I dried to install several different version from the adapter, 1.0.1, 1,2, .. . 
I also switched my fritzbox and opened all boards. But i get still the same error.

Platform

Accesspoint:  HmIP-HAP,
Firmware 2.2.18

linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
600 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
3.74 GB
System Betriebszeit
00:45:07
Node.js
v12.20.0
NPM
6.14.8
Festplatte Größe
28.94 GB
Festplatte frei
18.08 GB
Anzahl der Adapter
320

**Comment by Apollon77** [comment]
irgewndwie scheint wohl etwas Verbindungen zu verhindern. vllt haben die nen Schutz? Geht der normale HMIP Access point und die App noch?

**Comment by Apollon77** [comment]
ggf Adapter mal paar Stunden oder Tag ausschalten

**Comment by ErwinEberl** [comment]
Die App und der Accesspoint funktionieren. Ich konnte heute sogar mein altes Handy mit dem Accesspoint korrekt verbinden. PW ändern zurücksetzen usw.
Langsam gehen mir die Ideen aus.

**Comment by Apollon77** [comment]
Ich würde ggf mal rebooten und dns cache resetten ode rso ... somst hab ich auch keine ideew arum der gegenserver die verbindung ablehnt

**Comment by ErwinEberl** [comment]
Auch nach Löschen vom Adapter und neu starten vom IOBroker und Homematic IP Accesspoint mit untersschiedlichen Versionen kann ich keine Verbindung aufbauen. Ich gab über die Fritzbox die aut. Portweitergabe für den Accesspoint und Rasperry frei. Ich kann das PW auf dem Accesspoint ändern löschen neu vergeben  und auch nach dem Neustart baut er keine Verbindung auf.

**Comment by Apollon77** [comment]
automatische portfreigabe sollte an sich nicht gebraucht werden ... für keinen (und ist echt gefährlich!). Rest muss ich sagen das ich grad nicht weiss was los ist ... 

ok versuchen wir es "low levelig".

bitte auf die konsole gehen und

cd /opt/iobroker/node_modules/iobroekr.hmip/api
node test_getAuthToken.js ACCESSPOINTGTIN PIN

Bitte die werte der letzten zwei Dinge ersetzen. Ausgabe mit per email an iobroker@fischer-ka.de unter angabe dieses Issues und nummer

**Comment by ErwinEberl** [comment]
cd /opt/iobroker/node_modules/iobroker.hmip/api
node test_getAuthToken.js ACCESSPOINTGTIN [PIN]   führte ich aus. Jedoch bricht nach dem  Starten das Script bereits ab.

**Comment by Apollon77** [comment]
Process wise what I see is that it seems that HMIP APi is returning  81.14.202.219:6969
 as the REST API for your account, but your host can not connectthere because the server refuses the correction ... honestly I have no idea what I could do here. It seems also that you are the only one affected :-( can you do antelnet to the IP and this port?

**Comment by ErwinEberl** [comment]
telnet> open 81.14.202.219:6969
telnet: could not resolve 81.14.202.219:6969/telnet: Name or service not known
telnet> 
the ip is really not existing. If i check in the internet the ip adress is used by htp GmbH. I don't know, where i get this ip.

**Comment by Apollon77** [comment]
please check telnet usage! i think it is not working with the port that way

**Comment by apollo40** [comment]
Ich habe genau das selbe Problem.

16948) error requesting token: error hmip.0 | 2020-12-15 16:26:38.804 | warn | 

(16948) Request error: RequestError: Error: connect ECONNREFUSED 81.14.202.228:6969
hmip.0 | 2020-12-15 16:26:38.753 | info

**Comment by Apollon77** [comment]
Gleiche Frage: Geht eine telnet verbindung?

**Comment by Apollon77** [comment]
schaut mal hier ... https://homematic-forum.de/forum/viewtopic.php?t=63228 
ALso irgendwleche komichen VPNs im EInsatz oder sowas?

**Comment by apollo40** [comment]
Problem gelöst, es liegt leider daran das Homatic IP IP-Adressen sperrt.
Da ich eine statische ipv4 habe, wurde bei denen einfach meine IP gesperrt.
Wobei ich gar nicht so viele Anfragen gesendet habe, nur halt alle Thermostate aus wenn keiner daheim, und runter regulieren wenn ein Fenster geöffnet wird. Scheinbar aber doch zuviele für Homatic.

In diesem Fall einfach den Kundensupport von Homematic quälen. Hat jetzt 3 Tage gedauert jetzt funktioniert es wieder.

Sollte jemand keine fixe IP haben, was wohl bei den meisten der Fall ist, hilft unter umständen auch ein Modem Neustart da ihr dann meistens eine andere IP von eurem Provider bekommt.

Aber das hier gesperrt wird finde ich zum einen eine Sauerei zum anderen muss man das erst mal finden. War ein Zufallstreffer bei mir. Deswegen auch hier nochmal für alle die ähnliche Probleme haben festgehalten.

**Comment by ErwinEberl** [comment]
Vielen Dank für den Tip,  das Homeatic die IP-Adressen sperren kann.  Als Tip kann ich empfehlen den iobroker über das Handy zu verbinden und anschließend über die Weboberfläche auf dem Handy den Token für iobrokcer zu  erstellen.
