### ISSUE TITLE
Make serial call, instead of parallel

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.hmip#20]
These lines:
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L377
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L383
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L369
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L361
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/master/main.js#L132

MUST be serial call, because with too many parallel requests some of them will be lost.

**Comment by jogibear9988** [comment]
yes but I wanted to know, why it is needed to make it serial? is there a bug in node? in iobroker? I don't get it why a call should be lost

**Comment by GermanBluefox** [comment]
https://github.com/brillout/promise-serial

https://decembersoft.com/posts/promises-in-serial-with-array-reduce/

**Comment by jogibear9988** [comment]
I could also remove the promises completely and call the sync varaints. 
I wanted to know (kapiern auf deutsch mein ich eher) why it should not work with the parallel calls? What is the issue about the lost calls?

**Comment by jogibear9988** [comment]
Note that Promise.all() doesn't trigger the promises to start their work, creating the promise itself does.

**Comment by jogibear9988** [comment]
Es aber nicht normal wenn man 500 requests parallel sendet und auf 1gb rechner wird 1000% irgendwas knapp

**Comment by jogibear9988** [comment]
daher ich hab den code angepasst, im moment nur noch für 1 device/group/home parallel, d.h. max 10-20 calls
