### ISSUE TITLE
Unable to start the adapter

### ISSUE THREAD

**Issue by nils-hde** [iobroker-community-adapters/ioBroker.hmip#204]
Since updating to 1.5.0, I'm unable to start the adapter. Log repeatedly outputs this:

`
hmip.0 | 2020-12-20 12:43:24.712 | error | (546) Try reconnect in 30s
-- | -- | -- | --
hmip.0 | 2020-12-20 12:43:24.710 | error | (546) error starting homematic: TypeError: Cannot read property 'home' of undefined
hmip.0 | 2020-12-20 12:43:24.707 | warn | (546) Request error: RequestError: Error: connect ECONNREFUSED 81.14.202.218:6969
...
hmip.0 | 2020-12-20 12:39:52.732 | info | (546) starting. Version 1.5.0 in /opt/iobroker/node_modules/iobroker.hmip, node: v12.18.0, js-controller: 3.1.6
-- | -- | -- | --
`

Before it would occasionally crash when using together with the HomeKit adapters, but now it won't even start anymore.

Does anyone else observe a similar behavior? Using latest stable NPM and IOBroker versions.

**Comment by Apollon77** [comment]
First of all: Please turn on debug so that I can find the code place,

The ECONNREFUSED comes from a block of eq.3 ... they block if too many requets were done. Contact their support please

**Comment by Apollon77** [comment]
duplicate #206
