### ISSUE TITLE
Websocket Update necessary?

### ISSUE THREAD

**Issue by steckenpferd** [iobroker-community-adapters/ioBroker.hmip#205]
As eq3 is starting to block high frequency calls on their Cloud and it seems that ioBroker users are more affected than e.g. Home Assistant users. Does the adapter needs an update to not get blocked?

See also feedbacks in the Forum and this note:
https://alerts.home-assistant.io/?fbclid=IwAR0bRFLXT4mX3e1-AQFgoQidJaSX8HCBoCnIOhoLlGs1mcnZOVf-DhnOgl8#homematicip_cloud.markdown

**Comment by Apollon77** [comment]
Wihtout knowing exactly the reasons of "too much traffic" where we can try to reduct it  No update makes sense
I already try to contact EQ-3

**Comment by Apollon77** [comment]
For transparence: The adapter loads data at start and on certein events that come in, else we just receive data. And if a user controls a value then - for sure - we do calls for that action, but thats all. SO no idea whats wrong there
