### ISSUE TITLE
IP blocked because of to many requests to Homematic Server

### ISSUE THREAD

**Issue by lichtraum** [iobroker-community-adapters/ioBroker.hmip#206]
The Homematic IP server blocks IPs due to frequent requests. After that you can no longer use any Homematic IP instance. It should be possible to define an adjustable frequency for how often the adapter sends requests to the Homematic server.  Perhaps the adapter can then be used again.

**Comment by Apollon77** [comment]
I currently try to get a contact to EQ-3 to get infos on allowed frequencies ... unless that it is just "do not send too much"

**Comment by ToTXR4Y** [comment]
Well, i see a lot of traffic in my pihole for my Homematic IP Instance with Access Point:
query[AAAA] srv18.homematic.com

This is done every second. If i stop the adapter, the requests are stopping. That is maybe why HMIP Servers will drop down the packages.

**Comment by Lucifor1976** [comment]
I want to help to solve this Problem. My Installation of this Adapter does no Traffic to the Servers in Idle. Please leave Logfiles of this Traffic and this Adapter to see whats happend.
Change Adapter Logstate to warn, restart Adapter, goto Logs see logs until "Ban" und post the Logs here.
BTW Im sorry for my Bad English!

**Comment by Apollon77** [comment]
@ToTXR4Y Please set adapter to loglevel "debug" and then check whats logged. all communication (incoming or outgoing) is logged as debug ... so what is it that happens "every second" in your system? In mine also nothing really is send out if I not do anything

**Comment by Apollon77** [comment]
BTW: Loglevel to debug: Instances - Expert mode - column loglevel

**Comment by steckenpferd** [comment]
@Apollon77 have you talked with eQ3? What is the status between ioBroker and eQ3?

**Comment by Apollon77** [comment]
No answer so far from eq-3 ... I still hope I get an answer

**Comment by apex1834** [comment]
Im blocked now for an month. Apparrently you have to reset your full HMIP installation in order to regain access to the App from your local IP - or switch your IP if this is possible for you.

**Comment by Apollon77** [comment]
Other users were succesfully in contacting the eq-3 support to get unblocked again

**Comment by Lucifor1976** [comment]
Ich gebe hier auch mal meinen Senf dazu :)

Ich habe bis gestern die Version 1.5.2 vom 15.12.20 genutzt, bis Dato nie einen IPBan abbekommen, gestern Adapter Update und nach 30 Minuten wurde ich geblockt.

Nur zur Information.

**Comment by Apollon77** [comment]
keine Änderung seitdem sollte den traffic erhöhen

**Comment by Apollon77** [comment]
Ok, ich bin aktuell in Kontakt zu eq-3. mal schauen was rauskommt.

Ich habe auch im Adapter nochmals gecheckt und am Ende kann es nur sein das Nutzer-Skripte zu oft Werte setzen.

Ich habe daher in der 1.8.0 (noch nur GitHub) mal ein paar Sicherungen eingebaut. Bitte testen!
--> https://forum.iobroker.net/topic/42249/test-adapter-hmip-1-8-0

**Comment by Hesse-Bub** [comment]
Ich nutze den Adapter nur, um die Informationen von HMIP zu lesen und dann für Routine im Iobroker zu verwenden.
Ich setze aber keinerlei Werte bei HMIP.

Trotzdem habe ich alle paar Wochen aktuell das "Problem", dass die Anfragen geblockt werden

**Comment by Apollon77** [comment]
Nein ich glaube du hast ein anderes problem. eq3 arbeitet Serverbasiert. heisst ein account ist einem server zugeordnet. Accounts werden aber ggf mal verschoben und sowas. und das hat der adapter bisher nur über einen restart mitbekommen. bzw seot 1.9.0 erkennt er das und reagiert entsprechend selbst. Bitte aktuelle latest version nutzen

**Comment by Hesse-Bub** [comment]
Alles klar, danke :)
Update läuft, ich werde es weiter beobachten. 

Vielen Dank schonmal :)

**Comment by 1rfsNet** [comment]
Ich habs auch grad wieder. Ich lese lediglich die Türkontakte und Temperatur der HMIP Komponenten aus. Steuern tu ich gar nicht über ioBroker:

info | (903) ws connection opened
warn | (903) ws connection closed - code: 1000 - reason:

info.connection sagt übrigens true, was aber definitiv nicht stimmt. Der AP leuchtet gelb und auch die reguläre App lässt sich nicht verbinden.
Nutze v.1.9.0

**Comment by Apollon77** [comment]
Bitte mehr log zeigen. Nur das die Verbindung mal weg ist kann passieren - vor allem wenn auch die App nicht geht!! Die bisherigen ip Block Fälle hatten nur ioBroker betroffen und nicht die App. Ggf ist’s was ganz anderes

**Comment by 1rfsNet** [comment]
> Bitte mehr log zeigen. Nur das die Verbindung mal weg ist kann passieren - vor allem wenn auch die App nicht geht!! Die bisherigen ip Block Fälle hatten nur ioBroker betroffen und nicht die App. Ggf ist’s was ganz anderes

Ich hab leider nicht wirklich mehr. Um 12:43 gings damit los:

2021-03-03 12:43:42.454 - warn: hmip.0 (903) ws connection closed - code: 1006 - reason:
--
2021-03-03 12:43:52.515 - warn: hmip.0 (903) ws connection error: Error: connect ECONNREFUSED 81.14.202.211:8888

und dann kommen nur noch die o.g. Logeinträge. ca. 3200 Mal, bis ich um ca. 22 Uhr die Verbindung in der Fritz!Box neu gestartet habe und eine neue IP bekommen habe. Dann ging es sofort wieder. Der AP leuchtet die Zeit dann auch gelb, also keine Internet-Verbindung. 
Ich habe das Problem in letzter Zeit öfter mal. Ich habe jetzt mal den HMIP Adapter deaktiviert und beobachte das mal die nächsten Tage, ob das Problem weiterhin auftritt. Wenn die IP-Adresse blockiert wird, betrifft das doch den AP und nicht nur ioBroker oder?
Aber der info.connection Datenpunkt müsste doch eigentlich auf false gehen, wenn die Connection Refused wird oder nicht?

**Comment by Apollon77** [comment]
wichtig ... neueste Version 1.9.0 nutzen!!!

**Comment by Apollon77** [comment]
sonst mehr logs schauen (übrogens gibt auch ein logfile auf disk) sonst mal mit debug laufen lassen und debug Log posten

**Comment by 1rfsNet** [comment]
Okay, sorry. Das Problem tritt weiterhin auf. Sehr merkwürdig, dann werde ich mal bei EQ3 anfragen, was das ist. Bleibt nur das mit dem Datenpunkt. Soll ich dafür ein neues Issue aufmachen oder soll das so sein? 1.9.0 ist im Einsatz!

**Comment by Apollon77** [comment]
Gern neues Issue, aber bitte nur mit Debug log ...

**Comment by Apollon77** [comment]
SInce the new debouncing and request limitations no issue appeared again

**Comment by davidgiga1993** [comment]
Hi @Apollon77,
hast Du irgendwas mit dem EQ Support rausbekommen? Ich verwende ein eigenen Connector mit openHAB und wurde jetzt geblockt (ging ~3 Monate mit 1 req/Minute ohne Probleme).

**Comment by Apollon77** [comment]
Nur das Sie Ihre Systeme schützen müssen .. von daher ... einfach nicht regelmässig machen und akzeptieren das die API dafür nicht da ist.

**Comment by Apollon77** [comment]
> Was heißt das konkret?
Wir kennen keine exakten Angaben. Die Frage ist wozu du überhaupt so regelmässige anfragen brauchst?Kommen die Werte nicht per WbSocket verbindung als Push info?

**Comment by Apollon77** [comment]
Hm ... ohne das Werte gesetzt werden macht der Adapter nichts als Updates zu empfangen ... Also von daher verstehe ich nicht wie das passieren kann. AM besten mal das Loglevel der instanz auf "debug" setzen ... dann kann man genau nachvollziehen was passiert.
