### ISSUE TITLE
HmIP-DRBLI4 neues Device

### ISSUE THREAD

**Issue by stefantaust** [iobroker-community-adapters/ioBroker.hmip#213]
Der Aktor wird erkannt aber es fehlen viele Kanäle zum Schalten und Status Abfragen.

[https://www.homematic-ip.com/produkte/detail/homematic-ip-jalousieaktor-fuer-hutschienenmontage-4-fach-homematic-ip.html](url)

![rollo](https://user-images.githubusercontent.com/58149673/105904542-8b2b7380-6021-11eb-8ea5-51ddd673b4f5.PNG)

Wie kann ich behilflich sein, damit der Aktor noch richtig implementiert wird.

**Comment by Apollon77** [comment]
Abfrage/Lesen geht über 1.7.0
Für Steuerung muss jemand die API calls rausbekommen, hat noch keiner

**Comment by Apollon77** [comment]
bzw einige States könnten steuerbar sein mit 1.7.09 ... versuch mal

**Comment by stefantaust** [comment]
> bzw einige States könnten steuerbar sein mit 1.7.09 ... versuch mal

Wo finde ich die 1.7.09 ?

**Comment by Apollon77** [comment]
typo :-)) 1.7.0
auf GitHub  oder ab morgen im Latest Repo

**Comment by stefantaust** [comment]
![image](https://user-images.githubusercontent.com/58149673/105978156-82bf5100-6092-11eb-9fd9-560c6e6a35ec.jpeg)

Schaut gut aus. Danke
