### ISSUE TITLE
[Request] datapoint to get info about blocked connection

### ISSUE THREAD

**Issue by Hesse-Bub** [iobroker-community-adapters/ioBroker.hmip#222]
Hi,
first of all thanks for the great adapter.

As ist comes more and more, that connection are blocked on EQ3-side, would it be possible to get an datapoint which gives information about this?

f.e. in the log we can the following entries:

`

hmip.0 | 2021-02-17 13:13:16.869 | warn | (856) ws connection closed - code: 1006 - reason:
-- | -- | -- | --
hmip.0 | 2021-02-17 13:13:16.868 | warn | (856) ws connection error: Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:8888

`
But it would be really easy to creates scripts to get a note about this, if we would have a datapoint like "connection blocked" which changes to true.

The other possibility would be to change the datapoint "hmip.0.info.connection" to false.
But this seems only to be happen at adapter start.

Thank you in advance

**Comment by Apollon77** [comment]
The newest versions should detect that and reconnect which results in a "hmip.0.info-connection" getting false.
Also latest versions added some limitation that should prevent users from sending too many requests to hmip ... hwich most likely is the reason for these blocks!
