### ISSUE TITLE
info.connection not working

### ISSUE THREAD

**Issue by 1rfsNet** [iobroker-community-adapters/ioBroker.hmip#223]
I have a lot of errors from the hmip adapter in my log:

ws connection closed - code: 1006 - reason:
ws connection error: Error: connect ECONNREFUSED 81.14.202.226:8888

That's no big deal, but I just wanted to add a script so as soon as the connection drops, I will force my FritzBox to reconnect the internet connection for a new ip.

As far as I understand the info.connection data point should show the current connection status. But it always shows "true" for me, even I get these connection errors in log.

I am using Version 1.6.0.

Please let me know if you need any further info.

**Comment by Apollon77** [comment]
update to most recent version. fixed there

**Comment by 1rfsNet** [comment]
Don't have the issue with the IP bans anymore (using 1.9.0) but another kind of problem with the connection to HMIP. The AP light is blue (no flashing) but I am unable to connect with any client (hmip adapter, app, alexa, etc.). The app just shows "Access Point nicht verbunden". I'm not sure what the problem is, sometimes it only takes a few minutes, sometimes hours.

My problem: the datapoint still shows true, even the connection is not working. Is it possible to detect this? The app also shows it.

**Comment by Apollon77** [comment]
Please first open a new issue and attach debug log when that cae happens so that we can see whats up
