### ISSUE TITLE
Question: Why is the State for some Windows orange/yellow?

### ISSUE THREAD

**Issue by MrDrache333** [iobroker-community-adapters/ioBroker.hmip#231]
![2021-03-09 15 23 41](https://user-images.githubusercontent.com/22854641/110485089-94f9c980-80eb-11eb-88de-763b5e39a1ca.jpg)

I found nothing in the issues or in the FAQ 🤔

**Comment by Apollon77** [comment]
Please mouseover the orange state and make a screenshot of that ... or provide a debug log

**Comment by Apollon77** [comment]
No answer
