### ISSUE TITLE
No modes/boost for HMIP-eTRV-2

### ISSUE THREAD

**Issue by deus82ex** [iobroker-community-adapters/ioBroker.hmip#235]
My objects of type HMIP-eTRV-2 do not any propertys to set mode (auto/manuell) or boost.
Are theese missing in the adapter, and if so, can you add them?

**Comment by Apollon77** [comment]
Please provide a debug log

**Comment by deus82ex** [comment]
I hope this helps.

[hmip.log](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/6197625/hmip.log)
[hmip](https://user-images.githubusercontent.com/45871700/112319799-b394be80-8cae-11eb-90a2-42b80b505da0.png)

**Comment by Apollon77** [comment]
Please check the connect groups where the thermostat is in ... bost seems to be set there
