### ISSUE TITLE
Warning since i updated the js-controller adapter

### ISSUE THREAD

**Issue by KayThe95** [iobroker-community-adapters/ioBroker.hmip#239]
What can i do?
![image](https://user-images.githubusercontent.com/59337787/116780441-1f700100-aa7d-11eb-9e82-ada40543b5c8.png)

Thanks for your help (;

Kay

**Comment by Apollon77** [comment]
Is it only that one? Or more?

**Comment by JackDaniel007** [comment]
mehrere bei mir

hmip.0 | 2021-05-02 15:13:47.325 | info | (297716) State value to set for "hmip.0.groups.f7e45786-094f-4f1a-a081-27efd68ea0aa.humidityLimitEnabled" has to be type "number" but received type "boolean"

hmip.0 | 2021-05-02 15:13:47.325 | info | (297716) State value to set for "hmip.0.groups.f7e45786-094f-4f1a-a081-27efd68ea0aa.partyMode" has to be type "string" but received type "boolean"

hmip.0 | 2021-05-02 15:13:47.324 | info | (297716) State value to set for "hmip.0.groups.f7e45786-094f-4f1a-a081-27efd68ea0aa.cooling" has to be type "string" but received type "boolean"

hmip.0 | 2021-05-02 15:13:47.322 | info | (297716) State value to set for "hmip.0.devices.3014F711A0000A9BE99AC353.channels.0.lowBat" has to be type "string" but received type "boolean"

hmip.0 | 2021-05-02 15:13:17.901 | info | (297716) State value to set for "hmip.0.devices.3014F711A0000AD8A993E660.channels.0.lowBat" has to be type "string" but received type "boolean"

**Comment by KayThe95** [comment]
Same as @JackDaniel007

**Comment by Apollon77** [comment]
Please try out GitHub version. After update please manually restart adapter if it did not restarted itself on update. Errors gone?

**Comment by KayThe95** [comment]
How can i install the github version?

**Comment by Apollon77** [comment]
Use Admin and there the cutton withthe GitHub icon (cat) and select the adapter

**Comment by Apollon77** [comment]
will be release in 1.11.1 soon
