### ISSUE TITLE
Greenberet REST-API Update 0.10.4 geupdatet

### ISSUE THREAD

**Issue by steckenpferd** [iobroker-community-adapters/ioBroker.hmip#24]
Hallo Jochen,

Greenberet hat seine API auf 0.10.4 geupdatet - brauchst du die Update Informationen oder bist du Dank der jsons Logs der Community unabhängig davon?
https://github.com/coreGreenberet/homematicip-rest-api/blob/master/CHANGELOG.md

Hier eine Übersicht aller HmIP Geräte und was bereits Dank deinem Adapter funktioniert:
https://dl.dropboxusercontent.com/s/nma2rtpafgngy2e/REST-API.vs.ioBroker.HmIP.xlsx

Hier noch eine Doku die ich zu älteren API Version 0.9.8 gefunden habe  - nur als Info falls sich hier noch wichtige Informationen befinden.

Eine Frage - wenn du neue Geräte hinzufügst updatest du die Readme auf der Startseite oder muss ich da noch was machen?
https://www.pydoc.io/pypi/homematicip-0.9.8/autoapi/device/index.html

**Comment by jogibear9988** [comment]
Achtung, ich habe nun umgebaut das ich nicht mehr auf den Device Type, sondern auf den FunctionalChannelType schaue.

Daher kann ich nicht mehr sagen welche Hardware geht und welche nicht.

Da verschiedene Hardware gleiche Functional Channels haben kann.

Mit dem umbau kann es natürlich zu neuen Bugs kommen, bitte testen!

**Comment by jogibear9988** [comment]
Gibt es 80 versch. HomaticIP Devices????

**Comment by steckenpferd** [comment]
So ist es aber die gängsten sind schon drin

**Comment by jogibear9988** [comment]
ja, kann jetzt aber sein das viel mehr unterstützt wird, da die kanäle immer gleich sind

**Comment by steckenpferd** [comment]
Ich denke auch - vor allem die Internationalen Versionen (UK, IT usw.) gehen wahrscheinlich damit auch schon.

**Comment by jogibear9988** [comment]
des wegen, ich denke ich mache die liste iwann dann wieder raus... ziel sollte ja eh sein das irgendwann alle hw geht

**Comment by steckenpferd** [comment]
?

**Comment by jogibear9988** [comment]
denke nicht das schon alle channels übernommen sind

**Comment by steckenpferd** [comment]
Danke :-)

**Comment by jogibear9988** [comment]
diese Kanäle fehlen noch:

	CLIMATE_SENSOR_CHANNEL
	DEVICE_INCORRECT_POSITIONED
	DEVICE_PERMANENT_FULL_RX
	DEVICE_SABOTAGE
	DEVICE_OPERATIONLOCK
	DEHUMIDIFIER_DEMAND_CHANNEL
	HEAT_DEMAND_CHANNEL
	FLOOR_TERMINAL_BLOCK_CHANNEL
	FLOOR_TERMINAL_BLOCK_LOCAL_PUMP_CHANNEL
	DEVICE_GLOBAL_PUMP_CONTROL
	PASSAGE_DETECTOR_CHANNEL
	PRESENCE_DETECTION_CHANNEL

sind aber im json abzug von @coregreenberet vorhanden, d.h. man könnte die states auf jeden fall implementieren.
vlt. kann ja jemand helfen.

**Comment by steckenpferd** [comment]
Nur als Info 0.10.5 ist erschienen 
https://github.com/coreGreenberet/homematicip-rest-api
