### ISSUE TITLE
warnung im log unter admin 5

### ISSUE THREAD

**Issue by JackDaniel007** [iobroker-community-adapters/ioBroker.hmip#246]
adapter version 1.12.0

Object of state "hmip.0.devices.3014F711A0001898A993E0E4.channels.0.temperatureOutOfRange" is missing the required property "common.type"

**Comment by Apollon77** [comment]
Thank you for reporting, fixed in 1.12.1

**Comment by JackDaniel007** [comment]
State value to set for "hmip.0.homes.36b98aae-4468-434a-aaa9-f47787c3f1be.functionalHomes.securityAndAlarm.alarmEventTimestamp" has to be type "string" but received type "number"
