### ISSUE TITLE
set windowState possible?

### ISSUE THREAD

**Issue by w00dst0ck** [iobroker-community-adapters/ioBroker.hmip#249]
Im using the HmIP accesspoint with HmIP thermostat and some ZigBee window sensors from other brand.

 Currently the state windowState is not writeable.

```xml
{
  "type": "state",
  "common": {
    "name": "windowState",
    "type": "string",
    "role": "value",
    "read": true,
    "write": false
  },
  "native": {},
  "_id": "hmip.0.groups.79f07b65-9047-4a79-b437-xxxxxxxxxxx.windowState",
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": xxxx
}
```
Is it possible to make it writeable? Or is this limited by the API?

**Comment by Apollon77** [comment]
In fact the main issue is that you can not create HMIP devices without the device, so you have no sensor to write. ANd yes the HMIP system is API wise bould to that system, so no write possible
