### ISSUE TITLE
Status aus der Cloud wird nicht aktualisiert.

### ISSUE THREAD

**Issue by mdn-united** [iobroker-community-adapters/ioBroker.hmip#25]
### Erst mal: VIELEN DANK an den Entwickler! Das ist der Adapter, auf den ich gewartet hatte!
Aufmerksam geworden bin ich über Technikkram.net, aber die Installation habe ich gemacht, wie auf Github beschrieben. Version 0.0.4 war das. Das hat auch super funktioniert! Meine Aktoren und Sensore wurden auch alle erkannt. (Sind nur ein paar. Heizungsthermostate, Unterputzschalter, Schaltsteckdosen und ein zweifach Schalter.)

**Ein Sache sind mir aufgefallen:**
Nach einiger Zeit werden die neusten Daten nicht mehr von der Cloud abgerufen und es stehen alte Werte im ioBroker.
Wie habe ich das gemerkt? Es ist alles eingerichtet und dann schaltet man eine Lampe an, über die HMIP App oder Alexa. Der neue Zustand ist ioBroker aber nicht zu sehen. Wenn ich dann den Adapter neu starte, werden die aktuellen Werte eingelesen. Aber wenn ich einfach nichts mache, dann bleiben die alte Werte im ioBroker.

**Comment by jogibear9988** [comment]
Kann ich im Moment nicht nachvollziehen.

Hab aber auch nur rudimentäres error handling drin.

Hast du denn im logfile einen error vorher vom adapter?

**Comment by Ma-ster77** [comment]
Habe gestern direkt nach dem Release die Version 0.0.5 installiert und unter Objekte nachgesehen ob der Status geändert wird. Habe zwar keine Schalter aber die Tür und Fensterkontakte ändern in den Objekten sofort den Status wenn die Tür auf bzw zu geht.

**Comment by Ma-ster77** [comment]
So, heute kam ich dazu mehr zu testen. Muss mdn-united zustimmen. Meine erste Aussage war ein wenig voreilig. Gestern war das bei mir anscheinend Vorführeffekt. Heute sind die Tür und Fensterkontakte zwar einmal von Close kurz auf Open gesprungen aber danach direkt auf false. Und wenn man wie schon erwähnt den Adapter neu startet, geht es genau einmal bis es nicht mehr funktioniert.

**Comment by jogibear9988** [comment]
Habt ihr denn dann fehler im Log? schick mir mal bitte das logfile

**Comment by Ma-ster77** [comment]
Im Log steht nichts drin. Ich mache meine Schiebetür auf State geht kurz auf Open und dann direkt auf False. Ich mache die Türe wieder zu, der State geht kurz auf Close und dann direkt auf False.

**Comment by jogibear9988** [comment]
schick mir mal das logfile dazu

**Comment by jogibear9988** [comment]
@Ma-ster77 hast den fehler noch? logfile dazu?

**Comment by Ma-ster77** [comment]
Heute komme ich nicht zum testen. Morgen habe ich wieder Zeit dafür. Melde mich dann umgehend.

**Comment by mdn-united** [comment]
Ich habe seit dem Update auf 0.0.8 keine Probleme mehr. Vielleicht war es auch schon in 0.0.7 gelöst, aber ich kam nicht zum Testen mit der Version.
