### ISSUE TITLE
Fehlermeldungen nach update auf JS controller 3.3.15

### ISSUE THREAD

**Issue by Homeworker11** [iobroker-community-adapters/ioBroker.hmip#269]
**Describe the bug**  
Fehlermeldungen nach update auf JS controller 3.3.15

(1784) State value to set for "hmip.0.groups.9c1c0af2-8ceb-486f-8b2d-597763ebdda0.sabotage" has to be type "string" but received type "boolean"

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/74406135/128536930-654b344c-8c65-4e61-933d-61617afc1ceb.png)

**Versions:**  
 - Adapter version: <1.13.0>
 - JS-Controller version: <3.3.15>
 - Node version: <v12.21.0 >
 - Operating system: <Linux>

**Comment by Apollon77** [comment]
1.13.1 comes to npm in some minutes, fixed there
