### ISSUE TITLE
HmIP RC8 remote Control

### ISSUE THREAD

**Issue by mariofuhr** [iobroker-community-adapters/ioBroker.hmip#277]
Is it possible to query the long and short press status of the remote control?

**Comment by Apollon77** [comment]
Nope, see https://github.com/iobroker-community-adapters/ioBroker.hmip#important-info-what-can-be-done-with-this-adapter ... Die werden nicht gemeldet

**Comment by mariofuhr** [comment]
Okay verstehe Danke.
