### ISSUE TITLE
ASIR-O Alarmsirene Outdoor

### ISSUE THREAD

**Issue by florian84z** [iobroker-community-adapters/ioBroker.hmip#287]
Hi,

ich bekomme mit der o.g. Alarmsirene keine ausführbaren Datenpunkte. Iobroker & Adapter sind neu aufgesetzt.

Habe ich irgendwo einen (Denk-) Fehler?

vg

Florian

![image](https://user-images.githubusercontent.com/23108104/133451501-4d0e5fb5-d7a5-40ff-a047-7bc52d0ee29e.png)

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by Apollon77** [comment]
Ich würde erwarten das der "on" state funktioniert ... versuch mal "true" oder "false" zu setzen

**Comment by florian84z** [comment]
Bei beiden Werten tut sich nichts. Schau mal bitte diesen Post an, dort hat ein User, allerdings mit CCU3 deutlich mehr DP zur Auswahl.

https://www.facebook.com/groups/440499112958264/posts/1580191535655677

Wie können wir in dem AP diese DP auch bekommen?

**Comment by florian84z** [comment]
![Screenshot_20210917-083727_Homematic IP](https://user-images.githubusercontent.com/23108104/133736217-003ad2d2-f5a1-482c-97f5-a4b17a5de887.jpg)
![Screenshot_20210917-083747_Homematic IP](https://user-images.githubusercontent.com/23108104/133736220-921488cc-a5f4-4b40-aa1f-9a48baee7b70.jpg)

Das wäre die Konfig aus der HM App (Android)

**Comment by Apollon77** [comment]
Naja dann muss "jemand" der diese Geräte hat in der App mit sniffen was genau passiert wenn man hier was ändert weil das kann der adapter nicht selbst machen. Da ich solche Geräte nicht habe müstest DU das ggf tun. Kann versuchen dich anzuleiten und dann kann ich schauen was so geht

**Comment by florian84z** [comment]
> Naja dann muss "jemand" der diese Geräte hat in der App mit sniffen was genau passiert wenn man hier was ändert weil das kann der adapter nicht selbst machen. Da ich solche Geräte nicht habe müstest DU das ggf tun. Kann versuchen dich anzuleiten und dann kann ich schauen was so geht

klaro, können das auch gerne per Teamviewer machen, bzw du kannst dich austoben! ;) Rest per PN?

**Comment by florian84z** [comment]
> Naja dann muss "jemand" der diese Geräte hat in der App mit sniffen was genau passiert wenn man hier was ändert weil das kann der adapter nicht selbst machen. Da ich solche Geräte nicht habe müstest DU das ggf tun. Kann versuchen dich anzuleiten und dann kann ich schauen was so geht

Hast du heute abend zufällig Zeit?

**Comment by Apollon77** [comment]
Ich kläre es Dir gern hier :-)

https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/

Installieren und SSL Proxying einschalten. Dann das SSL Root Zert auf dem Handy installieren.

Dann auf dem Handy Proxy bei der WLAN Verbindung aktivieren und die IP des PCs und port 8888 angeben. Dann sollte alles was auf dem handy per HTTP kommuniziert sichtbar sein. Bei HTTPS Verbindungen darf im Proxy nicht nur "CONNECT" stehen sondern GET/POST was immer und man muss sehen was an Daten Kommt.

Dann jetzt die HMIP App bei aktiviertem Proxy starten und jetzt die relevanten Seiten aufrufen und ggf schalten bzw. Daten setzen und bitte aufschreiben am besten mit uhrzeit wann was war damit ich es nachvollziegen kann. ggf mit immer 1-30s Pausen. Dann die Session als chls File und mir an iobroker@fischer-ka.de senden unter referenz auf dieses Issue mit Link und den Zeitinfos. Dann schaue ich mal

**Comment by florian84z** [comment]
Super - bekomme ich hin. Nur wo bekomme ich das SSL Zertifikat für meinen Droiden?

**Comment by Apollon77** [comment]
liess mal die verlinkte Seite Abschnitt "Android"

**Comment by florian84z** [comment]
> liess mal die verlinkte Seite Abschnitt "Android"

email ist raus!

**Comment by RP70DP** [comment]
Das Gerät wird schon seit Ende 2019 von Greenberets REST-API unterstütz. Vermutlich ist da einfach nicht mehr Funktionalität über die API.

**Comment by Apollon77** [comment]
An sich ist die HMIP Adapter Funktionalität mit Greenberets REST-API gut abgeglichen und kann faktisch das gleiche ... dann wäre hier ggf wirklich irgendwas nicht möglich. Aber ich checke gern nochmal

**Comment by Apollon77** [comment]
Ok, auch bei Greenberet ist nicht mehr drin und alle Infos kennen nichts zur Steuerung. Aber ja man müsste es daher mitschneiden ...
