### ISSUE TITLE
HMIPw-FAL230-C6 - unknown FLOOR_TERMINAL_BLOCK_CHANNEL, HEAT_DEMAND_CHANNEL, DEHUMIDIFIER_DEMAND_CHANNEL, CHANGE_OVER_CHANNEL

### ISSUE THREAD

**Issue by cc3neo** [iobroker-community-adapters/ioBroker.hmip#297]
Hallo,

herzlichen Dank für den super Adapter.

Ich habe einen **wired** HMIP Fußbodenheizungsaktor 6-fach (HMIPw-FAL230-C6). Dieser wirft mir im Log "unknown Channel Type" aus.
Gerne würde ich den Status der Stellantriebe mitschreiben, den ich aber in den Objekten/Datenpunkten nicht finden kann. 

Vgl. https://www.eq-3.de/Downloads/eq3/download%20bereich/hm_web_ui_doku/HmIP_Device_Documentation.pdf 
Kapitel 52, Seite 4024 

Das Device habe ich im Adapter bereits gelöscht und neu laden lassen, ohne Erfolg.

Anbei Teile vom Logfile. DeviceID, HomeID und GroupIDs habe ich mit * pseudonymisiert.
[ioBroker HMIPw-FAL230-C6.txt](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/7338138/ioBroker.HMIPw-FAL230-C6.txt)

Könnte sich das bitte mal jemand ansehen und ggf. einfplegen?

Danke vorab!

**Comment by Apollon77** [comment]
Ja, deaktivieren der Statistik liefert auch das.

frage zu deinem Datenfile: Du hast nur einen heizkreislauf aktiviert?
Es ist win "Heizkreislauf 2" in den Daten aber das Objekt hat keine eigenen Datenpunkte auser eine Gruppen ID ... WIe sieht die Konfig denn aus? Bin noch am verstehen  was da für Daten sein sollten (oder auch nicht). Das PDF gibt da Semantisch nicht so viel her

**Comment by cc3neo** [comment]
Hallo,
ich habe 5 Kreisläufe aktiv (1,2,4,5,6). Wenn ich das richtig verstanden habe, kann der Aktor nur mit entsprechenden Wandthermostaten in einer Direktverknüpfung arbeiten. Deshalb befindet sich jeder Kreislauf in einer Gruppe mit einem solchen HmIPW-WTH. Kreisläufe 2 & 4 sind in meiner Konfig in einer gemeinsamen Gruppe mit einem Thermostat. Kreislauf 3 ist nicht in Verwendung.

Nun habe ich gerade mal eine Statusänderung (Ventil auf) mittels hoher Soll-Raumtemperatur provoziert. Der Aktor schaltet dann und das Ventil geht auf. Im Log kommen dazu aber keinerlei Einträge an (Silly-Mode). Die Einträge im Log aus dem ersten Beitrag tauchen nur auf, wenn der HMIP-Adapter startet.

Mehr kann ich aktuell nicht beitragen.

**Comment by Apollon77** [comment]
Hast Du mal das Log davon? von dem Zeitraum wo er schaltet? Mit Zeitangabe? Dann kann ich mal chauen was so ankommt

**Comment by cc3neo** [comment]
Anbei mal ein verbose Log.
19:26 Temperatur auf 23.5 gestellt, Raum "Schlafen", Heizkreislauf 5 (Ventil war da vermtl. schon offen)
19:30 Temperatur auf 20 gestellt.
19:32-35: Heizkreislauf 5 geht aus. Ebenso Kreislauf 4 aus. Kreislauf 2 geht an. Hier war ich leider mit den Zeiten etwas nachlässig im notieren.

[ioBroker HMIPw-FAL230-C6 silly-log.txt](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/7515393/ioBroker.HMIPw-FAL230-C6.silly-log.txt)

Falls Du es genauer brauchst, gerne noch mal melden, dann wiederhole ich es nochmal.

**Comment by Apollon77** [comment]
Ok,die relevanten Channel liefern einfach keine Daten, ich werde die einfach ignorieren. Ich kann leider keinen ventilstand liefern - sind in den Daten nicht drin. Zeigt die App den Status an?

**Comment by RP70DP** [comment]
Beim FAL-MOT-C12 werden keinerlei Daten angezeigt, das wird vermutlich bei allen ähnlichen Aktoren gleich sein.
