### ISSUE TITLE
Log message on setPointtemp change

### ISSUE THREAD

**Issue by Voodoo2man** [iobroker-community-adapters/ioBroker.hmip#304]
Hi,

If I enter a new value (e.g. 18) for setPointTemp for my homematic ip valve I get the following in the log:

state change - setPointTemperature - id 6398df5e-ee5f-4385-9521-c1b10eb27aea - value rounded to 18 (step=0.5 )

I wouldn‘t expect a log entry about a value change.
There is no need for any message in the log in this case. I just changed a value of my valve.
Its ok to get a message if the value has been set to another value as entered because of rounding. But a log entry for normal value setting, its not needed.
 A new entry for every value change is a bit too much for Info setting.

ioBroker in latest on raspi 4b
Hmip Adapter 1.13.2 (log setting: info)
Js controller: 
Node.js: 12.22.7

**Comment by Apollon77** [comment]
next version will have lowered that to debug
