### ISSUE TITLE
actualTemperature

### ISSUE THREAD

**Issue by meerkat82** [iobroker-community-adapters/ioBroker.hmip#309]
Hi,
der Wert hmip.0.groups.*.actualTemperature wird nur mit dem Wert null angegeben. Die aktuelle Temperatur vom Thermostat wird nicht ausgegeben.
![image](https://user-images.githubusercontent.com/72659369/141362293-90969c56-164b-43d1-8b0e-614bc0a3749e.png)

**Comment by Apollon77** [comment]
Please enable debug log, then you can see which data are coming in ... when the data are not delivered the adapter can not have them

**Comment by RP70DP** [comment]
Funktioniert bei mir einwandfrei.
![hmip_aT](https://user-images.githubusercontent.com/62850183/142734666-5c0dc005-09d6-4458-ad62-e2d4d3546125.PNG)
