### ISSUE TITLE
HM-WGC

### ISSUE THREAD

**Issue by Flori-5** [iobroker-community-adapters/ioBroker.hmip#316]
Hey, I sniffed the API Call from the iOS App

Header:
POST /hmip/device/control/startImpulse HTTP/1.1
Host	srv29.homematic.com:6969
Content-Type	application/json
Connection	keep-alive
CLIENTAUTH    XXXXXXXX
AUTHTOKEN    XXXXXXXX
Accept	*/*
VERSION	12
Accept-Language	de-de
Content-Length	56
Accept-Encoding	gzip, deflate, br
User-Agent	Homematic%20IP/15 CFNetwork/1325.0.1 Darwin/21.1.0

Body:
{"deviceId":"3014F711A000XXXXXXXXXX","channelIndex":2}

Does this help to get the device "controllable" via the Adapter?``

_Originally posted by @Flori-5 in https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/253#issuecomment-988277991_

**Comment by Apollon77** [comment]
Cool, thank you, can you also tell me which "action" you triggered in the app that this command was sent out? 
And ideally also which states changed afterwards in the adapter

**Comment by Apollon77** [comment]
Are there also other options to control?

**Comment by Flori-5** [comment]
I tirggered this action in the app:
![image](https://user-images.githubusercontent.com/75010474/145265155-1e5d46a4-e82f-408c-9a4e-7b595d05418b.png)

After sending the action, this value is changing to "true" for about 0,5 secs, before switching back to "false" again.
![image](https://user-images.githubusercontent.com/75010474/145264916-51be4637-097c-4e72-8818-5f69f87d8917.png)

I dont think there isnt any other option for controls

**Comment by Apollon77** [comment]
Ok then I ould add a new state as button like "triggerImpulse" to trigger it ? What do you think?

**Comment by Flori-5** [comment]
that would be awesome! Thanks!

**Comment by MartinKuhl** [comment]
Hi together. @Apollon77 did you already managed to get HM-WGC working? If so do you are able to add the support for this device in the commun python lib https://github.com/coreGreenberet/homematicip-rest-api so that other projects can participate in your progress?

**Comment by Apollon77** [comment]
@MartinKuhl did not had time so far, but in next days. But sorry I have no experience in python ...

**Comment by MartinKuhl** [comment]
@MartinKuhl me too ...
If you need a person to test something, I would be glad to help you. My HM-WGC is installed and working via App but unfortunately not via home assistant.

**Comment by MartinKuhl** [comment]
@Flori-5 or @Apollon77 are you able to trigger the garage door opener via ioBroker and if so, which data points do you used for that. I tried to use processing and on but it looks like that both options are not working.

**Comment by MartinKuhl** [comment]
if I try your Rest-Call my Garage door is opening/closing too.

**Comment by Apollon77** [comment]
Ok guys, please give the GitHub version a try and report back. I added a "startImpulse" states which should trigger it.

After GitHub update please manually Restart the adapter!

**Comment by MartinKuhl** [comment]
hi @Apollon77 so in a way it is working. In my case the garage door is starting to open/close but after some seconds it is stopping to move and after some seconds it is starting again. It looks like there is an unwanted loop that the trigger to start is pushed several times or the trigger is pushed in a loop.

**Comment by Apollon77** [comment]
Ooohh... please try again the new GitHub version... better now?

**Comment by MartinKuhl** [comment]
@Apollon77 thanks for the update! Now it is working perfectly.
Are you able to update (via pull request of course) the underlying lib (https://github.com/coreGreenberet/homematicip-rest-api) so that other projects can benefit frim your work an also support the HM-WGC device?

**Comment by Apollon77** [comment]
The other Lib is written in Python and sorry but I have no experience in python development, so no I can not update that library. Sorry

**Comment by MartinKuhl** [comment]
But thanks for your hard work here for the ioBroker adapter

**Comment by Flori-5** [comment]
Working perfectly! Thanks for implementation @Apollon77
