### ISSUE TITLE
Get HmIP-DLP working

### ISSUE THREAD

**Issue by aehs** [iobroker-community-adapters/ioBroker.hmip#320]
Please support Hmip-DLP, 
Currently it is possible to see the channels, but there is no way to interact with the lock.

**Comment by aehs** [comment]
The states are there and shown correctly, but it is not possible to manage the lock over iobroker.
Please let me know if I can help with log files or some similar stuff.



![image](https://user-images.githubusercontent.com/19493653/147406721-037d47a4-4f3b-4a3c-983d-e1cff4cfbb75.png)

**Comment by Apollon77** [comment]
We need to find out what the command it which needs to be sent ... in fact you would need to sniff the network traffic from the HMIP app... if you would be up for it I could sent instructions

**Comment by aehs** [comment]
Hi Ingo,
sure I would do that!

Please send me the instructions and I will give my best.

KR
André


Ingo Fischer ***@***.***> schrieb am So., 26. Dez. 2021,
22:54:

**Comment by RP70DP** [comment]
See:
https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/287#issuecomment-922088763

**Comment by RP70DP** [comment]
@aehs 
Are you sure that the device called HmIP-DLP? Because the Door Lock Drive named HmIP-DLD. The HmIP-DLD isnt't supported by Greenberets REST-API, because unfortunately he's not working on the library anymore.

Here is a dump. Dont't know if this helps:
https://github.com/coreGreenberet/homematicip-rest-api/issues/406#issuecomment-821944357

**Comment by Apollon77** [comment]
Ok, please try GitHub version. I added a setLockState state and also one for the pin (if a pin iss et in the app). See info on Readme.

Please manually restart adapter after the GitHub install. Please Try and report back

**Comment by aehs** [comment]
Hey Ingo, wish You a happy New Year!!!

Thanks for a fast reaction and a first solution. Well, setLock=LOCKED works
pretty fine, other commands produce Error “warn              Request error:
StatusCodeError: 400 -
{"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641075251525} “.
When I unlock with app and do setLock=LOCKED with iobroker again, it works
without errors. UNLOCKED and OPEN don’t work. The pin is set correctly.



Regards

André






Mit besten Grüßen aus Ladbergen
André Ehsner

__________________________________________
André Ehsner
Gartenstr. 18
49549 Ladbergen
GSM: +49 160 4467881
E-Mail: ***@***.*** ***@***.***>

_________________________________________
Ferme les yeux et oublie-moi

Je te le dis, c'est mieux comme ça


Am Sa., 1. Jan. 2022 um 20:27 Uhr schrieb Ingo Fischer <
***@***.***>:

**Comment by Apollon77** [comment]
Hm ... ok, lease install from GitHub again. I dded a logline that also displays the PIN value.Can youplease check that ths is the correct entered value?

**Comment by aehs** [comment]
<html>
<body>


hmip.0 | 2022-01-01 23:42:16.441 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641077026426}
-- | -- | -- | --
hmip.0 | 2022-01-01 23:42:16.351 | info | Call setLockState for OPEN with PIN [object Object]


</body>
</html>


<html>
<body>


hmip.0 | Zeit | debug | Nachricht
-- | -- | -- | --
hmip.0 | 2022-01-01 23:43:14.713 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641077026426}
hmip.0 | 2022-01-01 23:43:14.626 | info | Call setLockState for UNLOCKED with PIN [object Object]


</body>
</html>

**Comment by Apollon77** [comment]
meehh ... ok ... netx try :-)

**Comment by aehs** [comment]
<html>
<body>


hmip.0 | 2022-01-02 00:02:00.569 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641078248555}
-- | -- | -- | --
hmip.0 | 2022-01-02 00:02:00.481 | info | Call setLockState for OPEN with PIN xxxx

the pin is correct!!


</body>
</html>

**Comment by Apollon77** [comment]
Aahhhhhhhh ... Please make sure "iobroker" connection/app/client (whats correct term=) is added to the list of access control clients in HmIP app settings!

**Comment by aehs** [comment]
Yes, it is!

Ingo Fischer ***@***.***> schrieb am So., 2. Jan. 2022, 00:08:

**Comment by aehs** [comment]
And the access is granted to the lock as well.

Andre Ehsner ***@***.***> schrieb am So., 2. Jan. 2022, 00:15:

**Comment by Apollon77** [comment]
But still this error? Hm .....

**Comment by aehs** [comment]
Unfortunately yes

Ingo Fischer ***@***.***> schrieb am So., 2. Jan. 2022, 08:46:

**Comment by Apollon77** [comment]
Ok, next try ... noestly ... last idea i have before we need to sniff the network traffic from the app because my info sourfces ended then

**Comment by aehs** [comment]
Hi Ingo, same thing....but different messages, may be it helps:
<html>
<body>



hmip.0 | 2022-01-02 18:21:51.686 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641144256344}
hmip.0 | 2022-01-02 18:21:51.600 | info | Call setLockState for OPEN with PIN xxxx
hmip.0 | 2022-01-02 18:21:15.358 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641144256344}
hmip.0 | 2022-01-02 18:21:15.267 | info | Call setLockState for UNLOCKED with PIN xxxx
hmip.0 | 2022-01-02 18:21:10.032 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:21:08.486 | info | setOperationLock - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:21:08.479 | info | Ignore invalid value for setLockState.
hmip.0 | 2022-01-02 18:21:08.478 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:21:08.268 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:21:06.728 | info | setOperationLock - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:21:06.650 | info | Ignore invalid value for setLockState.
hmip.0 | 2022-01-02 18:21:06.649 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:21:03.132 | info | setOperationLock - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:21:03.125 | info | Ignore invalid value for setLockState.
hmip.0 | 2022-01-02 18:21:03.122 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:21:00.941 | info | setOperationLock - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:21:00.927 | info | Ignore invalid value for setLockState.
hmip.0 | 2022-01-02 18:21:00.926 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:20:58.751 | info | setOperationLock - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:20:58.745 | info | setLockState - id "3014F711A0002A1D89AA1C63" - Too fast value changes, change blocked!
hmip.0 | 2022-01-02 18:20:58.743 | info | Value unchanged, do not send this value
hmip.0 | 2022-01-02 18:20:58.611 | info | Call setLockState for LOCKED with PIN xxxx
hmip.0 | 2022-01-02 18:20:44.423 | info | hmip adapter connected and ready


</body>
</html>

**Comment by Apollon77** [comment]
And you really installed a new from GitHub and restarted? ;.) 

Nd what you do there with setOperationLock state?

Because then I have mo more ideas

**Comment by Apollon77** [comment]
Please give latest GitHub version one last try

**Comment by aehs** [comment]
The latest from GitHub is installed.
<html>
<body>


hmip.0 | 2022-01-02 20:12:38.886 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641151248576}
-- | -- | -- | --
hmip.0 | 2022-01-02 20:12:38.801 | info | Call setLockState for OPEN with PIN xxxx
hmip.0 | 2022-01-02 20:12:16.589 | warn | Request error: StatusCodeError: 400 - {"errorCode":"INVALID_AUTHORIZATION_PIN","blockingTime":1641151248576}
hmip.0 | 2022-01-02 20:12:16.503 | info | Call setLockState for UNLOCKED with PIN xxxx
hmip.0 | 2022-01-02 20:11:54.833 | info | Call setLockState for LOCKED with PIN xxxx    ---  **aehs commented :WORKS!**
hmip.0 | 2022-01-02 20:11:01.439 | info | hmip adapter connected and ready
hmip.0 | 2022-01-02 20:11:00.595 | info | ws connection opened
hmip.0 | 2022-01-02 20:10:53.753 | info | starting. Version 1.14.0 in /opt/iobroker/node_modules/iobroker.hmip, node: v14.18.2, js-controller: 3.3.22


</body>
</html>

**Comment by Apollon77** [comment]
So then I have no idea ... please check again all settings in the app that could be relevant?

**Comment by Apollon77** [comment]
And just to be sure: The PIN is not your system PIN but the access control PIN associated with the door lock itself. If you didn't assign an individual door lock PIN, please remove it from the config completely.

**Comment by Apollon77** [comment]
And: Maybe you didn't give access to the homebridge-homematicip plugin for this particular lock? Check all settings on the settings page "Access" / "Access authorizations" (German: "Zutrittsberechtigungen").

**Comment by aehs** [comment]
Ingo, 
you won’t believe. It works! I was that stupid and irritated by the app, cause it asks me each time for the system Pin when I navigate to the lock. But it is only for the APP. In the Access authorizations I didn’t set the pin. So, if try to open/lock/unlock with iobroker with empty Pin it WORKS!!!!

Thank You very much for the great job!!!!



KR
André
