### ISSUE TITLE
interop hmip - heatingcontrol

### ISSUE THREAD

**Issue by rg-engineering** [iobroker-community-adapters/ioBroker.hmip#322]
In ticket https://github.com/rg-engineering/ioBroker.heatingcontrol/issues/271 a user reports an interop problem between heatingcontrol and hmip.
The user @MiRo1310 would like to manually set a target temperature on an HMIP thermostat via alexa. To do this, he writes the target value directly to a data point made available by the hmip adapter. If only the hmip adapter is running, this apparently works.
If the user now activates the heatingcontrol adapter, the new target value is correctly recognized and processed by the heatingcontrol. **But**: the hmip adapter doesn't send the new value to the thermostat anymore.
At first I was of the opinion that the handling of the ack flag would be a problem. The heatingcontrol adapter sets the ack flag when it has processed the data. If the hmip adapter now checks whether the ack flag is not set and only then continues processing, this could have been the cause. I have now installed a delay of 2 seconds in the heatingcontrol before setting the ack flag.
Unfortunately, that doesn't help.

So now the ticket here: What are the causes that the hmip does not transfer changes to a setpoint temperature of a thermostat?

In log we see sometimes "Value unchanged, do not send this value". In those cases it's clear, why value wasn't sent. But in most of the cases this log doesn't appear...

**Comment by Apollon77** [comment]
I need more and a real log for that. In fact hmip has implemented "rounding" to 0.5 (because hmip thermostats do not accept other values), value comparism to prevent sending same value again and also rate limits and such because required ...

Ideally set hmip to debug loglevel and get a log of relevant cases

**Comment by Apollon77** [comment]
PS: eq-3 is very strict on rate limits and such and if you want not to be blocked only relevant updates should be sent and not too many in short time. Thats wha we needed to implement this kind of limits. But all blocked requests because of rate limits or delays are logged, so log should always tell whats up ... if nothing is logged then the value should be sent to hmip

**Comment by jogibear9988** [comment]
I think if the ack flag is set, then the adapter does nothing. 
see https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/cae40ae4eeca9a1574adb3e1607215f6dd42f17f/main.js#L408

but if you are sure it is false you need to check the logs

**Comment by Apollon77** [comment]
Yes and this is 100% as ioBroker works ... so commands are always ack=false and the adapter will only react in this case (as all other adapters too)

**Comment by rg-engineering** [comment]
But here two adapters are in the game... Who should set the ack flag?

@MiRo1310 Kannst du bitte hmip auf debug stellen und das log wie letztens nochmal erstellen?

**Comment by MiRo1310** [comment]
@rg-engineering ja das kann ich machen, habe ich auch schon mit @Apollon77 besprochen. 
Danke

**Comment by Apollon77** [comment]
> But here two adapters are in the game... Who should set the ack flag?

In fact "at the end" hmip is the adapter that really is doing the action/sending command so, "who ever" controls this hmip state  needs to do this with ack=false (and this should be the case for all adapters that need to do an action!).

So if heatingcontrol is using e.g. a timer or whatever to change the set-temp on hmip then this always needs to be done with ack=false

**Comment by rg-engineering** [comment]
That's the way heatingcontrol works. In cases where heatingcontrol sets values of other adapters I always use ack=false.
But here we have a different scenario: here a third adapter (alexa) sets an value of hmip (also with ack=false). heatingcontrol  has subscribed that value too (initially to get the current setting or changes from hmip). 
In our case heatingcontrol wants to be informed about changes of set-temp. The source of change can be the thermostat itself or a third adapter.
That means we have now two senarious:

1) a value changed on thermostat directly. This change hmip receives and put it on a DP without ack. heatingcontrol takes that value, do something and set the ack. so far so good, becasue this is the standard case most of the users have configured.
2) alexa changes the value. Now we expect that hmip takes that change and send it to the hardware (thermostat) . At the same time heatingcontrol must take care about that change. How can heatingcontrol now identify that the sender was alexa and not hmip, because only in case the sender was hmip heatingcontrol should set the ack-flag... 

on the other side I'm still not sure the ack-flag is the real root cause. In latest heatingcontrol version I wait two seconds after internal processing before I set the ack flag. So hmip should have enough time to do it's work.

**Comment by MiRo1310** [comment]
@Apollon77 Anbei mein lo
![Screenshot (8)](https://user-images.githubusercontent.com/68854794/147815794-fd45e312-f310-4e0f-8b50-1919c86d998a.png)
g

**Comment by rg-engineering** [comment]
@MiRo1310 aber hier sehen wir doch wieder den Fall, dass sich der Wert nicht geändert hat: "value unchanged", d.h. der DP hat schon 21°C und es wird nochmal versucht, 21°C zu schreiben.

**Comment by MiRo1310** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/68854794/147816784-c70f5fe7-bf58-4b1e-b5ad-4d64005e1a79.png)
@rg-engineering 
@Apollon77 
nein der Datenpunkt hatte vorher 19
guck mal auf den Zeitstempel, ich denke der HMIP adapter hat garkeine Zeit zu reagieren, oder sehe ich das falsche?
Darf denn der Heatingcontroladapter überhaupt ack true setzen? oder würde das nicht der hmip adapter machen?

**Comment by MiRo1310** [comment]
![Screenshot (10)](https://user-images.githubusercontent.com/68854794/147817338-ad2dfdb7-c334-4c87-b3a2-7decd1bb2e59.png)
@rg-engineering 
@Apollon77 
Ich habe mal folgendes gemacht, heatingcontrol adapter aus. 
Es dauert 7 sek bis der HMIP ack true setzt,
ist denn da nicht schon unser Konflikt? Der HMIP hat garkeine Zeit um den Wert zu übermitteln?

**Comment by rg-engineering** [comment]
> Darf denn der Heatingcontroladapter überhaupt ack true setzen?

naja, wie ich oben schon geschrieben habe, auf dem gleichen DP kommen ja auch die Änderungen vom Thermostat zurück. Dann ist hmip der Sender und heatingcontrol der Empfänger. Im vorliegenden Fall gibt es zwei Empfänger (hmip und heatingcontrol). Deshalb hatte ich ja die zwei Sekunden delay eingebaut, bevor ich das ack setze, damit hmip Zeit hat, selbst zu reagieren...

**Comment by MiRo1310** [comment]
Natrürlich ist der Datenpunkt schon auf dem wert, denn ich gebe ja genau da den Wert ein. Dann verarbeitet heatingcontrol und merkt das der Datenpunkt schon auf dem Wert ist. Und Hmip sagt oh  der wert hat schon ack true, also habe ich nichts mehr zu tun.
So stelle ich mir das gerade vor.
Und was ist wenn du anstatt 2sek einfach mal 10 sek gibst bis ack true gesetzt wird?

**Comment by rg-engineering** [comment]
> Und was ist wenn du anstatt 2sek einfach mal 10 sek gibst bis ack true gesetzt wird?

habe eine Version (2.8.2) ohne ack setzen gebaut und in github hochgeladen...

**Comment by MiRo1310** [comment]
Ich habe gerade mal in der console über nano den wert in deinem code von 2000 auf 10000 gesetzt, jetzt funktioniert es

**Comment by MiRo1310** [comment]
Wäre das ein Problem das auf 10 sek zu setzen? 
Ich könnte auch evtl. noch mal 8 sek testen

**Comment by rg-engineering** [comment]
im github liegt jetzt eine Version mit 10Sekunden...

**Comment by MiRo1310** [comment]
Ich habe die Version installiert, und es scheint bisher gut zu funktionieren. 
Vielen Dank

**Comment by jogibear9988** [comment]
nö, hmip setzt ack erst wenn fertig an die cloud geschickt.
aber es soll eben kein anderer adapter mit den ack states rumspielen.

warum legt er für das heatingcontrol nicht eigene states an?

**Comment by Apollon77** [comment]
Ok, ich kapiers immer noch nicht, aber vllt ist es ein Problem das der hmip if falle von "value unchanged" garkein ack=true setzt??
Weil das passiert nur wenn ein Wert an die cloud gesendet wird und dann von der cloud ein event gemeldet wird mit "einem" neuen wert! Ein reines "wert an cloud senden" setzt keinen ack=true! Und so soll es auch sein.

Also ja was wir tun könnten wäre im Falle von "value unchanged" den aktuellen Wert nochmal als ack= true zu setzen, sodass es so aussieht also ob der Wert übertragen wurde (weil faktisch ists ja korrekt das der Wert immer noch so ist wie vorher auch wenn es nicht aus der Coud kam)

Also heatingcontroll darf bei hmip mit ack=true bitte nichts setzen ... aber selbst wenn würde der das für seine interne Arbeit ignorieren. Also wenn heatingcontrol nen Wert setzt mit ack=true dann denkt der User es ist pot was anderes gesetzt als es wirklich ist - das wäre blöd. Intern denkt hmip immer noch das der wert da ist den es selbst kennt.

Also könnte bitte mal jemand genau sagen was wann in welcher Reihenfolge passiert - falls nicht das obige Thema das issue ist?

**Comment by rg-engineering** [comment]
@Apollon77 meine Interpretion ist etwas anders: Das Problem ist nicht der Zeitpunkt, wann hmip das ack setzt, sondern wann auf ack==false geprüft wird.  
Nochmal was eigentlich passiert:
* ein dritter Adapter  (im vorliegenden Fall alexa) setzt einen Datenpunkt im hmip (hier das set-temp eines Thermostats)
* auf den gleiche Datenpunkt schaut heatingcontrol (per subscribed)
* heatingcontrol übernimmt diese Änderung für das dort interne Handling und wartet zunächst 2 Sekunden, bevor ack gesetzt wird
* parallel dazu soll hmip die Änderung an das Thermostat schicken
* wenn hmip ebenfalls sofort auf ack==false checked und ebenfalls das interne Handling startet, sollten beide Adapter parallel arbeiten können und am Ende beide ack = true setzen dürfen
Leider funktioniert genau das nicht... heatingcontrol muss ca 10 Sekunden warten, bevor es das ack setzt, damit hmip seine interne Arbeit wirklich beginnt. Aus meiner Sicht scheint es, dass hmip zunächst "irgendetwas" tut, bevor auf ack==false geprüft wird.
Ich würde mir wünschen, dass einfach beide Adapter parallel auf die Änderung des Datenpunktes reagieren und dann am Ende beide das ack setzen dürfen (klar, der erste gewinnt, das sollte aber kein Problem sein, solange beide Empfänger wirklich zu arbeiten beginnen)

und nochmal warum heatingcontrol überhaupt das ack setzt: der Standardfall ist, dass auf dem set-temp-Datenpunkt von hmip die geänderte Zieltemperatur vom Thermostat kommt, d.h. hmip selbst setzt diesen Datenpunkt. Da in dem Fall der heatingcontrol der Empfänger ist, sollte er ja auch das ack setzen...

**Comment by jogibear9988** [comment]
Ich sehe das anderst, warum muss direkt das hmIp signal an den heatingcontrol adapter? warum kann man dafür nicht ein eigenes anlegen, und wenn heating control fertig ist (ack true) steuert man damit das hm-ip signal.

keine speziallogik für irgendeinen adapter gehört hier rein.

**Comment by jogibear9988** [comment]
Was ich mir vorstellen kann:

https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/cae40ae4eeca9a1574adb3e1607215f6dd42f17f/main.js#L409

in der zeile übernehme ich den wert in den internen speicher wenn "ack=true" kommt, und wenn dann der vergleich intern bevor an hmip geschickt wird nicht mehr != ist wird nix geschickt.

Wenn aber nur hm-ip intern ack setzt ist das eben kein problem.

**Comment by jogibear9988** [comment]
Ich werd da eh nix umbauen, ich hab gar kein hm-ip mehr im Einsatz, daher kann ich nix testen...

**Comment by rg-engineering** [comment]
> warum muss direkt das hmIp signal an den heatingcontrol adapter?

weil das der Standardfall ist: der user dreht am Thermostat, diese Änderung kommt im hmip im entsprechenden Datenpunkt an und muss vom heatingcontrol weiter verarbeitet werden...

und jetzt kommen die user und überlegen, wie sie die Temperatur noch verstellen können. und da kommen dann plötzlich weitere Adapter in's Spiel, die von außen in das System eingreifen wollen und den Datenpunkt manipulieren...
Ich könnte natürlich im heatingcontrol einen Datenpunkt anbieten, der solche Änderungen "von dritten" annimmt und weitergibt. Dann braucht es dieses oben von mir gewünschte parallele Arbeiten von Adaptern nicht.

ich würde auch in keinen Adapter spezielle Logik für andere Adapter einbauen wollen

**Comment by Apollon77** [comment]
@rg-engineering hmip hat inzwischen einige logiken drin die je nach Datenpunkt entscheiden ob und wann ein Wert an die Cloud gesendet wird - und ja dadurch kann es zu einem Delay kommen. Wenn Wertr zu oft geändert werden zB wird mit einem debounce Mechanismus gewartet das der Wert stabil bleibt bevor er gesendet wird.

Und ja heatingcontrol DARF keinen ack=true wert in hmip-Namespace setzen. Das macht keinen Sinn (und ehrlich generell nicht auser bei javascript/0_userdata.0 wo es kein Adapter ist).

Wie @jogibear9988 geschrieben hat wird ein ack=true Wert als "aktueller Wert" betrachtet weil bisher nie jemand reingepfuscht hat. Damit gaukelt dein Adapter dem hmip vor das andere Werte aktuell sind als es wirklich sind. Damit geht dann alles kaputt. Ok ich kann das jetzt umbauen - dann würde "dein" ack=true ignoriert werden, was vllt schon die Lösung ist - aber eigentlich ist das "Problem" das heatingcontroll überhaupt ack=true Werte setzt in Adapter-Namespaces die "nicht sein eigener sind" - so wie ich es jetzt verstehe

**Comment by Apollon77** [comment]
Lets try it that way https://github.com/iobroker-community-adapters/ioBroker.hmip/commit/6c3fb9b5f3e144c842e04bed953520793432fdda But neds to bebtested!! i have no thermostats!

**Comment by Apollon77** [comment]
Ok, ignore the this.namespace+id ... will fix in foloow up commit

**Comment by rg-engineering** [comment]
> Und ja heatingcontrol DARF keinen ack=true wert in hmip-Namespace setzen. Das macht keinen Sinn (und ehrlich generell nicht auser bei javascript/0_userdata.0 wo es kein Adapter ist).


Dann habe ich das Konzept des ack - Flags bisher nicht richtig verstanden. Ich dachte, wenn ein Adapter einen Datenpunkt setzt und ein anderer diesen Datenpunkt auswertet, dann soll der zur Bestätigung das ack-Flag setzen. Wenn das von mir falsch interpretiert ist, dann ist die Lösung einfach: dann entferne ich einfach das ack-Setzen im heatingcontrol...

**Comment by Apollon77** [comment]
Neeeeiinn!!!

* ack= false wird (zu 99%) von "Adapter extern" gesetzt und bedeutet eine "Steueraktion an den Adapter". Also eine Aufforderung das der Adapter doch bitte diesen Wert umsetzen soll. Bei hmip heisst das das dieser an die HMIP Cloud geendet wird.
* ack=true wird AUSSCHLIESSLICH vom Adapter gesetzt und beinhaltet den finalen Wert den das Gerät gerade hat -  den kann ja nur der Adapter wissen der das gerät anbindet. Deswegen ist der Wert "bestätigt"

Jemand der den Wert liesst kann so anhand des ack Flags ermitteln ob der gelesene Wert ein Kommando war (ack=false) oder ob das der Wert ist den das Gerät selbst gemeldet hat.

Wenn bei der Gerätekommunikation was fehlgeschlagen ist dann kann es vorkommen das der letzte Wert ein kommandowert war. Wenn der aber nie bestätigt wurde mit "einem finalen Gerätewert" dann weiss amn formal den echten Wert gerade nicht -  daher mein Change den Wert wieder neu zus etzen wenn er unchanged bleibt. Das macht denke ich sinn.

Jetzt klarer?

Andere Adapter die Werte lesen die sind für den Adapter komplett irrelevant .. könnten ja 10 Adapter sein die mit nem Wert eines bewegungsmelders irgendwas anstellen ... Das braucht der Adater aber gar nicht zu wissen. :-)

Das ganze obige gilt für Adapter. States in 0_userdata.0 oder javascript.X oder so sind da schwieriger weil die meisten User die dort States anlegen as ack Konzept nicht kennen. Für die mag es sein das es sinn macht das ein Adapter (für den ein State gedacht ist) ein ack=true setzt wenn er alles bearbeitet hat - ist aber ein Sonderfall.
