### ISSUE TITLE
Fehler im LOG bei HMIP-BWTH

### ISSUE THREAD

**Issue by backons** [iobroker-community-adapters/ioBroker.hmip#33]
Hi...
I get this info in my LOG for every of my HMIP-BWTH. 
hmip.0 unkown channel type - INTERNAL_SWITCH_CHANNEL - {"id":"3014...","homeId":"782...","label":"Wandthermostat...","lastStatusUpdate":1548603922020,"type":"BRAND_WALL_MOUNTED_THERMOSTAT","functionalChannels":{"0":{"label":"","deviceId":"3014...","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_OPERATIONLOCK","groups" etc...

**Comment by jogibear9988** [comment]
fixed in git

**Comment by steckenpferd** [comment]
Macht ein Mini Versionssprung Sinn auf 0.0.8?

**Comment by jogibear9988** [comment]
wenn ich ein neues npm veröffentliche, dann erhöhe ich.
ich will aber erst antworten ob es geht, werde nicht jedes mal ein paket publishen

**Comment by steckenpferd** [comment]
Verstehe - war nur als Vorschlag da die meisten nicht verstehen das man auch updaten kann ohne Versionssprung. Eine neue Version einspielen kriegen sie hin. Aber das ist nur Erklärungssache zu Anfang und dann sollte es bei den meisten klappen.
