### ISSUE TITLE
Boolean data point of windowState for heating groups

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hmip#331]
Unfortunately the state "windowState" in heating groups is a string. Is it possible to add a corresponding boolean data point?

**Comment by Apollon77** [comment]
because of the fact that I do not have such a device I have no clue aboit fields and the real content. Please provide the details ... so which strings are in there? Then we can think about if a boolean is popssible

**Comment by RP70DP** [comment]
No problem, a room can have more than just one window. The heating group consists (among others) of all windows in one room. So, if all windows of that room are closed, the value of the state "windowState" is "CLOSED". If one window out of all windows of that room is open, the value of the state "windowState" is "OPEN". Accordingly to the state "windowOpen" (boolean) of a single shutter contact a separate value "windowOpen" for the heating group would be nice.

If "windowState" = "CLOSED" -> "windowOpen" = false
If "windowState" = "OPEN" -> "windowOpen" = true

**Comment by Apollon77** [comment]
is somethign like "TILTED also there as status?

**Comment by RP70DP** [comment]
I didn't quit get that...
![heating group object tree](https://user-images.githubusercontent.com/62850183/149090151-1828eb11-5f6a-4271-800a-3a1a1974ec96.JPG)

**Comment by Apollon77** [comment]
A WindowState sometimes also has "TITLED" (gekippt)

**Comment by RP70DP** [comment]
Ah, i understand! Don't known because i don't have any HmIP-SRH.

**Comment by RP70DP** [comment]
I could ask the community.

**Comment by RP70DP** [comment]
TILTED

See: 
https://forum.iobroker.net/topic/51327/hmip-srh-drehgriffsensor-am-hmip-adapter?_=1641974634975

**Comment by Apollon77** [comment]
Thank you ... so the boolean is then "not "CLOSED" as open? :-)

**Comment by RP70DP** [comment]
Yes.

**Comment by Apollon77** [comment]
Ok, because windowOpen was existing already I decided to add it the same. This means that only OPEN is Open ... Please try GitHub version
