### ISSUE TITLE
Verbindung zum Homematic IP Gateway, erstellt keinen Token || Connection to the Homematic IP Gateway, does not create a token

### ISSUE THREAD

**Issue by sysonic2** [iobroker-community-adapters/ioBroker.hmip#333]
Liebe IoBroker,
Ich bitte euch um euren Blick und Rat, ich erhalte keine Verbindung,
ich möchte gerne den Adapter "HomeMatic IP Cloud-Zugriffspunkt" mit meinem AccessPoint verbinden und einen Token erstellen, erhalte aber leider keine Verbindung.
(PIN ist korrekt und accessPointSgtin ist definitiv korrekt)
Hat Jemand eine Idee?
Vielen Dank!

Dear IoBroker,
I ask you for your look and advice, I get no connection,
I would like to connect the "HomeMatic IP Cloud Access Point" adapter to my AccessPoint and create a token, but unfortunately I don't get a connection.
(PIN is correct and accessPointSgtin is definitely correct)
Does somebody has any idea?
Thanks very much!
![2022-01-08 22_30_08-Update js-controller und node js](https://user-images.githubusercontent.com/97381978/149659939-4c435073-3ac4-49d7-b081-87e919dc7d4e.png)
![2022-01-08 22_31_27-intro - raspberrypi](https://user-images.githubusercontent.com/97381978/149659941-ca7d0710-0b67-44ac-9fa0-1efe2378f584.png)
![2022-01-08 22_32_05-instances - raspberrypi](https://user-images.githubusercontent.com/97381978/149659942-830c73da-0a44-4a69-b282-7232615fa08a.png)
![2022-01-08 22_32_59-logs - raspberrypi](https://user-images.githubusercontent.com/97381978/149659943-8485e1f4-db94-4ab7-abc5-aa841c11c617.png)

<html>
<body>
<table style="font-family: monospace; font-size: 14px;"><tbody><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:43.141 -<span> </span><span class="type" style="font-weight: bold;">info</span>: host.raspberrypi "system.adapter.hmip.0" enabled</td></tr><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:43.227 -<span> </span><span class="type" style="font-weight: bold;">info</span>: host.raspberrypi instance system.adapter.hmip.0 started with pid 11424</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.204 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: /opt/iobroker/node_modules/request-promise-core/configure/request2.js:13</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.205 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: if (!isObjectLike(options)) {</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.205 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: ^</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.205 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: TypeError: isObjectLike is not a function</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.205 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/request-promise-core/configure/request2.js:13:10)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.205 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.<anonymous><span> </span>(/opt/iobroker/node_modules/request-promise-native/lib/rp.js:15:1)</anonymous></td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.206 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.206 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.206 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.206 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.206 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.207 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.207 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.<anonymous><span> </span>(/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:5:12)</anonymous></td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.207 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.207 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi instance system.adapter.hmip.0 terminated with code 1 (JS_CONTROLLER_STOPPED)</td></tr><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:29:44.208 -<span> </span><span class="type" style="font-weight: bold;">info</span>: host.raspberrypi Restart adapter system.adapter.hmip.0 because enabled</td></tr><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:14.264 -<span> </span><span class="type" style="font-weight: bold;">info</span>: host.raspberrypi instance system.adapter.hmip.0 started with pid 11432</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.280 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: /opt/iobroker/node_modules/request-promise-core/configure/request2.js:13</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.280 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: if (!isObjectLike(options)) {</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.281 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: ^</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.281 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: TypeError: isObjectLike is not a function</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.281 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at module.exports (/opt/iobroker/node_modules/request-promise-core/configure/request2.js:13:10)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.282 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.<anonymous><span> </span>(/opt/iobroker/node_modules/request-promise-native/lib/rp.js:15:1)</anonymous></td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.282 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.282 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.282 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.283 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.283 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.283 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.284 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Object.<anonymous><span> </span>(/opt/iobroker/node_modules/iobroker.hmip/api/hm-cloud-api.js:5:12)</anonymous></td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.284 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)</td></tr><tr class="error" style="background: rgb(255, 106, 91); color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.284 -<span> </span><span class="type" style="font-weight: bold;">error</span>: host.raspberrypi instance system.adapter.hmip.0 terminated with code 1 (JS_CONTROLLER_STOPPED)</td></tr><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><td>2022-01-16 13:30:15.285 -<span> </span><span class="type" style="font-weight: bold;">info</span>: host.raspberrypi Restart adapter system.adapter.hmip.0 because enabled</td></tr><tr class="info" style="background: white; color: rgb(0, 0, 0); font-family: monospace; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
</body>
</html>

**Comment by Apollon77** [comment]
Please try to reonstall the adapter. Something is broken in one of the installed npm modules that should be there but is not

**Comment by sysonic2** [comment]
still the same Problem,

**Comment by Apollon77** [comment]
STrange. Ok mach mal folgendes ...
* Shekll öffnen
* `cd /opt/iobroker/node_modules/iobroker.hmip`
* `npm install --production`

Dann weg?

**Comment by Apollon77** [comment]
Falls ja ist immer noch pot für andere Adapter was komisch in deiner installatuon. Das hat aber nichts mit dem Adapter zu tun!! Falls du das Problem nochmal hast dann bitte im Forum nach support suchen bzw backup und neuinstallation machen

**Comment by sysonic2** [comment]
200x Danke!, ja das hat es auf Anhieb gelöst.
