### ISSUE TITLE
No "ON" on SINGLE_KEY_CHANNEL

### ISSUE THREAD

**Issue by SukramJ** [iobroker-community-adapters/ioBroker.hmip#34]
Hello,
i tried to use a HmIP-RC8 with iobroker and switch an osram lightify bulb on and of with the following script:

on({id: 'hmip.0.devices.3014Fxxxxxxxxx.channels.8.on'}, function (obj) {
   setState("lightify.0.7359xxxxxxx.on", true);
});
on({id: 'hmip.0.devices.3014Fxxxxxxxxx.channels.7.on'}, function (obj) {
   setState("lightify.0.7359xxxxxxx.on", false);
});

If i press a button on the RC all channels are lighted green on the objects-view but the value of the on attribute is never changed on a channel. As a result the bulb never switches on or off.

From my past experience with the python rest api there is no ON on the SINGLE_KEY_CHANNEL that identifies the triggerd button. 
So my question is: Did you test an RC with your code and found a way to identify the triggered button/channel? Is my code broken?

BR
Markus

**Comment by jogibear9988** [comment]
it's not possible.
we do not get the info from the cloud!
