### ISSUE TITLE
Hörmann Modul HmIP-MOD-HO not working anymore

### ISSUE THREAD

**Issue by dklinger** [iobroker-community-adapters/ioBroker.hmip#349]
Hello,
since one of the last updates, the HmIP-MOD-HO it not working as expected.
Prior to the update it was 0 for open, 1 for stop, 2 for close and 3 for ventilation_position (state: doorCommand).
Now, the definition of the state is the following, which leads to wrong positions of the door:
    "states": {
      "1": "OPEN",
      "2": "STOP",
      "3": "CLOSE",
      "4": "VENTILATION_POSITION"
}
Since the update I cannot open the door via the adapter. I guess, as 0 is not in the states definition anymore, the state is simply not accepting the value 0 and therefore not sending it to the device.

**Comment by dklinger** [comment]
Essentially, this commit broke the integration with HmIP-MOD-HO. Prior to that, you could define the int value to send to the device by yourself. Now, with lines 213-216 you are ignoring all values with are not 1-4.
I'm sure this commit has its reason, but for HmIP-MOD-HO it its breaking the integration.

**Comment by Apollon77** [comment]
Meehh ... did eq-3 really use different definitions for different devices ... meehhh

Cna you show me all objects ob that device type please and indeally a debug log

**Comment by Apollon77** [comment]
ANd BTW: WHich values is what for your device?

**Comment by dklinger** [comment]
Yeah, we "love" eq-3... :D

That's what I see in the objects tree:
![image](https://user-images.githubusercontent.com/2249766/152307718-e419d527-9df1-4746-956e-8950f8218ed0.png)

I set the values for it via script. So 1-3 are working and they are doing the right things.
Here's the debug log for 0, which is the "open" command for HMIP-MOD-HO:

hmip.0 | 2022-02-03 09:44:19.063 | info | Ignore invalid value for doorCommand.
hmip.0 | 2022-02-03 09:44:19.063 | debug | state change - sendDoorCommand - id "xyz" - value 0

The values for my device are:
Open = 0
Stop = 1
Close = 2
Ventilation Position = 3

So they are your current values - 1.

**Comment by Apollon77** [comment]
Please try GitHub version

**Comment by dklinger** [comment]
Works like a charm again. Thanks!
