### ISSUE TITLE
HMIP-eTRV-2 - partymode and boostmode is missing

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.hmip#37]
Servus!
Vielleicht ist es ja möglich, den PartyMode und den BoostMode bei dem HMIP-eTRV-2 mit rein zu nehmen?

`2019-02-07 22:07:04.691 - silly: hmip.0 _updateGroupStates - {"id":"9907c323-1436-41f7-a600-e6b93d162cc8","homeId":"e6a3bdcb-88be-41ae-8587-c1ccab40b6c0","metaGroupId":"f3c7b976-1f03-4cb5-8c9a-2a5d72de5d92","label":"Wohnzimmer","lastStatusUpdate":1549573624647,"unreach":false,"lowBat":false,"dutyCycle":false,"type":"HEATING","channels":[{"deviceId":"3014F711A0000A1709ADEBCD","channelIndex":1}],"windowOpenTemperature":12,"setPointTemperature":23.5,"minTemperature":5,"maxTemperature":30,"windowState":null,"cooling":null,"partyMode":false,"controlMode":"AUTOMATIC","profiles":{"PROFILE_4":{"profileId":"f92c0747-b102-47a3-848a-b4a191a1fc3d","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_4","name":"","visible":true,"enabled":false},"PROFILE_5":{"profileId":"c4dbc7dc-ee9b-4ced-a7d9-2674b4e3220f","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_5","name":"","visible":false,"enabled":false},"PROFILE_6":{"profileId":"80bd4022-4a1d-4c61-9d41-5f726b00b425","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_6","name":"","visible":false,"enabled":false},"PROFILE_3":{"profileId":"3174a9d7-9185-4631-bbb3-d1be0c47b978","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_3","name":"","visible":false,"enabled":true},"PROFILE_2":{"profileId":"beda5fc5-1e38-454c-9f85-09434bbde948","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_2","name":"","visible":false,"enabled":true},"PROFILE_1":{"profileId":"87b525e1-9431-4f79-a564-bc2d37b6e5b0","groupId":"9907c323-1436-41f7-a600-e6b93d162cc8","index":"PROFILE_1","name":"Standard Wohnzimmer","visible":true,"enabled":true}},"activeProfile":"PROFILE_1","boostMode":false,"boostDuration":5,"actualTemperature":null,"humidity":null,"coolingAllowed":false,"coolingIgnored":false,"ecoAllowed":true,"ecoIgnored":false,"controllable":true,"floorHeatingMode":"FLOOR_HEATING_STANDARD","humidityLimitEnabled":true,"humidityLimitValue":60,"externalClockEnabled":false,"externalClockHeatingTemperature":19,"externalClockCoolingTemperature":23,"valvePosition":0.27,"sabotage":null}
`

Besten Dank noch, dass der Adapter überhaupt exestiert!!!

_Originally posted by @SliX185 in https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/29#issuecomment-461606425_

**Comment by jogibear9988** [comment]
@SliX185 ist drin, ist aber eine property der gruppe nicht des sensors

**Comment by SliX185** [comment]
@jogibear9988 Top! Vielen Dank! Leider sind die Objekte nur lesbar (read only). Wenn in den RAW daten "write": true" eingegeben wird, reicht leider nicht aus. Meine Idee war es mit einem Script die Boostfunktion im Bad zu steuern. ( humidity >= ??%  => boostMode = true)
Geht da noch was? Lg

**Comment by jogibear9988** [comment]
was müsste denn alles schreibbar sein? ich schau dann mal

**Comment by SliX185** [comment]
Für mich macht eigenlich nur "boostMode" Sinn, oder?
"controllable" weiß nicht ob man das recht steuern muss. "partyMode" macht ohne zusätzlichen Daten (Zeit/Datum) wahrscheinlich auch kein Sinn.

**Danke schonmal im Voraus! Machst nen Super Job!**

... und mir is grad noch was eingefallen, was aber mehr allgemein ist... 
"units" ist sicher nicht funktional, aber optisch schön (Raw daten zb. "unit": "°C",) aber das is nörgeln auf sehr hohen Niveau.

**Comment by jogibear9988** [comment]
> Für mich macht eigenlich nur "boostMode" Sinn, oder?
> "controllable" weiß nicht ob man das recht steuern muss. "partyMode" macht ohne zusätzlichen Daten (Zeit/Datum) wahrscheinlich auch kein Sinn.
> 
> **Danke schonmal im Voraus! Machst nen Super Job!**
> 
> ... und mir is grad noch was eingefallen, was aber mehr allgemein ist...
> "units" ist sicher nicht funktional, aber optisch schön (Raw daten zb. "unit": "°C",) aber das is nörgeln auf sehr hohen Niveau.

keine Ahnung was du damit meinst, aber kannst ja gerne mit nem pull req aushelfen ... :-)

**Comment by jogibear9988** [comment]
setboost sollte nun gehen

**Comment by SliX185** [comment]
Servus!
In main.js Zeile 1112 
`promises.push(this.setObjectNotExistsAsync('groups.' + group.id + '.boostMode', { type: 'state', common: { name: 'boostMode', type: 'boolean', role: 'info', read: true, write: false }, native:  { id: [group.id], parameter: 'setBoost' } }));`
und so funktionierts. ( write = true)
`promises.push(this.setObjectNotExistsAsync('groups.' + group.id + '.boostMode', { type: 'state', common: { name: 'boostMode', type: 'boolean', role: 'info', read: true, write: true}, native:  { id: [group.id], parameter: 'setBoost' } }));`

**Comment by jogibear9988** [comment]
oh ja, write hab ich vergessen
