### ISSUE TITLE
Implement missing Functional Channels

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.hmip#38]
Following are still missing

- [ ] DEVICE_INCORRECT_POSITIONED
- [ ] DEHUMIDIFIER_DEMAND_CHANNEL
- [ ] HEAT_DEMAND_CHANNEL
- [ ] FLOOR_TERMINAL_BLOCK_CHANNEL
- [ ] FLOOR_TERMINAL_BLOCK_LOCAL_PUMP_CHANNEL
- [ ] DEVICE_GLOBAL_PUMP_CONTROL
- [ ] PASSAGE_DETECTOR_CHANNEL
- [ ] PRESENCE_DETECTION_CHANNEL

**Comment by dprobst76** [comment]
Brauchst Du dazu noch Logfiles? Oder kann ich irgendwas dazu beitragen?

**Comment by jogibear9988** [comment]
nö, bräuchte Zeit! n pull request?

**Comment by FLAI16** [comment]
Hallo, sehr guter Adapter bisher! Großes Lob.

ich habe einen PUSH_BUTTON (HMIP-WRC2) - SINGLE_KEY_CHANNEL, welcher nicht richtig funktioniert. Die Channels sind angelegt, haben aber leider keine Funktion. Egal ob ich auf true oder false setze, es passiert nichts.
Falls ich irgendwelche Informationen zur Verfügung stellen kann, versuche ich gerne zu helfen.

**Comment by jogibear9988** [comment]
da kann ich nichts machen,für die channels kommen keine info aus der cloud!

**Comment by FLAI16** [comment]
Schade, hatte ich mir aber fast schon gedacht....

Trotzdem sehr gute Arbeit ;)

**Comment by dprobst76** [comment]
Hmm, was meinst Du mit Pull Request? Sorry kenn mich da nch nicht so aus...
