### ISSUE TITLE
Türschlossantrieb HmIP-DLD Datenpunkt lässt sich nicht steuern

### ISSUE THREAD

**Issue by Jeba0815** [iobroker-community-adapters/ioBroker.hmip#381]
Ich möchte über einen Datenpunkt die Tür Öffnung ansteuern.#
leider klappt das nicht.

Denk es ist der Datenpunkt "setLockState"  
Beim öffnen des Datenpunktes erscheint ein Drop-down-menü mit "Locked" "Unlocked" "Open"
Auch wenn ich den mauell setzte,reagiert das Türschloss nicht.

 
Adapterversion V1.17.0
NPM 6.14.7
Node.Js  14.19.2

**Comment by Apollon77** [comment]
Die PIN ist korrekt in der Adapter Konfiguration eingegeben? Sonst geht nur abschliessen. Bitte Readme lesen.

Wenn alles passt bitte Loglevel der Instanz auf Debug stellen und posten von so einer Aktion

**Comment by Jeba0815** [comment]
PIN hatte ich keine vergeben, also musste ich ja im Adapter auch keine eintragen  
Ich hab in der App noch mal alle Berechtigungen gelöscht und neu gemacht. 
Auch Node.ja eine Version höher upgedated. 
Komischerweise kann ich jetzt den Datenpunkt steuern. 
Allerdings verstehe ich nicht war ich vorher nicht mal abschließen könnte. Was ja immer gehen sollte. 
im LOG tauchte auch kein Eintrag auf, obwohl ich mehrmals den Datenpunkt manuell angestoßen habe. 
Kurz und knapp. Es funktioniert jetzt. 
Danke

**Comment by Jeba0815** [comment]
Man darf den Datenpunkt auch nicht mit OPEN,LOCK oder UNLOCK in Blockly steuern, sondern mit den Zahlen 1 ; 2 oder 3

**Comment by Apollon77** [comment]
> Man darf den Datenpunkt auch nicht mit OPEN,LOCK oder UNLOCK in Blockly steuern, sondern mit den Zahlen 1 ; 2 oder 3

ja :-)
