### ISSUE TITLE
Zustandswerte HmIP-BROLL im Protokoll

### ISSUE THREAD

**Issue by bambi-arch** [iobroker-community-adapters/ioBroker.hmip#387]
Hallo, bei den HmIP-BROLL Geräten wird im Protokoll unter "Info" folgendes angezeigt. Bitte bei Gelegenheit ändern. Danke

xxxxxxxxxxxx.channels.1.selfCalibrationInProgress" has to be type "string" but received type "boolean"

**Comment by Apollon77** [comment]
fixed in 1.19.1
