### ISSUE TITLE
6er Wandtaster HmIP-WRC6 Zeitstempel

### ISSUE THREAD

**Issue by bambi-arch** [iobroker-community-adapters/ioBroker.hmip#388]
Hallo,
bei den Wandtaster wird bei allen 6 Datenpunkten unter "on" der gleiche Zeitstempel angezeigt, obwohl nur die Taste "1" gedruckt wurde. Ich suche die Möglichkeiten, die Tasten Auszuwerten und andere Geräte zu steuern. Danke

![Bildschirmfoto 2022-08-21 um 23 11 28](https://user-images.githubusercontent.com/104907692/185811114-7d9c8279-28aa-4d40-a821-052b6d9d2d4c.png)

**Comment by Apollon77** [comment]
Von wann ist denn dieser Zeitstempel? Vllt vom Adapterstart? An sich werden Tastendrücke von Tastern nie gemeldet ... siehe auch Readme? Oder aktualisiert sich der Zeitstempel mit einem Druck? Falls ja bitte Debug Log anhängen von so einer aktion. Sonst leider "geht nicht anders"

**Comment by RP70DP** [comment]
> ...Ich suche die Möglichkeiten, die Tasten Auszuwerten und andere Geräte zu steuern. 

Das geht nicht. Es werden immer alle Zustände aktualisiert, wenn man irgendeine Taste drückt.
