### ISSUE TITLE
HmIP-KRCK buttons just not working

### ISSUE THREAD

**Issue by f-israel** [iobroker-community-adapters/ioBroker.hmip#391]
**Describe the bug**  
The states for buttons on HmIP-KRCK key are not updated - neither long nor short press.

**To Reproduce**  
Just take the normal way
    1. register device in CCU
    2. (to be sure) restart adapter with re-reading devices
    3. see states appear
    4. press any button

**Expected behavior**  
I expected the state would change for time being or flap at least

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/8896328/188510916-13bcde9f-4b59-4b43-aff6-4d3680553485.png)
All objects/states are created - this seems ok

![image](https://user-images.githubusercontent.com/8896328/188510790-aa80b8aa-7e0b-4634-af35-3afdb9b762d0.png)
States remain unchanged. Right side the full log output while (short) press button 3.

![image](https://user-images.githubusercontent.com/8896328/188510975-6adc6744-294d-4f17-b30f-3519da42db6e.png)
still initial value - event timestamp not changed

![image](https://user-images.githubusercontent.com/8896328/188511139-507c91f5-5e76-4102-8870-690ffc8c5572.png)
log of two button presses - upper half was button 4, lower button 3

**Versions:**  
 - Adapter version: hm-rpc v1.15.12
 - JS-Controller version:  4.0.23
 - Node version: v16.15.0
 - Operating system: Debian 10

**Comment by Apollon77** [comment]
Please read the Readme ... keypress is not "Pushed" as events, sono option to have that, sorry.

When you have a CCU2/3 then there would be a workaround, but not for hmip pure

**Comment by f-israel** [comment]
Sorry in advance for re-opening.

I'm not convinced key presses are not triggering events. Just attach to xml-rpc it seems that way regardless.
Just a side note: In some forum I read something about firing getValueUsage once for getting the presses as events. Tried to reproduce but I'm not a NodeJS nor XML-RPC developer - so I just failed the basics.

Other thing: using RedMatic there is also a node labeled "rpc event". Under the hood it's also using the HmIP-RF interface. See this config:
![image](https://user-images.githubusercontent.com/8896328/188628535-9c420757-446c-4727-9606-3b9ea78a53d1.png)

As seen in debugging tab the key pressed are triggering something.


Don't think there should be a way? I'll try to discover some way regardless. Btw: linked ref to named workaround would be nice

**Comment by Apollon77** [comment]
You compare XMLRPC protocol of an CCU with hmip Cloud which is NOT the same!

So:
* hmip Cloud (this adapter): Buttons do not work
* with a CCU you can create a program that "reacts" to buttons and as soon as you do this the conreete button preses arre available
