### ISSUE TITLE
Please support "HmIP-DSD-PCB" (DOOR_BELL_CONTACT_INTERFACE)

### ISSUE THREAD

**Issue by RP70DP** [iobroker-community-adapters/ioBroker.hmip#396]
See:
[iobroker forum](https://forum.iobroker.net/topic/58055/klingelsignalerkennung-hmip-dsd-pcb/117)
for fully log and discussion

Version 1.18.0

`hmip.0 (2046) updateDeviceStates - DOOR_BELL_CONTACT_INTERFACE - {"id":"XXX","homeId":"XXX","label":"Klingel","lastStatusUpdate":1663519071982,"type":"DOOR_BELL_CONTACT_INTERFACE","functionalChannels":{"0":{"label":"","deviceId":"XXX","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_BASE","groups":["XXX"],"unreach":false,"lowBat":false,"routerModuleEnabled":false,"multicastRoutingEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-49,"rssiPeerValue":null,"configPending":false,"dutyCycle":false,"deviceOverloaded":false,"coProUpdateFailure":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceUndervoltage":false,"deviceOverheated":false,"temperatureOutOfRange":false,"devicePowerFailureDetected":false,"supportedOptionalFeatures":{"IFeatureDeviceParticulateMatterSensorCommunicationError":false,"IFeatureDeviceCoProRestart":false,"IFeatureDeviceOverheated":false,"IOptionalFeatureDutyCycle":true,"IFeatureMulticastRouter":false,"IFeaturePowerShortCircuit":false,"IFeatureDeviceDriveModeError":false,"IFeatureDeviceTemperatureHumiditySensorCommunicationError":false,"IFeatureDeviceDriveError":false,"IFeatureRssiValue":true,"IFeatureBusConfigMismatch":false,"IFeatureDeviceOverloaded":false,"IOptionalFeatureDisplayContrast":false,"IFeatureDeviceIdentify":false,"IOptionalFeatureLowBat":true,"IOptionalFeatureMountingOrientation":false,"IFeatureDeviceTemperatureHumiditySensorError":false,"IFeatureDeviceTemperatureOutOfRange":false,"IOptionalFeatureDeviceErrorLockJammed":false,"IFeatureProfilePeriodLimit":false,"IFeatureDeviceCoProUpdate":false,"IFeatureDevicePowerFailure":false,"IFeatureShortCircuitDataLine":false,"IFeatureDeviceCommunicationError":false,"IFeatureDeviceUndervoltage":false,"IFeatureDeviceParticulateMatterSensorError":false,"IFeatureDeviceCoProError":false},"busConfigMismatch":null,"powerShortCircuit":null,"shortCircuitDataLine":null,"profilePeriodLimitReached":null,"mountingOrientation":null,"temperatureHumiditySensorError":null,"temperatureHumiditySensorCommunicationError":null,"particulateMatterSensorError":null,"particulateMatterSensorCommunicationError":null,"displayContrast":null,"lockJammed":null,"deviceDriveError":null,"deviceDriveModeError":null,"deviceCommunicationError":null},"1":{"label":"","deviceId":"XXX","index":1,"groupIndex":1,"functionalChannelType":"MULTI_MODE_INPUT_CHANNEL","groups":["XXX"],"multiModeInputMode":"SWITCH_BEHAVIOR","binaryBehaviorType":"NORMALLY_CLOSE","windowState":"CLOSED","corrosionPreventionActive":false,"doorBellSensorEventTimestamp":1663519066963,"supportedOptionalFeatures":{"IOptionalFeatureLongPressSupported":false,"IOptionalFeatureDoorBellSensorEventTimestamp":true,"IOptionalFeatureWindowState":false}}},"manufacturerCode":1,"oem":"eQ-3","liveUpdateState":"LIVE_UPDATE_NOT_SUPPORTED","firmwareVersion":"1.0.6","updateState":"UP_TO_DATE","firmwareVersionInteger":65542,"availableFirmwareVersion":"1.0.6","serializedGlobalTradeItemNumber":"XXX","modelType":"HmIP-DSD-PCB","modelId":410,"permanentlyReachable":false,"connectionType":"HMIP_RF"}`

**Comment by Apollon77** [comment]
What exactly is not supported? the main channel is a MULTI_MODE_INPUT_CHANNEL which is already supported

**Comment by Apollon77** [comment]
The only two fields that exists additionally here are:

```
"corrosionPreventionActive": false,
"doorBellSensorEventTimestamp": 1663519066963,
```

**Comment by Apollon77** [comment]
Yes I can add them. is this what is needed?

**Comment by RP70DP** [comment]
I don't think so. There are shutter contact datapoints with no function.

A screenshot of the object tree looks like this:
![1663497869631-screenshot-2022-09-18-124413](https://user-images.githubusercontent.com/62850183/190921769-d57a5086-1077-4c7e-8972-932543d855c2.jpg)

**Comment by Apollon77** [comment]
Try GitHub version, yet unreleased

**Comment by Apollon77** [comment]
So too much data in the object? Then this is up to the fact that we parse the data not based on device type but we simply present all data that are existing in the channels ... so when the data are in ... whey are in ... simply ignore it

**Comment by RP70DP** [comment]
Then what datapoint represents the state if the contact has been triggert?

**Comment by Apollon77** [comment]
Honestly ... no idea ... maybe the doorBellSensorEventTimestamp ?? One copuld assume it
