### ISSUE TITLE
Objekte werden nicht aktualisiert trotz bestehender Verbindung zur Homeatic IP Cloud

### ISSUE THREAD

**Issue by Matti82** [iobroker-community-adapters/ioBroker.hmip#398]
Ich beobachte das Problem schon seit einiger Zeit, habe aber jetzt damit angefangen die Ursache zu ergründen.
Da ich eine Automation über den ioBroker ausführe, wenn ich meine Eingangstür öffne, bekomme ich die fehlende Aktualisierung schnell mit.
Im Fehlerfall ist es so, dass der Zustand der Tür erfolgreich an die Cloud gemeldet wird, was ich über die App sehen kann.
Ich dachte zuerst das ich es über das Objekt "connection" unter Info mitbekommen und den Adapter neu starten kann. Aktuell habe ich gerade diesen Fehlerfall, die Connection ist ok und auch unter Adapterinfo ist alles grün. Also auf ins Logfile und geschaut, was dort zu finden ist:

hmip.0 | 2022-09-22 03:52:02.060 | warn | ws connection closed (0) - code: 1006 - reason:

Schaue ich mir andere Tage an, siehe es wie folgt aus:
2022-09-21 03:53:02.988 - warn: hmip.0 (264) ws connection closed (0) - code: 1006 - reason:
2022-09-21 03:53:13.192 - info: hmip.0 (264) ws connection opened

Das öffnen der Verbindung scheint einfach nicht zu geschehen, obwohl die Verbindung als ok angesehen wird!!

An der Zwangstrennung des Poviders kann es auch nicht liegen, diese wurde vorher getrennt und wieder aufgebaut:
22.09.22 03:36:08 Internetverbindung wurde erfolgreich hergestellt. IP-Adresse: , DNS-Server: und , Gateway:  Breitband-PoP: ASLJ00
22.09.22 03:36:01 Internetverbindung wurde getrennt.

Ich habe den Adapter manuell neu gestartet mit folgendem Ergebnis:
hmip.0 | 2022-09-22 11:28:14.123 | info | hmip adapter connected and ready
hmip.0 | 2022-09-22 11:28:12.808 | info | ws connection opened
hmip.0 | 2022-09-22 11:28:10.209 | info | starting. Version 1.18.0 in /opt/iobroker/node_modules/iobroker.hmip, node: v14.19.2, js-controller: 4.0.23
hmip.0 | 2022-09-22 11:28:10.070 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
hmip.0 | 2022-09-22 11:28:05.332 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
hmip.0 | 2022-09-22 11:28:05.330 | info | terminating
hmip.0 | 2022-09-22 11:28:05.329 | info | cleaned everything up...
hmip.0 | 2022-09-22 11:28:05.327 | info | Got terminate signal TERMINATE_YOURSELF
hmip.0 | 2022-09-22 03:52:02.060 | warn | ws connection closed (0) - code: 1006 - reason:

Was können wir tun um das Problem zu beseitigen? Einige Arbeitskollegen nutzen ebenfalls den HMIP Adapter und schildern die gleichen Probleme, somit kein Einzelfall. Ich hoffe meine Beschreibung kann behilflich sein das Problem zu beseitigen.

Liebe Grüße Matthias

**Comment by Apollon77** [comment]
Welche Adapter-Version wird genutzt? 1.18.0? IN https://github.com/iobroker-community-adapters/ioBroker.hmip#1192-2022-09-07 1.19.2 (Noch Beta) wurde zuletzt am Reconnect Handling genau für soclhe Fälle geschraubt und im nächsten Update nochmals ... Also bitte updaten

**Comment by Apollon77** [comment]
Bzw: Wenn das log voll mit den oben genannten "ws" Fehlern ist dann geht nichts wirkllich ... Wenn da im Log nichts ist dann sollte alles tun. Dann bitte Loglevel des Adapters auf Debug stellen und posten.
Bitter auch asicherstellen das alle Steueraktionen mit "bestätigt:false" ausgeführt werden, sonst ist es keine Steuerung!

**Comment by Matti82** [comment]
Hallo und Danke für die schnelle Antwort!
Normalerweise nutze ich die Beta Adapter nicht, bei einem Problem ist es jedoch sehr sinnvoll, habe auf die neueste v1.20.0 geupdatet und das Loglevel auf Debug gestellt. Ich werde das Thema beobachten und mich auf jeden Fall melden wie es lief. 
Das ws im Logfile tritt nur 1x pro Tag auf immer zur gleichen Zeit, ist das ein automatischer reconnect?
Im Logfile sollte dann demnächst mehr zu sehen sein.

Gruß Matthias

**Comment by Matti82** [comment]
Mal noch eine andere Frage, kann auch gerne einen neuen Request aufmachen. Ist es möglich über den Homematic Adapter einen Alarm auszulösen. Beispiel man hatte einige andere Bewegungsmelder z.B. von Philips Hue, die man so mit nutzen könnte. Wahrscheinlich ist es aber nicht gewollt, um Fehlalarme etc. zu verhindern.

**Comment by Apollon77** [comment]
Zur Frage: Kannst Du es per HMIP App? Glaube nein, also auch nein - wir können maximal das was die App kann

**Comment by Matti82** [comment]
Moin moin..
Danke für deine Antwort, über die App funktioniert es nicht, da gibt es maximal die Panikfunktion, ist vom Hersteller sicher auch nicht gewollt, da sonst nicht ihre Melder gekauft werden würden.

Ich habe heute früh mal ins Logfile geschaut mit der Logstufe Debug und der neuen Version.

hmip.0 | 2022-09-24 03:49:58.118 | info | ws connection opened
hmip.0 | 2022-09-24 03:49:47.917 | warn | ws connection closed (0) - code: 1006 - reason:

Ich sehe erstmal nur das er die Verbindung wieder erfolgreich aufgemacht hat, ist das so erstmal korrekt, dass nicht mehr ausgegeben wird?

Gruß Matthias

**Comment by Apollon77** [comment]
Reconnect ist so besser. nächste version hat aber noch eine Optimierung mehr
