### ISSUE TITLE
Reihenweise Fehlermeldung: "errorCode":"NOT_HEATING_GROUP"

### ISSUE THREAD

**Issue by unstressable** [iobroker-community-adapters/ioBroker.hmip#416]
Was hat es hiermit auf sich?

`<html>
<body>

hmip.0 | 2022-12-03 14:24:51.718 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
-- | -- | -- | --
hmip.0 | 2022-12-03 14:24:46.809 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
hmip.0 | 2022-12-03 14:24:41.727 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
hmip.0 | 2022-12-03 14:24:36.828 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
hmip.0 | 2022-12-03 14:24:31.727 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
hmip.0 | 2022-12-03 14:24:21.835 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}

</body>
</html>`

**Comment by Apollon77** [comment]
Bitte loglevel auf Debug setzen für die Instaz damit man sieht was genau das Kommando ist was gesendet wird was dazu führt.

**Comment by layeraccess** [comment]
Selber Fehler bei mir, kommt immer genau dann, wenn ich bei einem Thermostat eine andere Temperatur setze: 

`setState('hmip.0.devices.3014F711A0000A1D89982CC7.channels.1.setPointTemperature', 20);`

>hmip.0 | 2022-12-04 21:41:01.057 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}

Instanz läuft auf Loglevel Debug und hat sonst nichts weiter ausgespuckt.

**Comment by Apollon77** [comment]
Ok, sorry... silly log is needed

**Comment by layeraccess** [comment]
> Ok, sorry... silly log is needed

Auch da leider keine weiteren Infos.

**Comment by Apollon77** [comment]
Honestly ... Please let me decide which part of the liog is relevant wand which not. ELse you would be the developer ;)

**Comment by unstressable** [comment]
wieso screibst du eigentlich einmal deutsch und einmal englisch?

Hier das Silly log:

`<html>
<body>


Quelle | Zeit | debug | Nachricht
-- | -- | -- | --
hmip.0 | 2022-12-04 23:06:36.184 | warn | Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}
hmip.0 | 2022-12-04 23:06:36.057 | debug | setPointTemperature - id ["21a881df-f811-4f05-a982-0130182135bd","acce8b07-3ba8-4e46-bfb0-261d83dd058c"] - Send debounced value 19.5 now to HMIP
hmip.0 | 2022-12-04 23:06:31.051 | debug | state change - setPointTemperature - id ["21a881df-f811-4f05-a982-0130182135bd","acce8b07-3ba8-4e46-bfb0-261d83dd058c"] - value rounded to 19.5 (step=0.5 )
hmip.0 | 2022-12-04 23:05:58.657 | info | hmip adapter connected and ready


</body>
</html>`

**Comment by Apollon77** [comment]
1.) Standard GitHub ist für mich englisch, wobei ich mich anpasse wenn jemand deutsch schreibt ... manchmal übersehe ich aber was zuletzt war vor allem wenn ein post nur logs oder so war

2.) Log: Ok, damit müssen wir rausfinden welche der beiden Gruppen die er sendet warum "falsch" ist. Hatten wir schonmal das in den Daten eine Gruppe drin war die diesen Fehler auslöst. Btrauhcne dann bitte VOLLES Silly log ab adapterstart. Bitte per email an iobroker@fischer-ka.de mit referenz zu dem issue.

**Comment by unstressable** [comment]
Hier bekommst du es direkt:

`
hmip.0
2022-12-05 23:31:19.721	warn	Request error: StatusCodeError: 400 - {"errorCode":"NOT_HEATING_GROUP"}

hmip.0
2022-12-05 23:31:19.604	debug	setPointTemperature - id ["4849b947-3298-49d0-a0a6-424d809da2b2","f03ff9f5-81c9-4eba-800d-513088a3d1c8"] - Send debounced value 19.5 now to HMIP

hmip.0
2022-12-05 23:31:14.603	debug	state change - setPointTemperature - id ["4849b947-3298-49d0-a0a6-424d809da2b2","f03ff9f5-81c9-4eba-800d-513088a3d1c8"] - value rounded to 19.5 (step=0.5 )

hmip.0
2022-12-05 23:31:05.114	info	Value unchanged, do not send this value

hmip.0
2022-12-05 23:31:05.111	debug	setPointTemperature - id ["a2748d3d-9ab8-4920-8585-5296df832061","4ec7cceb-7c36-4327-a006-d6047fa694a0"] - Send debounced value 19 now to HMIP

hmip.0
2022-12-05 23:31:00.109	debug	state change - setPointTemperature - id ["a2748d3d-9ab8-4920-8585-5296df832061","4ec7cceb-7c36-4327-a006-d6047fa694a0"] - value rounded to 19 (step=0.5 )

hmip.0
2022-12-05 23:30:53.810	info	hmip adapter connected and ready

hmip.0
2022-12-05 23:30:53.809	debug	subscribeStates`

**Comment by Apollon77** [comment]
Jetzt liess bitte nochmal genau was ich brauche. GANZES Log im Loglevel Silly vom Adapterstart bis zum Problemzeitpunkt

**Comment by unstressable** [comment]
das Log wird gelöscht, wenn ich auf Silly umstelle.
Das gespeicherte zum downloaden schicke ich dir per Mail...

**Comment by Rookiestyle** [comment]
Ich hatte das Phänomen auch.

Schau bei dir mal im Adapter nach, aber nicht bei devices, sondern bei rooms. 
Da solltest du je einen Unterordner für die beiden IDs finden: 4849b947-3298-49d0-a0a6-424d809da2b2, f03ff9f5-81c9-4eba-800d-513088a3d1c8
Nut bei einem von beiden gibt's einen Datenpunkt `setPointTemperature`, mit dem sollte es ohne Warnung gehen.
Ist zumindest bei mir so, vielleicht geht's bei dir ja auch

**Comment by unstressable** [comment]
Gute Tipp, werde och nachschauen.
Müsste wahrscheinlich sehr viele Scripte umbauen.

**Comment by Flashaholic88** [comment]
> setPointTemperature

Habe das selbe Problem aber ich finde keinen ordner mit rooms, nur homes.
ich kann die temperatur zwar umstellen im homekit zB aber die fehlermeldung nervt schon etwas

**Comment by Flashaholic88** [comment]
> Ich hatte das Phänomen auch und hab es für mich gelöst, indem ich die Temperatur des Raums statt des Thermostats ändere.
> 
> Schau bei dir mal im Adapter nach, aber nicht bei devices, sondern bei rooms. Da solltest du je einen Unterordner für die beiden IDs finden: 4849b947-3298-49d0-a0a6-424d809da2b2, f03ff9f5-81c9-4eba-800d-513088a3d1c8 Nut bei einem von beiden gibt's einen Datenpunkt `setPointTemperature`, mit dem sollte es ohne Warnung gehen. Ist zumindest bei mir so, vielleicht geht's bei dir ja auch
> 
> In der Homematic App ändere ich ja auch nicht die Temperatur des Thermostats sondern die des Raums, so bin ich draufgekommen

Habe das selbe Problem aber ich finde keinen ordner mit rooms, nur homes.
ich kann die temperatur zwar umstellen im homekit zB aber die fehlermeldung nervt schon etwas

**Comment by unstressable** [comment]
Lege mal in der HomematicIP App Räume an, verknüpfe die entsprechenden Thermostate.

Anschließend sollte ein Ordner Groups in ioBroker erscheinen.

dann dort die Datenpunkte verwenden, nicht bei Devices wie bisher.

**Comment by Flashaholic88** [comment]
Also wenn ich die aktuelle Temperatur auslese über devices wird es in Homekit angezeigt aber bei groups nicht.
auch kann ich zwar die temperatur im homekit regeln in den groups aber wenn ich im homekit heizen wieder deaktiviere bleibt die Temperatur so und geht nicht mehr zurück.

**Comment by unstressable** [comment]
Die aktuelle Temperatur muss vom device genommen werden, da jedes device seine eigene Temperatur misst.

Die Solltemperatur (setPointTemperature) sollte auf die Gruppe (Raum) geschrieben werden, damit alle Geräte in diesem Raum bescheid wissen.
Oft gibt es mehrere Thermostate im Raum oder gar ein Wand-Controller. Diese sollten alle die gleiche Soll-Vorgabe erhalten.
