### ISSUE TITLE
"Schlüsselbundfernbedienung" / "KEY_REMOTE_CONTROL_KEY_MATIC" for Locks - missing state updates

### ISSUE THREAD

**Issue by tehmilcho** [iobroker-community-adapters/ioBroker.hmip#442]
Hey there,

it is possible to get the States when you are pressing a Button on the Remote?
In under Device it is already listed also is there an Channel for each Button (4 in total) but the values for the "state" will be all the time "(null)"

![image](https://user-images.githubusercontent.com/22918349/229601571-223346f1-81dd-4219-a0ee-91f9d6e59d63.png)

Because you need only 3 buttons to control all functions of the lock from Homematic,  i want to use the last one to control my "Ring Intercom" from the "ring" Adapter (over an blocky rule) but because i dont get trigger when the buttons is pressed in Iobroker, i cant build something.

Im Using the Cloud Accesspoint in the moment.

In the debugmode you will see the button will trigger one line of log:
hmip.0 | 2023-04-03 21:04:04.383 | debug | Read Home for SECURITY_JOURNAL_CHANGED: {"pushEventType":"SECURITY_JOURNAL_CHANGED"}

but im not sure it is because in the moment is set to change the Alarm-Mode.

**Comment by Apollon77** [comment]
Sotry... please see Readme, no chance, "Taster" are not reported ... It migth work to link them to an action (at least in CCU it works that way), but no idea for HMIP

**Comment by tehmilcho** [comment]
yep sad .. i want to switch to the CCU3 anyway im but to lessy or i just get an Smart-Plug from them and let the Remote-Control switch this plug and then build my rules around the plug. thanks for fast response
