### ISSUE TITLE
No states for HmIP-WRC6 in iobroker

### ISSUE THREAD

**Issue by niki11euro** [iobroker-community-adapters/ioBroker.hmip#445]
Hey there,

ich have a HmIP-AP and the HmIP-WRC6. They are connected with the App. Ich have installed the HmIP-Adapter in my iobroker but I can't get any states for my remote.

![image](https://user-images.githubusercontent.com/38863831/231554997-c8377e60-feb7-47db-8e28-e3b39f8c9229.png)

![IMG_6985F87B1E69-1](https://user-images.githubusercontent.com/38863831/231556082-e97ccb35-247a-416d-b2e4-ce82b6c6cbe9.jpeg)

Thank you for you're help!

**Comment by Apollon77** [comment]
Sorry, but nope. Readme states:

> !!! You can only trigger events with this adapter that can be triggered through the original Homematic IP app. For example direct connections between devices have no events in the app and can also not be triggert through this adapter!!!

"Taster" are exactly that
