### ISSUE TITLE
HMIP-BROLL Info Meldung im Protokoll

### ISSUE THREAD

**Issue by SebeSebe** [iobroker-community-adapters/ioBroker.hmip#459]
Hallo 
Habe folgende Info Meldung im Protokoll
(COMPACT) State value to set for "hmip.0.devices.xxxxxxx.channels.1.previousShutterLevel" has to be type "string" but received type "number"

wenn es passt bitte korrigieren.

Grüße 

**Versions:**  
 - Adapter version: 1.20
 - JS-Controller version: 4.0.24  
 - Node version: v18.16.1  
 - Operating system: raspi

**Additional context**

**Comment by Apollon77** [comment]
Closed because?

**Comment by SebeSebe** [comment]
In between I changed my environment: Hmip to Somfy and upgraded to a raspi 4. 
So I am no more able to reproduce the case above.
