### ISSUE TITLE
HmIP-DBB ändert den Wert nicht, wenn der Klingeltaster betätigt wird.

### ISSUE THREAD

**Issue by SaschaSchr** [iobroker-community-adapters/ioBroker.hmip#474]
Sobald ich den Taster betätige, soll in IoBroker das entsprechende Objekt geändert werden. Allerdings aktualisiert sich nichts. 
![HMIPDBB](https://github.com/iobroker-community-adapters/ioBroker.hmip/assets/86142033/2fdbf5b6-4e9b-4bfb-97d7-96802ae48553)

**Versions:**  
 - Adapter version: 1.20.0
 - JS-Controller version: js-controller-version
 - Node version: node -v
 - Operating system: proxmox

Der Debug-Modus ergibt keine Werte.

**Comment by Apollon77** [comment]
Taster?? Dann wird das nicht gehen weil tasterzustände meistens nicht gemeldet werden. Von daher: wenn es nicht von hmip gepusht wird kann es der adapter nicht anzeigen.

**Comment by SaschaSchr** [comment]
Gibt es eventuell eine Alternative? Alexa kann auf den Taster reagieren. Allerdings finde ich im Alexa2 Adapter keinen Punkt an dem ich es abgreifen kann. Über Node Red? Da habe ich keine Erfahrung mit. Sollte es gehen, werde ich mich gerne einlesen.

**Comment by Apollon77** [comment]
ich kenne keinen weg
