### ISSUE TITLE
HmIP-BSL einfügen möglich?

### ISSUE THREAD

**Issue by Feuer001** [iobroker-community-adapters/ioBroker.hmip#50]
Hallo,

wäre es möglich den Schaltaktror für Markenschalter mit Signalleuchte (HmIP-BSL) mit einzubauen,
sodass die beiden Signalleuchten über iobroker angesteuert werden können? 
Leider fehlt mir momentan diese Funktion...

**Comment by jogibear9988** [comment]
KP ob das möglich ist, schick mal das JSON von dem (Adapter auf Silly stellen und aus dem Logfile (nicht der Webseite) kopieren), dann kann ich mal schauen.
Weiß aber nicht ob das die API schon hergibt

**Comment by Feuer001** [comment]
Wenn du mir kurz erklären könntest wo ich diese infos herbekomme, dann kann ich dir diese morgen nachmittag gerne zukommen lassen. Im Log auf der Adminseite habe ich gerade auf silly gestellt und kann z.B. bei Farbänderung schon eine Ausgabe mit "unkown channel type - NOTIFICATION_LIGHT_CHANNEL...." sehen. Sorry, hab leider momentan bezüglich iobroker nur minimal Wissen.

**Comment by Feuer001** [comment]
Ich habe nur das im Log gefunden:
`2019-03-12 20:34:58.671  - [32minfo[39m: hmip.0 unkown channel type - NOTIFICATION_LIGHT_CHANNEL - {"id":"3014F711A0001A58A9A240DD","homeId":"32bc43fe-ab94-4854-b774-176566eb839f","label":"Schlafzimmerlicht ","lastStatusUpdate":1552417698016,"type":"BRAND_SWITCH_NOTIFICATION_LIGHT","functionalChannels":{"0":{"label":"","deviceId":"3014F711A0001A58A9A240DD","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_BASE","groups":["f472eb04-05aa-4da8-a885-cfadb4e15699"],"unreach":false,"lowBat":null,"routerModuleEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-59,"rssiPeerValue":-61,"configPending":false,"dutyCycle":false},"1":{"label":"","deviceId":"3014F711A0001A58A9A240DD","index":1,"groupIndex":1,"functionalChannelType":"SWITCH_CHANNEL","groups":["263985b7-1a03-4722-a101-af0ac453dbc2"],"on":false,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC"},"2":{"label":"","deviceId":"3014F711A0001A58A9A240DD","index":2,"groupIndex":2,"functionalChannelType":"NOTIFICATION_LIGHT_CHANNEL","groups":["263985b7-1a03-4722-a101-af0ac453dbc2"],"on":null,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC","dimLevel":0,"simpleRGBColorState":"RED"},"3":{"label":"","deviceId":"3014F711A0001A58A9A240DD","index":3,"groupIndex":3,"functionalChannelType":"NOTIFICATION_LIGHT_CHANNEL","groups":["263985b7-1a03-4722-a101-af0ac453dbc2"],"on":null,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC","dimLevel":1,"simpleRGBColorState":"GREEN"}},"oem":"eQ-3","manufacturerCode":1,"firmwareVersion":"1.0.2","updateState":"UP_TO_DATE","firmwareVersionInteger":65538,"liveUpdateState":"LIVE_UPDATE_NOT_SUPPORTED","availableFirmwareVersion":"0.0.0","permanentlyReachable":true,"serializedGlobalTradeItemNumber":"3014F711A0001A58A9A240DD","modelType":"HmIP-BSL","modelId":360}
`

ka ob das hilft...

**Comment by jogibear9988** [comment]
ich schaus mir am WE an

**Comment by steckenpferd** [comment]
Any news?

**Comment by jogibear9988** [comment]
erl
