### ISSUE TITLE
V1.21.0 HmIP-FBL shutterlevel no value anymore

### ISSUE THREAD

**Issue by DaniSchaer** [iobroker-community-adapters/ioBroker.hmip#518]
With V1.21.0 there is no shutterlevel for HmIP-FBL anymore
After rollback to V1.20.0 it works fine again

**Comment by Apollon77** [comment]
Please post a debug log that shows when an update of the value is received. Thank you

**Comment by DaniSchaer** [comment]
Besten Dank für die Rückmeldung. Bei den Tests den issue zu debuggen konnte das Verhalten nicht mehr reproduziert werden. Möglicherweise war ich einfach zu ungeduldig.
Ticket geschlossen
