### ISSUE TITLE
Request Token not working

### ISSUE THREAD

**Issue by loskrachos** [iobroker-community-adapters/ioBroker.hmip#533]
Unfortunately description and video are not any longer matching the apperence of the recent Homematic IP App. (iOS, 2.17.1)

I have activated "Einstellungen->Benutzerverwaltung->Benutzerrechte" and hereby generated an "Administrator-PIN".

With the adapter I use the SGTIN of the device and this Admin-PIN
ioBroker system is fresh and was installed with all the latest updates just the day before.

I have to mention, that I use the "Multi-Home-Verwaltung" within Homematic IP App and have registered 8 HMIP-HAPs. Currently only the one is online, that I am trying to connect to. App is working fine.

I am attaching the log(silly) for the failing request. SGTIN was anonymized in the last 2 parts
[hmip_tokenfailed.txt](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/14498693/hmip_tokenfailed.txt)

**Comment by Apollon77** [comment]
duploicate #532

**Comment by loskrachos** [comment]
regarding log messages it looks the same - I just thought, that I have an Administrator-PIN whilst #532 states "without PIN". But log messages do pretty much look the same...
