### ISSUE TITLE
thermostate temperature

### ISSUE THREAD

**Issue by hallerdavid** [iobroker-community-adapters/ioBroker.hmip#536]
Hello together

i have a little problem. We have some hmip theromstats in our flat that are controlled via this adapter. I can set the "SetPointTemperature" to every value i want - and it works!

BUT since a few days, for each thermostat one value is ignored.. so i have an eco temperature 19 degrees in room A and 18 degrees in room B.

In room B i can set every value, but not 18 degrees and in room A not 19 degrees. Every other value will work.

Can you help me? The eco temperature is not set in the HMIP app, there is everything on profile "manual".

**Comment by Apollon77** [comment]
Please provide a debug log of trying to make the calls

**Comment by mcm1957** [comment]
no log provided - lets close

Please open a new issue and provide complete version information and a log with level debug if issue still exists.
