### ISSUE TITLE
Homematic IP Neue Home Control Unit ab Q4/24

### ISSUE THREAD

**Issue by bambi-arch** [iobroker-community-adapters/ioBroker.hmip#537]
Hallo,
Homematic Ip hat für Q4/2024 eine neue Home Control Unit (Cloud und Lokal mit Homematic APP) angekündigt inkl. 
Entwicklerschnittstelle.
Hab ihr schon  Überlegungen, ob dies neue Unit in diesem Adapter zu integrieren oder einen neuen Adapter zu machen?

Danke im Voraus.

https://homematic-ip.com/de/produkt/home-control-unit

**Comment by Apollon77** [comment]
Hm ... was denkst du ist die Antwort? :-) Ohne Informationen zu dem Gerät und was es wie tut und so ist das schlicht nicht zu beantworten. Also erstmal muss das Gerät auf dem Markt sein, dann muss es ein Developer haben und dann zeit haben es anzusehen und entweder Anpassungen vorzunehmen oder was neues zu bauen. Sorry, aber aktuell schlicht nicht zu beantworten
