### ISSUE TITLE
Status Alarm-Modus

### ISSUE THREAD

**Issue by neom29** [iobroker-community-adapters/ioBroker.hmip#54]
Hi,

can you please add the status of the Alarm-Modus (disable, cover protection, full protection) in
Homes.securityAndAlarm

Thank you in advance!

**Comment by steckenpferd** [comment]
@neom29 - Jochen doesn't have much time - a Pull Request would help to support him

**Comment by andiak1990** [comment]
Sorry i Dont know how to Make a pull request.  :/
