### ISSUE TITLE
Verbunden mit hmip: falsch

### ISSUE THREAD

**Issue by Acuario4** [iobroker-community-adapters/ioBroker.hmip#55]
Hallo zusammen,
jedes mal, wenn ich im iobroker einen Token in der Instanz hmip.0 automatisch erstellen lasse, dann klappt das ohne Probleme und in meiner HomeMatic IP App (auf dem Handy) wird erfolgreich angezeigt, dass ein neuer Benutzer (iobroker) hinzugefügt wurde. Wenn ich nun auf "Speichern und schließen" drücke, schließt sich das Fenster normal und der Adapter wird neu gestartet. Und ab hier funktioniert gar nichts mehr.

- Wenn ich über das Statuslämpchen der Instanz im iobroker hover, steht da: "Verbunden mit Host: wahr | Lebenszeichen: wahr | Verbunden mit hmip: falsch"
- Im Log steht als Fehlermeldung: "error starting homematic: TypeError: this.setObjectNotExistsAsync is not a function"
- Unter: Objekte -> hmip.0 -> info -> connection (Expertenmodus Ansicht) ist der status "false"
- Unter: Objekte -> hmip.0 -> sind gar keine weiteren Dateien (so wie Smarthome Geräte), abgesehen von der soeben genannten

Den Token neu erstellen lassen hilft, neu starten ebenso wenig.
Mache ich etwas falsch oder ist das ein Bug o.ä.?

Danke im Voraus für die Hilfe

Grüße

**Comment by jogibear9988** [comment]
welche node version? iobroker version?

Von meinem iPhone gesendet

**Comment by Acuario4** [comment]
![image](https://user-images.githubusercontent.com/47208805/55670054-d0e0e000-587f-11e9-9d22-50d3bbc8491c.png)
![image](https://user-images.githubusercontent.com/47208805/55670060-e9e99100-587f-11e9-91a4-6749b2d6876d.png)
Danke für die schnelle Antwort!
Kenne mich mit dem Thema leider noch nicht so gut aus, wo finde ich die node version?

**Comment by steckenpferd** [comment]
Any news

**Comment by jogibear9988** [comment]
node version??

**Comment by Acuario4** [comment]
Wo finde ich die node version?

**Comment by jogibear9988** [comment]
http://lmgtfy.com/?q=read+node+version

**Comment by Acuario4** [comment]
Die Node Version ist: v8.11.1

**Comment by marcbroe** [comment]
Hallo, ich habe das gleiche Problem wie bereits oben beschrieben...
Tokken usw. alles ohne Probleme, auch der Benutzer "iobroker" wird in der Homematic app angelegt aber der Adapter bleibt auf gelb. Neustart und noch mal neu den Tokken usw. setzen blieb ohne erfolg. Node 8.6 ist installiert... Danke schon einmal.

**Comment by jogibear9988** [comment]
geht das mittlerweile? ich habe keine idee

**Comment by michaelheiml** [comment]
Same here, gibts dafür eine Lösung?

**Comment by michaelheiml** [comment]
Ok ich hab gerade durch Zufall herausgefunden was dabei das Problem ist - man muss so vorgehen:
1. die STGIN Nummer eingeben (NICHT Save drücken)
2. Den Connect Prozess starten
3. Auf der Bridge blauen Button drücken
4. Dann erst SAVE klicken
(Problem: wenn man nach Eingabe der STGIN Nummer bereits Save drückt, kann man SAVE nicht noch einmal nach Abfrage des Tokens drücken sondern nur CLOSE, dann geht die Verbindung aber nicht)

**Comment by Acuario4** [comment]
Hallo zusammen,

keine Ahnung, warum, aber nachdem ich den raspberri pi einmal neu aufsetzen musste, hat es dieses mal doch funktioniert. Das ist zwar keine Erklärung, warum es jetzt klappt, es aber vorher nicht geklappt hat, aber damit beurteile ich zumindest das Problem für gelöst, weshalb ich dieses Problem hier jetzt schließen werde.
Vielen Dank an alle, die versucht haben zu helfen!

Grüße
