### ISSUE TITLE
Typ-Fehler bei State hardwareColorTemperatureColdWhite und previousShutterLevel

### ISSUE THREAD

**Issue by tt-tom17** [iobroker-community-adapters/ioBroker.hmip#571]
Tippfehler beim State hardwareColorTemperatureColdWhite Typ number

[Code Zeile ](https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/bd8f6e56991dbb5f96740e70186650266510df1e/main.js#L2445)

falscher Typ bei State previousShutterLevel => Typ ist number (altes issue #459) 

[Code Zeile](https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/bd8f6e56991dbb5f96740e70186650266510df1e/main.js#L2378)

[Code Zeile](https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/bd8f6e56991dbb5f96740e70186650266510df1e/main.js#L2567)

Edit: [Verweis zum Forumbeitrag](https://forum.iobroker.net/post/1177916)

**Comment by Apollon77** [comment]
Please try GitHub version. Install, manuall restart adapter and verify please and report back. Then I release it

**Comment by LukasMS55** [comment]
seems to be solved (see #572 )

**Comment by Apollon77** [comment]
release comes
