### ISSUE TITLE
kann kein token erstellen

### ISSUE THREAD

**Issue by Feuer001** [iobroker-community-adapters/ioBroker.hmip#58]
wie kann ich einen token erstellen?
das Feld token erstellen ist bei mir ausgegraut.
habe auch schonmal den Adapter neuinstalliert...

**Comment by steckenpferd** [comment]
Ich wäre dafür disen Issue zu schließen.

@Feuer001 Solche individuellen Themen sollten im Forum besprochen werden:
https://forum.iobroker.net/topic/18872/aufruf-homematic-ip-cloud-access-point-adapter

**Comment by jogibear9988** [comment]
@Feuer001 die anderen werte hast du alle ausgefüllt? steht den im log ein fehler?
node version?

**Comment by Feuer001** [comment]
Ja alle Werte waren eingetragen.
Hatte schonmal den HmIP Cloud Adapter installiert und auch da war es schon so fummelig diesen zum laufen zu bekommen. Irgendwann lief es dann. Zwischenzeitlich hatte ich ein update von ioBroker gemacht und dabei wurde auch die Node Version „aktualisiert“. Nach einem manuellen Update von Node läuft es nun wieder. Besten Dank!

Kann hier geschlossen werden.
