### ISSUE TITLE
hm-rpc.0 error Cannot call setValue: Unexpected endLine: 0Column: 0Char:

### ISSUE THREAD

**Issue by Docdisaster** [iobroker-community-adapters/ioBroker.hmip#586]
****Versions:****  
 - Adapter version: v1.17.0
 - JS-Controller version: 6.0.11
 - Node version: v20.17.0
 - Operating system: Debian 12.7 (Proxmox LXC Container)
 

Neuerdings erhalte ich beim Steuern meiner Homematic Geräte folgende Fehler: 

In diesem Beispiel handelt es sich um ein Homematic IP Thermostat:
hm-rpc.0 error	Cannot call setValue: Unexpected endLine: 0Column: 0Char:
hm-rpc.0 error	xmlrpc -> setValue ["000A9A49A2DB47:1","SET_POINT_TEMPERATURE",5] FLOAT

Auslöser sind Blockly Skripte. Der Wert wird trotz Fehlermeldung geändert.

****Screenshots & Logfiles****  
![Screenshot 2024-09-06 082243](https://github.com/user-attachments/assets/faaccf71-a4f3-47d4-86f4-1beba25d3034)
![Screenshot 2024-09-06 082012](https://github.com/user-attachments/assets/b018a6e8-2cd3-4633-9ae8-2ef41d964dea)
![Screenshot 2024-09-06 082209](https://github.com/user-attachments/assets/1d4f2bf0-f168-4aa6-ad9f-1c01fe9f6d29)
![Screenshot 2024-09-06 082745](https://github.com/user-attachments/assets/de80e54f-546e-4017-b7a6-098ae1e54e8e)

**Comment by Apollon77** [comment]
hmip !== hm-rpc :-) Please recreate in correct adapter repo
