### ISSUE TITLE
Neues Gerät (HmIP-FSM) wird nicht gefunden

### ISSUE THREAD

**Issue by backons** [iobroker-community-adapters/ioBroker.hmip#61]
Ich habe vor zwei Tagen ein neues Gerät am Access Point angelernt. Es handelt sich um den Schalt-Mess-Aktor Unterputz HmIP-FSM.
Leider erscheint das Gerät nicht im ioBroker unter Devices.
Nach der ursprünglichen Installation des Adapters habe ich schon mehrere Geräte nachträglich hinzugefügt. Alle sind dann auch im ioBroker erschienen.
Ich habe den Adapter auch schon mehrfach neugestartet...
Kann ich irgendetwas tun damit das Gerät auch erscheint ?

**Comment by steckenpferd** [comment]
Genau wie beim Wassermelder LOG/JSON posten und dann hoffen/warten das Jochen oder jemand anderes sich die Zeit nimmt um den Adapter zu erweitern.
