### ISSUE TITLE
HmIP-WRC6 missing update for switch: on

### ISSUE THREAD

**Issue by dahlweid** [iobroker-community-adapters/ioBroker.hmip#68]
I just connected a HmIP-WRC6 remote control (6 buttons) to iobroker. I can see all 6 channels in the iobroker UI. If I press any button, I also see that all properties of all channels/buttons are updated, but the state of the "on" switch does not change, nor it is updated at all. I had planned to trigger on any change of the value of that switch, but there are no updates to `hmip.0.devices.<id>.channels.6.on` or for any other channel.

**Comment by jogibear9988** [comment]
https://github.com/iobroker-community-adapters/ioBroker.hmip/issues/34
