### ISSUE TITLE
0.0.12 into stable?

### ISSUE THREAD

**Issue by steckenpferd** [iobroker-community-adapters/ioBroker.hmip#72]
Hi,

doesn't it make sense to send 0.0.12 to stable?

**Comment by steckenpferd** [comment]
@Apollon77 @DutchmanNL @GermanBluefox 

Jogi scheint nicht mehr viel Zeit zu haben - könnte jemand aus der community übernehmen und ihn in stable schieben?

**Comment by marcus0303** [comment]
Ich hatte Jogi angeschrieben, da ich seine Version 0.0.12 noch um die Kanaltypen  (Wassermelder) DEVICE_INCORRECT_POSITIONED, (Fussbodenheizungsaktor) DEVICE_GLOBAL_PUMP_CONTROL, FLOOR_TERMINAL_BLOCK_LOCAL_PUMP_CHANNEL erweitert habe (nur lokal bei mir) und ihn gefragt, ob er den Quellcode haben möchte, aber leider bisher noch keine Antwort.
Da ich noch neu bei GitHub bin und mich noch nicht richtig auskenne, weiss ich leider nicht, wie oder wem ich die Information sonst noch zukommen lassen könnte.

**Comment by Apollon77** [comment]
Mach einen pull request. 

Am einfachsten: GitHub dort auf den Stift beim file. Alles so anpassen und dann unten Änderungen kommentieren und absenden.

**Comment by marcus0303** [comment]
@Apollon77 
Danke für den Hinweis.
Ich schau mal, ob ich das hinbekomme.

**Comment by Apollon77** [comment]
Sonst helfen wir gern

**Comment by jogibear9988** [comment]
@marcus0303 vlt. hast du ja lust der community beizutreten und dich ein bisschen um den adapter zu kümmern?  ich komm da leider wenig dazu, vor allem weil ich ihn nicht verwende!

**Comment by marcus0303** [comment]
Ich bin zwar Informatiker, aber kein Experte in Java.
Solange es um Erweiterungen von Channels geht, kann ich gerne unterstützen.
Ich habe ja auch schon viel von der Community profitiert, und könnte so etwas zurückgeben.

**Comment by steckenpferd** [comment]
@marcus0303 @jogibear9988 könnte man nicht schon mal die Version in stable schieben?

**Comment by jogibear9988** [comment]
ich komme zur Zeit leider gar nicht dazu an iobroker zu arbeiten.
an hmip noch weniger da ich es selbst nicht nutze. also wenn jemand hier gerne weiterarbeiten möchte, ich nehme gerne jemand in die community auf das er am adapter arbeiten kann
