### ISSUE TITLE
HMIP-BSL LED nicht steuerbar

### ISSUE THREAD

**Issue by GLichtenauer** [iobroker-community-adapters/ioBroker.hmip#77]
Hallo, leider kann man beim HMIP-BSL die 2 LEDs (obere / untere Taste) nicht steuern und die Farbe ändern. Wäre super wenn das noch integriert werden könnte.
VG
Günter

**Comment by jogibear9988** [comment]
gibt das denn die api irgendwie her?

**Comment by GLichtenauer** [comment]
Hallo jogibear9988,
Ich habe folgenden  Hinweis von dem Rest-Api Team bekommen:

hast du es schon mit Async/BrandSwitchNotificationLightset_rgb_dim_level probiert?

Nützt das was ?

Viele Grüße 
Günter

**Comment by GLichtenauer** [comment]
Zusätzliche Erkenntnis:
Die IOBROKER Alternative 
HomeAssistant unterstützt die Led Steuerung. Und die nutzen auch die API von coreGreenberet...
Somit müsste die Rest-Api das eigentlich unterstützen.... !?

**Comment by jogibear9988** [comment]
glaube die led hab ich vergessen
muss schaun wann ich dazu komm

**Comment by GLichtenauer** [comment]
Wäre super wenn das funktionieren würde!
Vielen Dank für Deine tolle Arbeit!

VG
Günter

**Comment by Andy200877** [comment]
Ich habe die Version 1.1.0 unter IOBroker installiert.
Leider lassen sich auch da noch nicht die Farben / Helligkeit der Tasten schalten. :-(
Die Objekte (Channel 2+3)
hmip.0.devices.xxxx.channels.2.simpleRGBColorState
hmip.0.devices.xxxx.channels.2.simpleRGBColorState
hmip.0.devices.xxxx.channels.2.dimLevel

sind readonly. Auch nach einem ändern auf "schreiben möglich" lassen sich die LED's nicht steuern.
In der App funktioniert das jedoch.

Gibt es dazu schon eine Lösung ? Oder steht es auf der ToDo-Liste und kommt mit einem späteren Update ?

**Comment by HornetRider81** [comment]
Hallo,

ich würde es großartig finden, wenn sich hier eine Lösung finden lassen würde.
Die App Smartha kann die LEDs ebenfalls steuern (die wird zwar inzwischen auf offiziell beworben, aber vielleicht hilft das trotzdem).
Leider kann ich nicht mit einem Pull Request dienen.


Vielen Dank noch dafür, dass der Status der Alarmanlage jetzt über die Gruppen EXTERNAL und INTERNAL jetzt auslesbar ist.

VG
Thorsten

**Comment by HornetRider81** [comment]
Hi,

schalten kann man die LED, wenn man den Datenpunkt "on" so bearbeitet, wie den vom Kanal 1.
Also in "allgemein" die "Rolle" auf "switch" ändern. 
Dann noch in "nativ" die drei Einträge "id", channel" und "parameter" anlegen. Bei "channel" den richtigen Kanal "2" oder "3" nehmen, die beiden anderen Werte vom Kanal 1 übernehmen.

dimLevel und simpleRGBColorState konnte ich leider bisher nicht richtg anpassen.

VG
Thorsten

**Comment by Andy200877** [comment]
Die tasten oben / unten können nicht abgefragt werden oder ? Weil wer auch immer sich diese logik ausgedacht hat, hat ihn wahrscheinlich nie wirklich benutzt. 2 taster ok. Aber einen zum einschalten und den anderen zum ausschalten des lichts zu nehmen ist schon ziemlich dämlich. Warum kann man nicht beide Taster einzeln "belegen" ? Also taster 1 toggled das licht , taster 2 löst eine andere aktion bzw. Schaltet einen anderen aktor ? Naja verstehen tue ich es nicht...ich habe gehofft das ich über iobroker die taster bekomme um zu triggern. Aber kanal 2 und 3 sind die led's. Und kanal 1 sind beide taster on/off

**Comment by HornetRider81** [comment]
Hi, 

Kanal 1 ist der geschaltete Ausgang vom BSL. Beim BSM geht das auch nicht.
Wer den Ausgang nicht benötigt, ist mit einem BRC2 oder WRC2 besser beraten, da geht das mit dem Access Point. 
Mit einer CCU kann man die interne Direktverknüpfung aufheben und die Taster einzeln verwenden. 
Aber das ist ein komplett anderes Thema. 

VG
Thorsten

**Comment by apex1834** [comment]
Mit einer CCU scheint die Ansteuerung problemlos über die zusätzlichen Kanäle zu gehen. Hat HMIP wirklich nur die 3?

dimLevel als level mit "write" scheint leider nicht zu funktionieren.

**Comment by HornetRider81** [comment]
Hi, 

Hast du eine CCU und einen BSL?
Könntest du ggf gucken, wie die von mir genannten Parameter heißen? 
Auch wenn der Adapter für die CCU eventelk anders aufgebaut ist. 
Nur schreiben erlauben reicht nicht, da noch weitere Daten fehlen.

**Comment by apex1834** [comment]
Der BSL ist aktuell mit dem Accesspoint gekoppelt und lässt sich leider nicht mehr trennen. Auch das zurücksetzen auf die Werkseinstellungen hat nicht funktioniert.

**Comment by apex1834** [comment]
In der API Doc von REST gibt es aber einen Eintrag dazu:
https://homematicip-rest-api.readthedocs.io/en/latest/homematicip.html?highlight=BSL#homematicip.device.BrandSwitchNotificationLight

**Comment by apex1834** [comment]
JSON scheint nicht viel herzugeben:

2020-08-03   20:44:41.222 - silly: hmip.0 (4613) updateDeviceStates -   BRAND_SWITCH_NOTIFICATION_LIGHT -   {"id":"3014F711A0001A5A00000000","homeId":"678e1ade-c1fd-46f9-9740-306a79f17c5e","label":"Schaltaktor   für Markenschalter – mit   Signalleuchte","lastStatusUpdate":1596480281203,"type":"BRAND_SWITCH_NOTIFICATION_LIGHT","functionalChannels":{"0":{"label":"","deviceId":"3014F711A0001A5A00000000","index":0,"groupIndex":0,"functionalChannelType":"DEVICE_BASE","groups":["41f35687-f495-46bf-a6eb-2cce2d7f25db"],"unreach":false,"lowBat":null,"routerModuleEnabled":false,"routerModuleSupported":false,"rssiDeviceValue":-53,"rssiPeerValue":-57,"configPending":false,"dutyCycle":false,"deviceOverloaded":false,"coProUpdateFailure":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceUndervoltage":false,"deviceOverheated":false,"temperatureOutOfRange":false,"devicePowerFailureDetected":false,"supportedOptionalFeatures":{"IFeatureDeviceCoProRestart":false,"IFeatureDeviceOverheated":true,"IFeatureDeviceUndervoltage":false,"IFeatureDeviceCoProUpdate":false,"IFeatureDeviceCoProError":false,"IFeatureDeviceOverloaded":false,"IFeatureDevicePowerFailure":false,"IFeatureDeviceIdentify":false,"IFeatureDeviceTemperatureOutOfRange":false}},"1":{"label":"","deviceId":"3014F711A0001A5A00000000","index":1,"groupIndex":1,"functionalChannelType":"SWITCH_CHANNEL","groups":[],"on":false,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC"},"2":{"label":"","deviceId":"3014F711A0001A5A00000000","index":2,"groupIndex":2,"functionalChannelType":"NOTIFICATION_LIGHT_CHANNEL","groups":[],"on":false,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC","dimLevel":0,"deviceOverloaded":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceOverheated":false,"supportedOptionalFeatures":{"IFeatureDeviceOverloaded":false},"simpleRGBColorState":"BLACK"},"3":{"label":"","deviceId":"3014F711A0001A5A00000000","index":3,"groupIndex":3,"functionalChannelType":"NOTIFICATION_LIGHT_CHANNEL","groups":[],"on":false,"profileMode":"AUTOMATIC","userDesiredProfileMode":"AUTOMATIC","dimLevel":0,"deviceOverloaded":false,"coProFaulty":false,"coProRestartNeeded":false,"deviceOverheated":false,"supportedOptionalFeatures":{"IFeatureDeviceOverloaded":false},"simpleRGBColorState":"BLACK"}},"oem":"eQ-3","manufacturerCode":1,"firmwareVersion":"1.0.2","firmwareVersionInteger":65538,"updateState":"UP_TO_DATE","liveUpdateState":"LIVE_UPDATE_NOT_SUPPORTED","availableFirmwareVersion":"1.0.2","serializedGlobalTradeItemNumber":"3014F711A0001A5A00000000","modelType":"HmIP-BSL","modelId":360,"permanentlyReachable":true,"connectionType":"HMIP_RF"}
--

**Comment by apex1834** [comment]
[hmip-bsl_ccu3states.zip](https://github.com/iobroker-community-adapters/ioBroker.hmip/files/5042766/hmip-bsl_ccu3states.zip)

@HornetRider81 Anbei die states aus der CCU3 für den HMIP-BSL

**Comment by HornetRider81** [comment]
Cool, danke
Werde ich mich mit beschäftigen, sobald Zeit ist.
Könntest du bitte auch noch Sceenshots vom Reiter "Allgemein" machen?

**Comment by Apollon77** [comment]
Ich hab mal einiges aktualisiert. Versucht mal GitHub Version. Wichtig: löscht ggf die Instanz oder mindestens die relevanten Objekte/Geräte sodass der Adapter es neu erzeugen kann.

**Comment by HornetRider81** [comment]
Hi, sorry hatte mich gar nicht mehr gemeldet. 
Meine Versuche waren leider erfolglos. 

Das Update teste ich so schnell wie möglich.

**Comment by HornetRider81** [comment]
Hallo, mit der neuen Version ist die LED weiterhin nicht steuerbar. Die Datenpunkte stehen auf "nur lesen", die von mir beschriebenen Parameter in "nativ", wie man die LED wenigsten ein/aus schalten kann, sind leer.

VG

**Comment by Apollon77** [comment]
Hast Du gelesen ... bitte mal die objekte löschen und dann adapter neu starten, dann sollten die objekte korrekt neu erzeugt werden

**Comment by HornetRider81** [comment]
Ich hatte die "devices" Liste vom Adapter komplett gelöscht, dann upgedatet, dann neu eingelesen.
Ich sehe ja, dass das die Datenpunke nun anders aussehen.

**Comment by HornetRider81** [comment]
> 
> Dann noch in "nativ" die drei Einträge "id", channel" und "parameter" anlegen. Bei "channel" den richtigen Kanal "2" oder "3" nehmen, die beiden anderen Werte vom Kanal 1 übernehmen.
> 

Nachdem ich schreiben wieder erlaubt habe und die zitierten Parameter im Reiter "nativ" angelegt habe. kann ich die LED wieder ein/aus schalten.

Ich probiere morgen nochmal neu aus.

**Comment by Apollon77** [comment]
Ok dann bitte nochmal ein Screenshot der angelegten Objekte und exakte Details  wo was in native fehlt. An sich habe ich es an die Stelle wo ich es gesehen habe angelegt. Vllt gibt es eine andere Stelle die ich gerade nicht sehe

**Comment by HornetRider81** [comment]
Hi,
hab jetzt nochmals alles geladen. Es fehlen nur die Einträge in "native" beim Datenpunkt "on". 
Helligkeit und Farbwechsel lassen sich leider trotzdem nicht steuern.

Im Log steht nur:


```
hmip.0 | 2020-09-17 12:22:14.570 | warn | (21261) Request error: StatusCodeError: 400 - {"errorCode":"INVALID_REQUEST"}
-- | -- | -- | --
hmip.0 | 2020-09-17 12:22:14.509 | info | (21261) state change - sendDoorCommand - id 3014F711A0001A58A9A23C68 - value 0.7
```
bzw
```
hmip.0 | 2020-09-17 12:21:16.767 | warn | (21261) Request error: StatusCodeError: 400 - {"errorCode":"INVALID_REQUEST"}
-- | -- | -- | --
hmip.0 | 2020-09-17 12:21:16.660 | info | (21261) state change - setRgbDimLevel - id 3014F711A0001A58A9A23C68 - value RED
```

**Comment by Apollon77** [comment]
bei welchem Objekt fehlt es denn exakt? zeig doch bitte mal nen screenshot von allen objekten des geräts. ich muss den chanel typ finden und so. Behandel mich mal so als ob ich von HMIP und allen Details KEINE Ahnung habe. Ich kenne nur den Code.
Die Fehler sagen an sich das diese Kommandos wohl irgendwie falsch laufen weil Sie ja abgelehnt werden ... also passt auch da was nicht

**Comment by HornetRider81** [comment]
Okay, ich versuche es mal ;)

Bild 1 zeigt die Übersicht vom Gerät. Es sind die Kanäle 2 und 3 die die LEDs steuern. 
![BSL1](https://user-images.githubusercontent.com/66309884/93504924-7247de80-f91a-11ea-8dda-02c63e9721b1.jpg)

Der Dstenpunkt, bei dem die Parameter fehlen:
![BSL2](https://user-images.githubusercontent.com/66309884/93504942-796eec80-f91a-11ea-973a-f47840ac90b1.jpg)

Die beiden nicht steuerbaren Elemente:
![BSL3](https://user-images.githubusercontent.com/66309884/93504968-825fbe00-f91a-11ea-9e25-66add9bf19bd.jpg)

![BSL4](https://user-images.githubusercontent.com/66309884/93505011-92779d80-f91a-11ea-90f4-e8b188c2f392.jpg)

Brauchst du noch mehr? 

Vielen Dank für dein Engagement

**Comment by Apollon77** [comment]
Perfekt, das war genau das was ich brauchte. Bitte nochmal Github versuchen und objekte vorher wieder löschen

**Comment by ubieberich** [comment]
Hallo, bei mir funktioniert die Ansteuerung der LED's jetzt. Super Arbeit. Danke

**Comment by Apollon77** [comment]
1.3.0 auf dem weg

**Comment by HornetRider81** [comment]
Hi, bei mir funktioniert es nun auch. 
Eine Kleinigkeit aber noch, beim Datenpunkt, bei dem die Parameter fehlten, zweites Bild im vorherigen Post, fehlen die Schreibrechte.
