### ISSUE TITLE
Eco Modus Schalter

### ISSUE THREAD

**Issue by TobiasF1986** [iobroker-community-adapters/ioBroker.hmip#79]
Hallo.
Wäre es möglich einen "Schalter" für den zeitlich unendlichen Ecomodus bei Heizungssteuerungen zu implementieren? Aktuelle muss man in Absence z.B. immer einen hohen Wert schreiben für einen andauernden Eco Modus.

**Comment by SliX185** [comment]
Servus!
Workaround wäre, falls eine Alexa im Haus ist und der dazugehörige Adapter auch läuft, über diesen den ECO Modus zu schalten ( ECO Modus - > active = true / false)

**Comment by HornetRider81** [comment]
Hallo, 
ich möchte mich der Bitte um einen Schalter für den permanenten ECO-Modus anschliessen.
Eine Implementierung wäre super.

**Comment by JustDoneNow** [comment]
Ich fände eine Umsetzung auch super.

**Comment by SliX185** [comment]
So wie ich die API von coreGreenberet lese, gibt diese leider keinen PERMANENTEN ECO Betrieb her... und somit wird's auch keinen Button für Permanentes Eco geben, solange sich die API nicht ändert.

Es kann lediglich der Datenpunkt "setAbsenceEndTime" 
mit z.B: "2100_12_31 23:59" gesetzt werden, was einen permanenten Betrieb gleich käme, jedoch mit dem Schönheitsfehler, dass kein "Dauerhafter Ecobetrieb" in der App angezeigt wird.
