### ISSUE TITLE
Wettersensor PLUS enthält keine Daten vom einfachen Wettersensor

### ISSUE THREAD

**Issue by mccrossen** [iobroker-community-adapters/ioBroker.hmip#90]
Hallo,
im Wettersensor PLUS (HmIP-SWO-PL) sind leider nur die PLUS-Werte enthalten und keine Werte vom einfachen Wettersensor. Eventuell funktioniert dieser Subaufruf nicht richtig:
https://github.com/iobroker-community-adapters/ioBroker.hmip/blob/9c7a161de5d9071b01471fa96f8078cbded34a39/main.js#L667

Gruß

Marcel

**Comment by marcus0303** [comment]
@mccrossen 
Ich habe da noch etwas entdeckt, dass wahrscheinlich die Ursache für den Fehler ist.
Dies hängt zwar nicht mit dem von dir genannten Aufruf zusammen, aber es hat auf jeden Fall geholfen. Ich werde die Korrektur in Kürze vornehmen.
