### ISSUE TITLE
Scharfschaltungs-Zustand der Alarmanlage als eigener Parameter

### ISSUE THREAD

**Issue by epcos71** [iobroker-community-adapters/ioBroker.hmip#94]
Der aktuelle Zustand der Alarmanlage über die Gruppe "SecurityAndAlarm" sollte auslesbar sein. Aktuell ist es schwierig das mit den vorhandenen Parametern, z.B. "ActivationInProgress" nachzubauen. Ein einfacher Parameter mit true oder false wäre hier echt eine geniale Lösung. Falls es da schon eine andere Lösung geben sollte, ich wäre für jeden Tip dankbar.

**Comment by HornetRider81** [comment]
Hallo,

ich möchte mich der Bitte anschließen.
Eine Implementierung wäre super.

**Comment by JustDoneNow** [comment]
Ich bin gestern auch darüber gestolpert und würde mich über eine Implementierung freuen.
