### ISSUE TITLE
Homematic IP smoke detector status

### ISSUE THREAD

**Issue by firechhe** [iobroker-community-adapters/ioBroker.hmip#95]
Hello,

I want to send a pushover message if a smoke detector triggers. But I dont know which status I should use? I havent found the right status:

![rm](https://user-images.githubusercontent.com/43295016/76686948-e7f78880-661f-11ea-89ee-67fdf0e903b0.jpg)

Can someone help me?

**Comment by marcus0303** [comment]
@firechhe 
It should be smokeDetectorAlarmType.
I haven't a HMIP SmokeDetector, so i don't know the state if it triggers (instead of IDLE_OFF).
Perhaps you could trigger an alarm by yourself and take a look at the state of smokeDetectorArlarmType.
regards

**Comment by kkickingereder** [comment]
Looks like the HomematicIPCloud Adapter doesnt show this datapoints only CCU2/3 shows them.
Developer should clarify.

**Comment by marcus0303** [comment]
@kkickingereder 
Could you tell me the datapoints on CCU for the Smoke_Detector? THX in advance

**Comment by kkickingereder** [comment]
Hi @marcus0303 , many thanks for taking care

Datapoints on CCU are
![image](https://user-images.githubusercontent.com/61472717/77818564-be386a00-70d3-11ea-9731-ed35277570a9.png)

whereas on HMIP Adapter only following Datapoints appear special on channel 1 the dp are missing
![image](https://user-images.githubusercontent.com/61472717/77818579-dad4a200-70d3-11ea-8f22-36064f6134f7.png)

**Comment by marcus0303** [comment]
@kkickingereder 
Thank you for posting the datapoints from CCU.
Unfortunately i couldn't find this datapoints in the APIs, only the dp smokeDetectorAlarmType.
I guess that the HMIP Cloud returns only this one dp with it states: 
    IDLE_OFF
    PRIMARY_ALARM
    INTRUSION_ALARM
    SECONDARY_ALARM
@firechhe 
Perhaps you could use this information for your project.
Sorry and best regards

**Comment by jogibear9988** [comment]
That means not possible, so I close this...
