### ISSUE TITLE
Searching for Maintainers

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.hmip#97]
Hello, since I don't use this Adapter myself, I've very Limited resources to work on this.
Is anyone interested to look after the Adapter and work on issues, and look after pull requests?

**Comment by smarthome43372** [comment]
Hello, as I do not have deep knowledge in programming I can offer testing and providing logs.

**Comment by mueckeflo** [comment]
Same here. Just tell me how I can help and I'm happy to do so

**Comment by SWU-DEV** [comment]
I can help you!
I just opend an issue (unkown channel type) with a fix for it. But u will need to update the main.js, a file is with the issue, to fix that.
